// Generated by `npm run bundle` from src/server.ts. Do not edit.

// src/server.ts
import postgres from "postgres";

// src/fetcher.ts
var UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
var FetchError = class extends Error {
  status;
  blocked;
  constructor(message, status, blocked) {
    super(message);
    this.name = "FetchError";
    this.status = status;
    this.blocked = blocked;
  }
};
function looksGzipped(url, contentType) {
  if (/\.gz(\?|$)/i.test(url)) return true;
  return /application\/(x-)?gzip/i.test(contentType ?? "");
}
async function gunzip(res) {
  if (!res.body) return "";
  const stream = res.body.pipeThrough(new DecompressionStream("gzip"));
  return new Response(stream).text();
}
async function fetchText(url, headers = {}, timeoutMs = 2e4) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": UA, Accept: "*/*", ...headers },
      signal: controller.signal,
      redirect: "follow"
    });
    if (!res.ok) {
      const blocked = res.status === 403 || res.status === 429 || res.status === 503;
      throw new FetchError(
        `${res.status} ${res.statusText || ""}`.trim() + (blocked ? " \u2014 looks like a block; this source needs the Watcher" : ""),
        res.status,
        blocked
      );
    }
    return looksGzipped(url, res.headers.get("content-type")) ? await gunzip(res) : await res.text();
  } catch (err) {
    if (err instanceof FetchError) throw err;
    const msg = err instanceof Error ? err.message : String(err);
    throw new FetchError(msg, 0, false);
  } finally {
    clearTimeout(timer);
  }
}
async function probeUrl(url, headers = {}) {
  const started = Date.now();
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": UA, Accept: "*/*", ...headers },
      redirect: "follow"
    });
    const blocked = res.status === 403 || res.status === 429 || res.status === 503;
    let note = "";
    if (res.ok && res.body) {
      const reader = res.body.getReader();
      const { value } = await reader.read();
      await reader.cancel().catch(() => {
      });
      const bytes = value?.length ?? 0;
      const head = new TextDecoder().decode((value ?? new Uint8Array()).slice(0, 200));
      note = /^\x1f\x8b/.test(head) || /gzip/i.test(res.headers.get("content-type") ?? "") ? `gzipped, ${bytes}B read` : /<sitemapindex/i.test(head) ? "sitemap index" : /<urlset/i.test(head) ? "sitemap" : `${bytes}B read`;
    } else if (blocked) {
      note = "blocked \u2014 this source needs the Watcher";
    } else if (!res.ok) {
      note = res.statusText || "not ok";
    }
    return { url, ok: res.ok, status: res.status, blocked, ms: Date.now() - started, note };
  } catch (err) {
    return {
      url,
      ok: false,
      status: 0,
      blocked: false,
      ms: Date.now() - started,
      note: err instanceof Error ? err.message : String(err)
    };
  }
}

// src/parsers/sitemap.ts
var LOC_RE = /<loc>([\s\S]*?)<\/loc>/gi;
var CDATA_RE = /^\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*$/;
var ENTITIES = {
  "&amp;": "&",
  "&lt;": "<",
  "&gt;": ">",
  "&quot;": '"',
  "&apos;": "'",
  "&#39;": "'"
};
function decodeEntities(s) {
  return s.replace(/&(?:amp|lt|gt|quot|apos|#39);/g, (m) => ENTITIES[m] ?? m);
}
function sitemapKind(xml) {
  const head = xml.slice(0, 4e3);
  if (/<sitemapindex[\s>]/i.test(head)) return "index";
  if (/<urlset[\s>]/i.test(head)) return "urlset";
  return "unknown";
}
function extractLocs(xml) {
  const out = [];
  LOC_RE.lastIndex = 0;
  let m;
  while ((m = LOC_RE.exec(xml)) !== null) {
    let raw = m[1] ?? "";
    const cdata = CDATA_RE.exec(raw);
    if (cdata) raw = cdata[1] ?? "";
    const value = decodeEntities(raw.trim());
    if (value) out.push(value);
  }
  return out;
}

// src/parsers/jsonList.ts
function pluck(obj, path) {
  if (!path) return obj;
  let cur = obj;
  for (const rawPart of path.split(".")) {
    const part = rawPart.trim();
    if (!part) continue;
    const idx = /^\[(\d+)\]$/.exec(part);
    if (idx) {
      if (!Array.isArray(cur)) return void 0;
      cur = cur[Number(idx[1])];
      continue;
    }
    if (cur === null || typeof cur !== "object") return void 0;
    cur = cur[part];
  }
  return cur;
}
function str(v) {
  if (v === null || v === void 0) return "";
  if (typeof v === "string") return v;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return "";
}
function num(v) {
  if (typeof v === "number" && Number.isFinite(v)) return v;
  if (typeof v === "string") {
    const n = Number(v.replace(/[^0-9.]/g, ""));
    return Number.isFinite(n) ? n : null;
  }
  return null;
}
function parseJsonList(payload, config) {
  const raw = pluck(payload, config.itemsPath ?? "");
  if (!Array.isArray(raw)) return [];
  const idField = config.idField ?? "id";
  const nameField = config.nameField ?? "title";
  const urlField = config.urlField ?? "url";
  const out = [];
  for (const item of raw) {
    if (item === null || typeof item !== "object") continue;
    const externalId = str(pluck(item, idField)).trim();
    if (!externalId) continue;
    out.push({
      externalId,
      name: str(pluck(item, nameField)).trim() || externalId,
      url: str(pluck(item, urlField)).trim(),
      price: config.priceField ? num(pluck(item, config.priceField)) : null
    });
  }
  return out;
}

// src/parsers/identify.ts
var TARGET_TCIN = /\/-\/A-(\w+)/i;
var PC_PRODUCT = /\/product\/([^/?#]+)/i;
var WALMART_IP = /\/ip\/(?:([^/?#]+)\/)?(\d{5,})/i;
function titleise(slug) {
  const cleaned = slug.replace(/[-_+]+/g, " ").replace(/\.(html?|aspx)$/i, "").replace(/\s+/g, " ").trim();
  if (!cleaned) return "";
  return cleaned.split(" ").map((w) => w.length > 2 ? w[0].toUpperCase() + w.slice(1) : w).join(" ");
}
function lastSegment(pathname) {
  const parts = pathname.split("/").filter(Boolean);
  return parts.length ? parts[parts.length - 1] : "";
}
function fromUrl(rawUrl, retailer) {
  let u;
  try {
    u = new URL(rawUrl);
  } catch {
    return null;
  }
  const path = u.pathname;
  const tcin = TARGET_TCIN.exec(path);
  if (tcin) {
    const slug = path.split("/-/")[0]?.replace(/^\/p\//, "") ?? "";
    return {
      externalId: tcin[1],
      name: titleise(slug) || tcin[1],
      url: `${u.origin}${path}`
    };
  }
  const wm = WALMART_IP.exec(path);
  if (wm) {
    const slug = wm[1] ?? "";
    const itemId = wm[2];
    return {
      externalId: itemId,
      name: titleise(slug) || itemId,
      url: `${u.origin}${path}`
    };
  }
  const pc = PC_PRODUCT.exec(path);
  if (pc) {
    const id = pc[1];
    const rest = path.slice(pc.index + pc[0].length).replace(/^\//, "");
    return {
      externalId: id,
      name: titleise(rest) || titleise(id),
      url: `${u.origin}${path}`
    };
  }
  const seg = lastSegment(path);
  if (!seg || seg.length < 3) return null;
  return {
    externalId: `${retailer}:${seg}`.toLowerCase(),
    name: titleise(seg),
    url: `${u.origin}${path}`
  };
}
function productKey(name, fallback) {
  const base = (name || fallback).toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 48);
  return `prd_${base || "unknown"}`;
}
var HOSTS = [
  { match: /(^|\.)target\.com$/i, product: /\/p\/(?:[^?#]*\/)?-\/A-\w+/i, retailer: "Target" },
  {
    match: /(^|\.)pokemoncenter\.com$/i,
    product: /\/product\/[^/?#]+/i,
    retailer: "Pokemon Center"
  },
  { match: /(^|\.)walmart\.com$/i, product: /\/ip\/(?:[^/?#]+\/)?\d{5,}/i, retailer: "Walmart" }
];
function identifyListing(rawUrl) {
  let u;
  try {
    u = new URL(rawUrl.trim());
  } catch {
    return null;
  }
  if (u.protocol !== "https:" && u.protocol !== "http:") return null;
  const host = HOSTS.find((h) => h.match.test(u.hostname));
  if (!host) return null;
  if (!host.product.test(u.pathname)) return null;
  const found = fromUrl(u.toString(), host.retailer);
  if (!found?.externalId) return null;
  return {
    retailer: host.retailer,
    externalId: found.externalId,
    name: found.name,
    url: found.url || u.toString()
  };
}

// src/filter.ts
function fold(s) {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
}
function matches(item, filters) {
  if (!filters || filters.length === 0) return true;
  const hay = fold(`${item.name} ${item.url}`);
  return filters.some((f) => {
    const needle = fold(f).trim();
    return needle.length > 0 && hay.includes(needle);
  });
}
function applyFilters(items, filters) {
  if (!filters || filters.length === 0) return items;
  return items.filter((i) => matches(i, filters));
}
function dedupe(items) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const item of items) {
    if (!item.externalId || seen.has(item.externalId)) continue;
    seen.add(item.externalId);
    out.push(item);
  }
  return out;
}

// src/store.ts
function toPrice(v) {
  if (v === null || v === void 0 || v === "") return null;
  const n = typeof v === "number" ? v : Number(v);
  return Number.isFinite(n) && n > 0 ? n : null;
}
function toDate(v) {
  if (v === null || v === void 0 || v === "") return null;
  if (v instanceof Date) {
    return Number.isNaN(v.getTime()) ? null : v.toISOString().slice(0, 10);
  }
  const s = String(v);
  if (/^\d{4}-\d{2}-\d{2}/.test(s)) return s.slice(0, 10);
  const parsed = new Date(s);
  return Number.isNaN(parsed.getTime()) ? null : parsed.toISOString().slice(0, 10);
}
function toConfig(v) {
  if (v && typeof v === "object") return v;
  try {
    return JSON.parse(String(v || "{}"));
  } catch {
    return {};
  }
}
function toSource(row) {
  return {
    id: String(row.id),
    label: String(row.label ?? ""),
    retailer: String(row.retailer ?? ""),
    kind: row.kind,
    url: String(row.url ?? ""),
    via: row.via,
    config: toConfig(row.config),
    enabled: row.enabled === true,
    seeded: row.seeded === true,
    cursor: Number(row.cursor ?? 0),
    lastSweptAt: row.last_swept_at ? String(row.last_swept_at) : null,
    lastStatus: String(row.last_status ?? ""),
    lastCount: Number(row.last_count ?? 0)
  };
}
async function listSources(db2, via) {
  const rows = via ? await db2.query("SELECT * FROM sources WHERE enabled = true AND via = $1 ORDER BY id", [via]) : await db2.query("SELECT * FROM sources WHERE enabled = true ORDER BY id");
  return rows.map(toSource);
}
async function listAllSources(db2) {
  const rows = await db2.query("SELECT * FROM sources ORDER BY retailer, id");
  return rows.map(toSource);
}
async function getSource(db2, id) {
  const rows = await db2.query("SELECT * FROM sources WHERE id = $1", [id]);
  return rows[0] ? toSource(rows[0]) : null;
}
async function knownIds(db2, sourceId) {
  const rows = await db2.query(
    "SELECT external_id FROM discoveries WHERE source_id = $1",
    [sourceId]
  );
  return new Set(rows.map((r) => r.external_id));
}
async function recordDiscoveries(db2, sourceId, items, announce2) {
  if (items.length === 0) return [];
  const statements = items.map((item) => ({
    text: `INSERT INTO discoveries (source_id, external_id, url, name, price, announced)
           VALUES ($1, $2, $3, $4, $5, $6)
           ON CONFLICT (source_id, external_id) DO NOTHING`,
    params: [sourceId, item.externalId, item.url, item.name, item.price ?? null, !announce2]
  }));
  await db2.batch(statements);
  return announce2 ? items : [];
}
async function markAnnounced(db2, sourceId, externalIds) {
  if (externalIds.length === 0) return;
  await db2.query(
    "UPDATE discoveries SET announced = true WHERE source_id = $1 AND external_id = ANY($2)",
    [sourceId, externalIds]
  );
}
async function attachIdentity(db2, sourceId, retailer, item) {
  const existing = await db2.query(
    "SELECT product_key FROM aliases WHERE kind = $1 AND retailer = $2 AND value = $3",
    ["retailer_sku", retailer, item.externalId]
  );
  if (existing[0]?.product_key) return existing[0].product_key;
  const key = productKey(item.name, item.externalId);
  await db2.batch([
    {
      text: "INSERT INTO products (key, name) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING",
      params: [key, item.name]
    },
    {
      text: `INSERT INTO aliases (product_key, kind, retailer, value) VALUES ($1, $2, $3, $4)
             ON CONFLICT (kind, retailer, value) DO NOTHING`,
      params: [key, "retailer_sku", retailer, item.externalId]
    },
    {
      text: "UPDATE discoveries SET product_key = $1 WHERE source_id = $2 AND external_id = $3",
      params: [key, sourceId, item.externalId]
    }
  ]);
  return key;
}
async function finishSweep(db2, sourceId, status, count, seeded, cursor = 0) {
  await db2.query(
    `UPDATE sources
        SET last_swept_at = now(), last_status = $1, last_count = $2,
            seeded = $3, cursor = $4
      WHERE id = $5`,
    [status.slice(0, 300), count, seeded, cursor, sourceId]
  );
}
async function logEvent(db2, kind, message, data = null) {
  await db2.query("INSERT INTO events (kind, message, data) VALUES ($1, $2, $3)", [
    kind,
    message.slice(0, 1e3),
    data === null || data === void 0 ? null : JSON.stringify(data).slice(0, 4e3)
  ]);
}
async function watchlist(db2) {
  const rows = await db2.query(
    `SELECT l.id, l.product_key, p.name, p.release_date, l.retailer, l.external_id, l.url
       FROM listings l
       JOIN products p ON p.key = l.product_key
      ORDER BY p.name, l.retailer`
  );
  return rows.map((r) => ({
    listingId: Number(r.id),
    productKey: String(r.product_key),
    name: String(r.name ?? ""),
    retailer: String(r.retailer ?? ""),
    externalId: String(r.external_id ?? ""),
    url: String(r.url ?? ""),
    releaseDate: toDate(r.release_date)
  }));
}
function toProduct(r) {
  return {
    key: String(r.key),
    name: String(r.name ?? ""),
    releaseDate: toDate(r.release_date),
    msrp: toPrice(r.msrp),
    imageUrl: String(r.image_url ?? ""),
    notes: String(r.notes ?? "")
  };
}
function keyForName(name) {
  const slug = name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 60);
  return `prd_${slug || "unnamed"}`;
}
async function listProducts(db2) {
  const rows = await db2.query("SELECT * FROM products ORDER BY name");
  return rows.map(toProduct);
}
function validateProduct(p) {
  if (!p.name?.trim()) return "a product needs a name";
  if (p.name.trim().length > 200) return "that name is too long";
  if (p.msrp !== void 0 && p.msrp !== null && !(p.msrp > 0)) {
    return "MSRP must be greater than zero, or left blank";
  }
  if (p.releaseDate && !/^\d{4}-\d{2}-\d{2}$/.test(p.releaseDate)) {
    return "a release date must look like 2026-09-26";
  }
  if (p.imageUrl && !/^https?:\/\//i.test(p.imageUrl)) {
    return "an image URL must start with http:// or https://";
  }
  return null;
}
async function upsertProduct(db2, p) {
  const problem = validateProduct(p);
  if (problem) throw new Error(problem);
  const key = p.key?.trim() || keyForName(p.name);
  const rows = await db2.query(
    `INSERT INTO products (key, name, release_date, msrp, image_url, notes)
     VALUES ($1, $2, $3, $4, $5, $6)
     ON CONFLICT (key) DO UPDATE SET
       name = EXCLUDED.name,
       -- COALESCE, not EXCLUDED: an edit that omits a field must not blank a
       -- value someone already took the trouble to set.
       release_date = COALESCE(EXCLUDED.release_date, products.release_date),
       msrp = COALESCE(EXCLUDED.msrp, products.msrp),
       image_url = CASE WHEN EXCLUDED.image_url = '' THEN products.image_url ELSE EXCLUDED.image_url END,
       notes = CASE WHEN EXCLUDED.notes = '' THEN products.notes ELSE EXCLUDED.notes END
     RETURNING *`,
    [key, p.name.trim(), p.releaseDate || null, p.msrp ?? null, p.imageUrl ?? "", p.notes ?? ""]
  );
  return toProduct(rows[0]);
}
async function deleteProduct(db2, key) {
  await db2.query("DELETE FROM products WHERE key = $1", [key]);
}
function toListing(r) {
  return {
    id: Number(r.id),
    productKey: String(r.product_key),
    productName: String(r.product_name ?? ""),
    retailer: String(r.retailer ?? ""),
    externalId: String(r.external_id ?? ""),
    url: String(r.url ?? ""),
    sellerKind: String(r.seller_kind ?? "unknown"),
    sellerName: String(r.seller_name ?? ""),
    isPrimary: r.is_primary === true
  };
}
async function listListings(db2, productKey2) {
  const sql = `SELECT l.*, p.name AS product_name FROM listings l
                 JOIN products p ON p.key = l.product_key
                ${productKey2 ? "WHERE l.product_key = $1" : ""}
                ORDER BY p.name, l.retailer`;
  const rows = productKey2 ? await db2.query(sql, [productKey2]) : await db2.query(sql);
  return rows.map(toListing);
}
async function addListing(db2, l) {
  const rows = await db2.query(
    `INSERT INTO listings (product_key, retailer, external_id, url)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (retailer, external_id) DO UPDATE SET
       url = EXCLUDED.url,
       product_key = EXCLUDED.product_key
     RETURNING *`,
    [l.productKey, l.retailer.trim(), l.externalId.trim(), l.url.trim()]
  );
  const [full] = await db2.query(
    "SELECT l.*, p.name AS product_name FROM listings l JOIN products p ON p.key = l.product_key WHERE l.id = $1",
    [rows[0].id]
  );
  return toListing(full);
}
async function deleteListing(db2, id) {
  await db2.query("DELETE FROM listings WHERE id = $1", [id]);
}
function toMission(r) {
  const iso = (v) => v ? new Date(String(v)).toISOString() : "";
  return {
    id: Number(r.id),
    listingId: Number(r.listing_id),
    productKey: String(r.product_key ?? ""),
    productName: String(r.product_name ?? ""),
    imageUrl: String(r.image_url ?? ""),
    msrp: toPrice(r.msrp),
    retailer: String(r.retailer ?? ""),
    externalId: String(r.external_id ?? ""),
    url: String(r.url ?? ""),
    label: String(r.label ?? ""),
    enabled: r.enabled === true,
    armed: r.armed === true,
    ceiling: toPrice(r.ceiling),
    quantity: Number(r.quantity ?? 1),
    sellerPolicy: String(r.seller_policy ?? "retailer_only"),
    checkEverySeconds: Number(r.check_every_s ?? 60),
    checkNow: r.check_now_at !== null && r.check_now_at !== void 0,
    notes: String(r.notes ?? ""),
    state: String(r.state ?? "unchecked"),
    confidence: String(r.confidence ?? "unknown"),
    price: toPrice(r.price),
    sellerKind: String(r.ws_seller_kind ?? r.seller_kind ?? "unknown"),
    sellerName: String(r.ws_seller_name ?? r.seller_name ?? ""),
    availableQuantity: r.available_quantity === null || r.available_quantity === void 0 ? null : Number(r.available_quantity),
    orderLimit: r.order_limit === null || r.order_limit === void 0 ? null : Number(r.order_limit),
    isPreOrder: r.is_preorder === true,
    releaseDate: toDate(r.release_date),
    note: String(r.note ?? ""),
    lastCheckedAt: iso(r.last_checked_at),
    lastChangedAt: iso(r.last_changed_at)
  };
}
var MISSION_SELECT = `
  SELECT m.*, l.product_key, l.retailer, l.external_id, l.url,
         p.name AS product_name, p.image_url, p.msrp,
         COALESCE(w.state, 'unchecked') AS state,
         COALESCE(w.confidence, 'unknown') AS confidence,
         w.price,
         COALESCE(w.seller_kind, l.seller_kind) AS ws_seller_kind,
         COALESCE(NULLIF(w.seller_name, ''), l.seller_name) AS ws_seller_name,
         w.available_quantity, w.order_limit,
         COALESCE(w.is_preorder, false) AS is_preorder,
         COALESCE(w.release_date, p.release_date) AS release_date,
         COALESCE(w.note, '') AS note,
         w.last_checked_at, w.last_changed_at
    FROM missions m
    JOIN listings l ON l.id = m.listing_id
    JOIN products p ON p.key = l.product_key
    LEFT JOIN watch_state w ON w.listing_id = l.id`;
async function listMissions(db2) {
  const rows = await db2.query(`${MISSION_SELECT}
    ORDER BY
      CASE COALESCE(w.state, 'unchecked')
        WHEN 'in' THEN 0 WHEN 'queue' THEN 1 WHEN 'unknown' THEN 2
        WHEN 'unchecked' THEN 3 ELSE 4 END,
      m.armed DESC, p.name, l.retailer`);
  return rows.map(toMission);
}
async function getMission(db2, id) {
  const rows = await db2.query(`${MISSION_SELECT} WHERE m.id = $1`, [id]);
  return rows[0] ? toMission(rows[0]) : null;
}
async function requestCheckNow(db2, id) {
  const rows = await db2.query(
    "UPDATE missions SET check_now_at = now() WHERE id = $1 RETURNING id",
    [id]
  );
  return rows.length > 0;
}
async function activeMissions(db2) {
  const rows = await db2.query(`${MISSION_SELECT} WHERE m.enabled = true ORDER BY m.id`);
  return rows.map(toMission);
}
function validateMission(m) {
  if (!Number.isFinite(m.listingId) || m.listingId <= 0) return "a mission needs a listing";
  const quantity = m.quantity ?? 1;
  if (!Number.isInteger(quantity) || quantity < 1 || quantity > 20) {
    return "quantity must be a whole number between 1 and 20";
  }
  if (m.ceiling !== void 0 && m.ceiling !== null && !(m.ceiling > 0)) {
    return "a price ceiling must be greater than zero";
  }
  if (m.armed && (m.ceiling === void 0 || m.ceiling === null)) {
    return "set a price ceiling before arming \u2014 armed with no ceiling is an open cheque";
  }
  if (m.sellerPolicy && !["retailer_only", "any"].includes(m.sellerPolicy)) {
    return "seller policy must be retailer_only or any";
  }
  const every = m.checkEverySeconds ?? 60;
  if (!Number.isInteger(every) || every < 30 || every > 86400) {
    return "check interval must be between 30 seconds and a day";
  }
  return null;
}
async function upsertMission(db2, m) {
  const problem = validateMission(m);
  if (problem) throw new Error(problem);
  const rows = await db2.query(
    `INSERT INTO missions (listing_id, label, enabled, armed, ceiling, quantity,
                           seller_policy, check_every_s, notes)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
     ON CONFLICT (listing_id) DO UPDATE SET
       label = EXCLUDED.label,
       enabled = EXCLUDED.enabled,
       armed = EXCLUDED.armed,
       ceiling = EXCLUDED.ceiling,
       quantity = EXCLUDED.quantity,
       seller_policy = EXCLUDED.seller_policy,
       check_every_s = EXCLUDED.check_every_s,
       notes = EXCLUDED.notes
     RETURNING id`,
    [
      m.listingId,
      m.label ?? "",
      m.enabled ?? true,
      m.armed ?? false,
      m.ceiling ?? null,
      m.quantity ?? 1,
      m.sellerPolicy ?? "retailer_only",
      m.checkEverySeconds ?? 60,
      m.notes ?? ""
    ]
  );
  const mission = await getMission(db2, Number(rows[0].id));
  if (!mission) throw new Error("mission vanished immediately after being written");
  return mission;
}
async function deleteMission(db2, id) {
  await db2.query("DELETE FROM missions WHERE id = $1", [id]);
}
async function startRun(db2, missionId) {
  const rows = await db2.query("INSERT INTO mission_runs (mission_id) VALUES ($1) RETURNING id", [
    missionId
  ]);
  return Number(rows[0].id);
}
async function finishRun(db2, runId, r) {
  const needsReason = r.outcome !== "bought" && r.outcome !== "in_stock";
  const reason = (r.reason ?? "").trim() || (needsReason ? `${r.outcome}, no reason recorded` : "");
  await db2.query(
    `UPDATE mission_runs
        SET finished_at = now(),
            outcome = $1, reason = $2, state = $3, price = $4,
            seller_kind = $5, seller_name = $6, quantity = $7, total = $8,
            ms = GREATEST(0, EXTRACT(EPOCH FROM (now() - started_at)) * 1000)::int
      WHERE id = $9`,
    [
      r.outcome,
      reason.slice(0, 500),
      r.state ?? "",
      r.price ?? null,
      r.sellerKind ?? "",
      r.sellerName ?? "",
      r.quantity ?? null,
      r.total ?? null,
      runId
    ]
  );
}
async function recordRun(db2, missionId, r) {
  const id = await startRun(db2, missionId);
  await finishRun(db2, id, r);
  return id;
}
function toRun(r) {
  const iso = (v) => v ? new Date(String(v)).toISOString() : "";
  return {
    id: Number(r.id),
    missionId: Number(r.mission_id),
    productName: String(r.product_name ?? ""),
    retailer: String(r.retailer ?? ""),
    startedAt: iso(r.started_at),
    finishedAt: iso(r.finished_at),
    outcome: String(r.outcome ?? "running"),
    reason: String(r.reason ?? ""),
    state: String(r.state ?? ""),
    price: toPrice(r.price),
    sellerKind: String(r.seller_kind ?? ""),
    sellerName: String(r.seller_name ?? ""),
    quantity: r.quantity === null || r.quantity === void 0 ? null : Number(r.quantity),
    total: toPrice(r.total),
    ms: r.ms === null || r.ms === void 0 ? null : Number(r.ms)
  };
}
var RUN_SELECT = `
  SELECT r.*, p.name AS product_name, l.retailer
    FROM mission_runs r
    JOIN missions m ON m.id = r.mission_id
    JOIN listings l ON l.id = m.listing_id
    JOIN products p ON p.key = l.product_key`;
async function missionRuns(db2, missionId, limit = 100) {
  const rows = await db2.query(
    `${RUN_SELECT} WHERE r.mission_id = $1 ORDER BY r.started_at DESC, r.id DESC LIMIT $2`,
    [missionId, Math.min(Math.max(limit, 1), 500)]
  );
  return rows.map(toRun);
}
async function recentRuns(db2, limit = 50) {
  const rows = await db2.query(
    `${RUN_SELECT} ORDER BY r.started_at DESC, r.id DESC LIMIT $1`,
    [Math.min(Math.max(limit, 1), 200)]
  );
  return rows.map(toRun);
}
async function recordObservation(db2, obs) {
  const prior = await db2.query(
    "SELECT state, price, seller_kind FROM watch_state WHERE listing_id = $1",
    [obs.listingId]
  );
  const before = prior[0] ?? null;
  const isFirst = before === null;
  const previousPrice = before ? toPrice(before.price) : null;
  const price = obs.price ?? null;
  const sellerKind = obs.sellerKind ?? "unknown";
  const changed = !isFirst && (before.state !== obs.state || previousPrice !== price || before.seller_kind !== sellerKind);
  await db2.query(
    `INSERT INTO watch_state (
       listing_id, state, confidence, price, seller_kind, seller_name,
       available_quantity, order_limit, is_preorder, release_date, note,
       last_checked_at, last_changed_at
     ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11, now(), now())
     ON CONFLICT (listing_id) DO UPDATE SET
       state = EXCLUDED.state,
       confidence = EXCLUDED.confidence,
       price = EXCLUDED.price,
       seller_kind = EXCLUDED.seller_kind,
       seller_name = EXCLUDED.seller_name,
       available_quantity = EXCLUDED.available_quantity,
       order_limit = EXCLUDED.order_limit,
       is_preorder = EXCLUDED.is_preorder,
       release_date = EXCLUDED.release_date,
       note = EXCLUDED.note,
       last_checked_at = now(),
       -- Only move this when something actually moved, so "in stock since"
       -- means what it says instead of resetting on every poll.
       last_changed_at = CASE WHEN $12 THEN now() ELSE watch_state.last_changed_at END`,
    [
      obs.listingId,
      obs.state,
      obs.confidence ?? "unknown",
      price,
      sellerKind,
      obs.sellerName ?? "",
      obs.availableQuantity ?? null,
      obs.orderLimit ?? null,
      obs.isPreOrder ?? false,
      obs.releaseDate ?? null,
      (obs.note ?? "").slice(0, 500),
      changed
    ]
  );
  await db2.query(
    "UPDATE missions SET check_now_at = NULL WHERE listing_id = $1 AND check_now_at IS NOT NULL",
    [obs.listingId]
  );
  if (sellerKind !== "unknown") {
    await db2.query("UPDATE listings SET seller_kind = $1, seller_name = $2 WHERE id = $3", [
      sellerKind,
      obs.sellerName ?? "",
      obs.listingId
    ]);
  }
  if (obs.imageUrl) {
    await db2.query(
      `UPDATE products SET image_url = $1
        WHERE image_url = ''
          AND key = (SELECT product_key FROM listings WHERE id = $2)`,
      [obs.imageUrl, obs.listingId]
    );
  }
  if (changed || isFirst) {
    await db2.query(
      `INSERT INTO observations
         (listing_id, state, confidence, price, seller_kind, seller_name,
          available_quantity, note)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
      [
        obs.listingId,
        obs.state,
        obs.confidence ?? "unknown",
        price,
        sellerKind,
        obs.sellerName ?? "",
        obs.availableQuantity ?? null,
        (obs.note ?? "").slice(0, 500)
      ]
    );
  }
  return { changed, isFirst, previousState: before?.state ?? null, previousPrice };
}
async function recentObservations(db2, limit = 50) {
  const rows = await db2.query(
    `SELECT o.listing_id, p.name AS product_name, l.retailer, o.state, o.price,
            o.seller_kind, o.seller_name, o.note, o.at
       FROM observations o
       JOIN listings l ON l.id = o.listing_id
       JOIN products p ON p.key = l.product_key
      ORDER BY o.at DESC, o.id DESC
      LIMIT $1`,
    [Math.min(Math.max(limit, 1), 200)]
  );
  return rows.map((r) => ({
    listingId: Number(r.listing_id),
    productName: String(r.product_name ?? ""),
    retailer: String(r.retailer ?? ""),
    state: String(r.state ?? ""),
    price: toPrice(r.price),
    sellerKind: String(r.seller_kind ?? "unknown"),
    sellerName: String(r.seller_name ?? ""),
    note: String(r.note ?? ""),
    at: r.at ? new Date(String(r.at)).toISOString() : ""
  }));
}

// src/discover.ts
var DEFAULT_CHILD_LIMIT = 3;
var MAX_ITEMS_PER_SWEEP = 5e3;
function rotate(items, cursor, limit) {
  if (items.length === 0 || limit <= 0) return [];
  if (limit >= items.length) return items.slice();
  const start = (cursor % items.length + items.length) % items.length;
  const out = [];
  for (let i = 0; i < limit; i++) out.push(items[(start + i) % items.length]);
  return out;
}
function nextCursor(cursor, limit, total) {
  if (total <= 0 || limit <= 0) return 0;
  return (cursor + limit) % total;
}
function productsFromSitemap(xml, retailer) {
  const locs = extractLocs(xml);
  const out = [];
  for (const loc of locs) {
    const item = fromUrl(loc, retailer);
    if (item) out.push(item);
  }
  return out;
}
async function collect(source, fetchText2) {
  const config = source.config;
  const headers = config.headers ?? {};
  if (source.kind === "json_list") {
    const text = await fetchText2(source.url, headers);
    let payload;
    try {
      payload = JSON.parse(text);
    } catch {
      throw new FetchError("response was not valid JSON", 0, false);
    }
    return { items: parseJsonList(payload, config), childTotal: 0 };
  }
  if (source.kind === "sitemap" || source.kind === "sitemap_index") {
    const text = await fetchText2(source.url, headers);
    const kind = sitemapKind(text);
    if (kind === "index" || source.kind === "sitemap_index") {
      const children = extractLocs(text);
      const limit = config.childLimit ?? DEFAULT_CHILD_LIMIT;
      const window = rotate(children, source.cursor ?? 0, limit);
      const all = [];
      for (const child of window) {
        try {
          const childXml = await fetchText2(child, headers);
          all.push(...productsFromSitemap(childXml, source.retailer));
        } catch (err) {
          console.warn("child sitemap failed", child, String(err));
        }
        if (all.length >= MAX_ITEMS_PER_SWEEP) break;
      }
      return { items: all, childTotal: children.length };
    }
    return { items: productsFromSitemap(text, source.retailer), childTotal: 0 };
  }
  return { items: [], childTotal: 0 };
}
async function sweepSource(db2, source, fetchText2 = fetchText) {
  const config = source.config;
  const base = {
    sourceId: source.id,
    label: source.label,
    ok: true,
    seen: 0,
    fresh: [],
    seeded: source.seeded
  };
  let collected;
  try {
    collected = await collect(source, fetchText2);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await finishSweep(db2, source.id, `error: ${message}`, 0, source.seeded, source.cursor ?? 0);
    await logEvent(db2, "sweep_error", `${source.label}: ${message}`);
    return { ...base, ok: false, error: message };
  }
  const items = dedupe(applyFilters(collected.items, config.filters)).slice(0, MAX_ITEMS_PER_SWEEP);
  const known = await knownIds(db2, source.id);
  const fresh = items.filter((i) => !known.has(i.externalId));
  const alreadySeeded = source.seeded;
  const announced = await recordDiscoveries(db2, source.id, fresh, alreadySeeded);
  for (const item of announced) {
    await attachIdentity(db2, source.id, source.retailer, item);
  }
  const limit = config.childLimit ?? DEFAULT_CHILD_LIMIT;
  const advanced = nextCursor(source.cursor ?? 0, limit, collected.childTotal);
  const lapComplete = collected.childTotal === 0 || advanced === 0;
  const nowSeeded = alreadySeeded || lapComplete;
  const status = alreadySeeded ? `ok, ${fresh.length} new of ${items.length}` : lapComplete ? `seeded ${fresh.length} on final pass` : `seeding, pass ends at child ${advanced} of ${collected.childTotal}`;
  await finishSweep(db2, source.id, status, items.length, nowSeeded, advanced);
  if (!alreadySeeded) {
    await logEvent(
      db2,
      "seed",
      `${source.label}: recorded ${fresh.length} silently (${status})`
    );
  }
  return { ...base, seen: items.length, fresh: announced, seeded: nowSeeded };
}
async function sweepAll(db2, fetchText2 = fetchText) {
  const sources = await listSources(db2, "hub");
  const results = [];
  for (const source of sources) {
    results.push(await sweepSource(db2, source, fetchText2));
  }
  return results;
}

// src/notify.ts
var COLOR_NEW = 2059087;
var COLOR_OPS = 9069584;
var MAX_FIELDS = 20;
function clip(s, n) {
  return s.length <= n ? s : `${s.slice(0, n - 1)}\u2026`;
}
function buildDiscoveryEmbed(label, retailer, items, now) {
  const shown = items.slice(0, MAX_FIELDS);
  const fields = shown.map((i) => ({
    name: clip(i.name || i.externalId, 240),
    value: clip(i.url ? `[${i.externalId}](${i.url})` : i.externalId, 1e3)
  }));
  const extra = items.length - shown.length;
  return {
    title: `\u{1F195} ${items.length} new ${items.length === 1 ? "product" : "products"} \u2014 ${retailer}`,
    description: `Seen for the first time in **${label}**.` + (extra > 0 ? `
_${extra} more not listed._` : ""),
    color: COLOR_NEW,
    fields,
    footer: { text: "catalog discovery \xB7 not a stock signal" },
    timestamp: now
  };
}
function buildOpsEmbed(results, now) {
  const failed = results.filter((r) => !r.ok);
  if (failed.length === 0) return null;
  return {
    title: `\u26A0\uFE0F ${failed.length} source${failed.length === 1 ? "" : "s"} failed`,
    color: COLOR_OPS,
    fields: failed.slice(0, MAX_FIELDS).map((r) => ({
      name: clip(r.label, 240),
      value: clip(r.error ?? "unknown error", 1e3)
    })),
    timestamp: now
  };
}
async function post(url, embeds) {
  if (!url || embeds.length === 0) return;
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ embeds: embeds.slice(0, 10) })
    });
    if (!res.ok && res.status !== 204) {
      const detail = await res.text().catch(() => "");
      console.warn("discord rejected the post", res.status, detail.slice(0, 300));
    }
  } catch (err) {
    console.warn("discord unreachable", err instanceof Error ? err.message : String(err));
  }
}
async function announce(webhookUrl, label, retailer, items, now) {
  if (items.length === 0) return;
  await post(webhookUrl, [buildDiscoveryEmbed(label, retailer, items, now)]);
}
async function reportOps(webhookUrl, results, now) {
  const embed = buildOpsEmbed(results, now);
  if (embed) await post(webhookUrl, [embed]);
}

// src/auth.ts
var SESSION_COOKIE = "hub_session";
var SESSION_HOURS = 24 * 14;
function b64url(bytes) {
  return Buffer.from(bytes).toString("base64url");
}
async function hmac(secret, message) {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return b64url(new Uint8Array(sig));
}
function safeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}
async function mintSession(secret, now = Date.now()) {
  const expires = now + SESSION_HOURS * 3600 * 1e3;
  const payload = String(expires);
  return `${payload}.${await hmac(secret, payload)}`;
}
async function sessionValid(secret, token, now = Date.now()) {
  if (!token) return false;
  const dot = token.lastIndexOf(".");
  if (dot < 1) return false;
  const payload = token.slice(0, dot);
  const signature = token.slice(dot + 1);
  const expected = await hmac(secret, payload);
  if (!safeEqual(signature, expected)) return false;
  const expires = Number(payload);
  return Number.isFinite(expires) && expires > now;
}
function readCookie(request, name) {
  const header = request.headers.get("cookie") ?? "";
  for (const part of header.split(";")) {
    const [k, ...rest] = part.trim().split("=");
    if (k === name) return decodeURIComponent(rest.join("="));
  }
  return null;
}
function sessionCookie(value, secure) {
  const bits = [
    `${SESSION_COOKIE}=${encodeURIComponent(value)}`,
    "Path=/",
    // HttpOnly: script on the page can never read it, so an injected script
    // cannot post the session anywhere.
    "HttpOnly",
    // Lax: the cookie is not sent on cross-site POSTs, which is the CSRF that
    // would otherwise let another tab trigger a buy.
    "SameSite=Lax",
    `Max-Age=${SESSION_HOURS * 3600}`
  ];
  if (secure) bits.push("Secure");
  return bits.join("; ");
}
function clearCookie(secure) {
  const bits = [`${SESSION_COOKIE}=`, "Path=/", "HttpOnly", "SameSite=Lax", "Max-Age=0"];
  if (secure) bits.push("Secure");
  return bits.join("; ");
}
async function identify(request, env2) {
  const header = request.headers.get("Authorization") ?? "";
  if (env2.INGEST_TOKEN && header.startsWith("Bearer ")) {
    if (safeEqual(header.slice(7), env2.INGEST_TOKEN)) return "watcher";
  }
  if (env2.APP_PASSWORD) {
    const cookie = readCookie(request, SESSION_COOKIE);
    if (await sessionValid(env2.APP_PASSWORD, cookie)) return "browser";
  }
  return "none";
}

// src/page.ts
function esc(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
var FONTS = '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=DM+Sans:wght@400;500;600;700&family=DM+Mono:wght@400;500&display=swap">';
var STYLE = `
:root {
  color-scheme: dark;
  --bg: #09080e;
  --panel: #17161f;
  --panel-2: rgba(237, 235, 245, .04);
  --line: rgba(237, 235, 245, .07);
  --line-strong: rgba(237, 235, 245, .13);
  --ink: #edebf5;
  --muted: #9b97b0;
  --dim: #6e6a85;

  --accent: #7f77dd;
  --accent-soft: rgba(127, 119, 221, .14);

  --in: #5fd3a0;      --in-bg: rgba(95, 211, 160, .13);
  --out: #9b97b0;     --out-bg: rgba(237, 235, 245, .07);
  --warn: #e0b060;    --warn-bg: rgba(224, 176, 96, .13);
  --alert: #f0836b;   --alert-bg: rgba(240, 131, 107, .13);

  --shadow: 0 8px 24px rgba(0,0,0,.35), 0 1px 3px rgba(0,0,0,.3);
  --r-card: 18px;
  --r-ctl: 13px;
  --r-sm: 9px;

  --sans: "DM Sans", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
  --display: Syne, var(--sans);
  --mono: "DM Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--ink); font: 15px/1.55 var(--sans); }
main { max-width: 1040px; margin: 0 auto; padding: 28px 20px 96px; }

header { display: flex; align-items: baseline; gap: 12px; flex-wrap: wrap; }
h1 { font: 800 26px/1.2 var(--display); margin: 0; letter-spacing: -0.02em; }
h2 { font: 700 12px/1.4 var(--display); text-transform: uppercase; letter-spacing: .1em;
     color: var(--dim); margin: 32px 0 10px; }
h3 { font: 700 14px/1.4 var(--display); margin: 0 0 8px; letter-spacing: -0.01em; }
.sub { color: var(--muted); font-size: 13px; }
a { color: var(--accent); text-underline-offset: 2px; }

.tabs { display: flex; gap: 2px; margin: 18px 0 16px; border-bottom: 1px solid var(--line); }
.tab { padding: 9px 16px; cursor: pointer; border: none; background: none;
       font: 500 14px/1.4 var(--sans); color: var(--muted);
       border-bottom: 2px solid transparent; border-radius: 0; }
.tab:hover { color: var(--ink); }
.tab.on { color: var(--ink); border-bottom-color: var(--accent); font-weight: 600; }
.tab .count { font-family: var(--mono); font-size: 12px; opacity: .6; margin-left: 6px; }

.bar { display: flex; gap: 10px; align-items: center; margin-bottom: 18px; flex-wrap: wrap; }
button, .btn {
  font: 600 14px/1.4 var(--sans); padding: 8px 15px; border-radius: var(--r-ctl);
  cursor: pointer; border: 1px solid var(--line-strong); background: var(--panel-2);
  color: var(--ink); text-decoration: none; display: inline-block;
  transition: border-color .12s, background .12s, opacity .12s;
}
button:hover:not(:disabled), .btn:hover { border-color: var(--accent); background: var(--accent-soft); }
button:disabled { opacity: .45; cursor: progress; }
button.primary { background: var(--accent); border-color: var(--accent); color: #fff; }
button.primary:hover:not(:disabled) { filter: brightness(1.1); background: var(--accent); }
button.danger { color: var(--alert); border-color: rgba(240,131,107,.35); }
button.danger:hover:not(:disabled) { background: var(--alert-bg); border-color: var(--alert); }
button.small { padding: 4px 10px; font-size: 12px; border-radius: var(--r-sm); }

.card { background: var(--panel); border: 1px solid var(--line);
        border-radius: var(--r-card); padding: 16px 18px; margin-bottom: 12px;
        box-shadow: var(--shadow); }
.row { display: flex; gap: 16px; align-items: flex-start; flex-wrap: wrap; }
.grow { flex: 1 1 260px; min-width: 0; }
.name { font: 600 15px/1.35 var(--sans); letter-spacing: -0.01em; }
.meta { color: var(--muted); font-size: 13px; }
.meta + .meta { margin-top: 3px; }
.price { font: 500 21px/1.2 var(--mono); letter-spacing: -0.02em; white-space: nowrap; }
.price.over { color: var(--alert); }
.price.under { color: var(--in); }
/* A fixed column, so prices line up down the page instead of each card
   deciding its own right edge. */
.right { text-align: right; flex: 0 0 auto; min-width: 152px; }
@media (max-width: 560px) { .right { text-align: left; min-width: 0; } }

/*
 * Tags.
 *
 * inline-flex with an explicit line-height, not inline-block: an inline-block
 * pill inherits the body's 1.55 line-height, so the text sits high in a box
 * that is taller than it needs to be, and each pill baseline-aligns against its
 * neighbours instead of centring in its own pill.
 *
 * text-indent cancels the letter-spacing. Letter-spacing adds its gap *after*
 * every character including the last, so the glyphs drift left of centre by
 * exactly one gap; indenting by the same amount puts them back.
 */
.pill {
  display: inline-flex; align-items: center; justify-content: center;
  padding: 3px 11px; border-radius: 999px; min-height: 22px;
  font: 600 11.5px/1.2 var(--sans);
  letter-spacing: .04em; text-indent: .04em; text-transform: uppercase;
  white-space: nowrap; vertical-align: middle;
}
/* A flex row with a gap, so spacing never depends on stray text nodes. */
.tags { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; margin-top: 10px; }
.s-in { background: var(--in-bg); color: var(--in); }
.s-out { background: var(--out-bg); color: var(--out); }
.s-unknown, .s-unchecked, .s-queue { background: var(--warn-bg); color: var(--warn); }
.flag { background: var(--alert-bg); color: var(--alert); }
.info { background: var(--accent-soft); color: var(--accent); }
.stale { color: var(--alert); font-weight: 600; }

.thumb { width: 60px; height: 60px; border-radius: var(--r-ctl); object-fit: contain;
         background: var(--panel-2); border: 1px solid var(--line); flex: 0 0 auto; }
.thumb.ph { display: flex; align-items: center; justify-content: center;
            color: var(--dim); font-size: 20px; }
.thumb.lg { width: 88px; height: 88px; }

form.stack { display: grid; gap: 11px; }
.grid2 { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 11px; }
label.f { display: grid; gap: 4px; font-size: 12px; color: var(--muted);
          font-weight: 500; letter-spacing: .01em; }
label.f .hint { font-weight: 400; color: var(--dim); }
label.check { display: flex; gap: 8px; align-items: center; font-size: 14px;
              color: var(--ink); cursor: pointer; }
input[type=text], input[type=url], input[type=number], input[type=date],
select, textarea, input[type=password] {
  font: 400 14px/1.5 var(--sans); padding: 9px 11px; border-radius: var(--r-ctl); width: 100%;
  border: 1px solid var(--line-strong); background: var(--bg); color: var(--ink);
}
input::placeholder, textarea::placeholder { color: var(--dim); }
input:focus, select:focus, textarea:focus {
  outline: none; border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-soft);
}
textarea { min-height: 64px; resize: vertical; }
.actions { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; }

.msg { font-size: 13px; min-height: 18px; }
.msg.bad { color: var(--alert); }
.msg.good { color: var(--in); }
.empty { color: var(--muted); padding: 38px 16px; text-align: center;
         border: 1px dashed var(--line-strong); border-radius: var(--r-card); }
.empty strong { color: var(--ink); display: block; margin-bottom: 5px;
                font: 700 15px/1.4 var(--display); }

table { width: 100%; border-collapse: collapse; font-size: 13px; }
td, th { padding: 8px; border-top: 1px solid var(--line); vertical-align: top; text-align: left; }
th { color: var(--dim); font: 600 10.5px/1.4 var(--sans); text-transform: uppercase;
     letter-spacing: .09em; border-top: none; }
tr:first-child td { border-top: none; }
.nowrap { white-space: nowrap; }
.mono { font-family: var(--mono); }
.o-bought { color: var(--in); font-weight: 600; }
.o-failed, .o-blocked { color: var(--alert); font-weight: 600; }
.o-declined, .o-running { color: var(--warn); }
.o-in_stock { color: var(--in); }

details { margin-top: 12px; border-top: 1px solid var(--line); padding-top: 12px; }
details > summary { cursor: pointer; color: var(--muted); font-size: 13px; list-style: none;
                    font-weight: 500; }
details > summary::-webkit-details-marker { display: none; }
details > summary::before { content: '\u25B8 '; color: var(--dim); }
details[open] > summary::before { content: '\u25BE '; }
details > summary:hover { color: var(--ink); }
.off { opacity: .5; }

.login { max-width: 350px; margin: 15vh auto; }
.login .card { padding: 26px 24px; }
.err { color: var(--alert); font-size: 13px; min-height: 20px; }
`;
function loginPage(message = "") {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Hub</title>${FONTS}<style>${STYLE}</style></head>
<body><main class="login">
  <div class="card">
    <h1>Hub</h1>
    <p class="sub" style="margin:6px 0 0">Sign in to see what's being watched.</p>
    <form method="POST" action="/login" style="margin-top:20px">
      <input type="password" name="password" placeholder="Password" autofocus required
             autocomplete="current-password">
      <div class="err" style="margin:9px 0">${esc(message)}</div>
      <button type="submit" class="primary" style="width:100%">Sign in</button>
    </form>
  </div>
</main></body></html>`;
}
function dashboardPage() {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Hub</title>${FONTS}<style>${STYLE}</style></head>
<body><main>
  <header>
    <h1>Hub</h1>
    <span class="sub" id="summary">loading\u2026</span>
  </header>

  <div class="tabs">
    <button class="tab on" data-tab="missions">Missions<span class="count" id="c-missions"></span></button>
    <button class="tab" data-tab="products">Products<span class="count" id="c-products"></span></button>
    <button class="tab" data-tab="activity">Activity<span class="count" id="c-activity"></span></button>
  </div>

  <div class="bar">
    <button id="refresh">Refresh</button>
    <label class="check sub"><input type="checkbox" id="auto" checked> auto every 30s</label>
    <span class="grow"></span>
    <a class="btn" href="/logout">Sign out</a>
  </div>

  <section id="tab-missions"><div id="missions"></div></section>

  <section id="tab-products" hidden>
    <div class="card">
      <h3>Add a product</h3>
      <p class="sub" style="margin:-4px 0 12px">
        The thing itself. Only the name is needed \u2014 everything else can wait,
        or be filled in from the page once the Watcher reads it.
      </p>
      <form class="stack" id="product-form" novalidate>
        <label class="f">Name
          <input type="text" name="name" placeholder="Pok\xE9mon TCG: Pitch Black Elite Trainer Box">
        </label>
        <div class="grid2">
          <label class="f">Release date <span class="hint">optional</span>
            <input type="date" name="releaseDate">
          </label>
          <label class="f">MSRP <span class="hint">optional \u2014 what it should cost</span>
            <input type="number" name="msrp" step="0.01" min="0.01" placeholder="49.99">
          </label>
        </div>
        <label class="f">Image URL <span class="hint">optional \u2014 filled in automatically otherwise</span>
          <input type="url" name="imageUrl" placeholder="https://\u2026">
        </label>
        <label class="f">Notes <span class="hint">optional</span>
          <textarea name="notes" placeholder="Anything you want to remember about this one."></textarea>
        </label>
        <div class="actions">
          <button type="submit" class="primary">Add product</button>
          <span class="msg" id="product-msg"></span>
        </div>
      </form>
    </div>
    <div id="products"></div>
  </section>

  <section id="tab-activity" hidden>
    <h2 style="margin-top:0">Mission runs</h2>
    <p class="sub" style="margin:-6px 0 10px">
      Written when a mission acted, or could not. Routine checks that found
      nothing are not runs \u2014 otherwise the four that matter drown in ten
      thousand that don't.
    </p>
    <div class="card" id="runs-card"></div>

    <h2>Stock and price changes</h2>
    <div class="card" id="changes-card"></div>
  </section>
</main>
<script>
const money = (n) => n === null || n === undefined ? '\u2014' : '$' + Number(n).toFixed(2);

function ago(iso) {
  if (!iso) return 'never';
  const s = Math.max(0, (Date.now() - new Date(iso).getTime()) / 1000);
  if (s < 60) return Math.round(s) + 's ago';
  if (s < 3600) return Math.round(s / 60) + 'm ago';
  if (s < 86400) return Math.round(s / 3600) + 'h ago';
  return Math.round(s / 86400) + 'd ago';
}

// Anything older than five minutes is not a live reading. Say so loudly rather
// than showing a stale price as though it were current.
const STALE_MS = 5 * 60 * 1000;

let DATA = { missions: [], runs: [], changes: [], products: [], listings: [] };
const OPEN = new Set();   // which detail panels are expanded, kept across refreshes

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
}

/**
 * Read a form.
 *
 * FormData, never form.fieldName. A form's own "name" property is its name
 * attribute, not the input called "name" \u2014 so the add-product form sent an empty
 * name on every submission and came back "a product needs a name". The only field
 * left to suspect was the date, which is why it looked required when it never was.
 */
function fields(form) {
  const out = {};
  for (const [k, v] of new FormData(form)) out[k] = typeof v === 'string' ? v.trim() : v;
  for (const input of form.querySelectorAll('input[type=checkbox]')) out[input.name] = input.checked;
  return out;
}

const num = (v) => (v === '' || v === undefined || v === null ? null : Number(v));

async function api(method, path, body) {
  const res = await fetch(path, {
    method,
    headers: body ? { 'Content-Type': 'application/json' } : {},
    body: body ? JSON.stringify(body) : undefined,
  });
  if (res.status === 401) { location.href = '/login'; throw new Error('signed out'); }
  const data = await res.json().catch(() => ({}));
  // The API answers failures in sentences. Show the sentence, not the status.
  if (!res.ok) throw new Error(data.error || (method + ' ' + path + ' failed'));
  return data;
}

function say(node, text, ok) {
  if (!node) return;
  node.textContent = text;
  node.className = 'msg ' + (ok ? 'good' : 'bad');
  if (ok) setTimeout(() => { if (node.textContent === text) node.textContent = ''; }, 4000);
}

/**
 * Run an action attached to a button.
 *
 * The button says what it is doing and cannot be pressed twice while it does
 * it. Double-submitting a mission edit is harmless; double-submitting a buy
 * would not be, and the habit should be the same in both places.
 */
async function withButton(button, busyText, msgNode, fn) {
  const original = button.textContent;
  button.disabled = true;
  button.textContent = busyText;
  try {
    const result = await fn();
    say(msgNode, result || 'saved', true);
    return true;
  } catch (err) {
    say(msgNode, err.message, false);
    return false;
  } finally {
    button.disabled = false;
    button.textContent = original;
  }
}

function thumb(url, alt, big) {
  const cls = 'thumb' + (big ? ' lg' : '');
  if (!url) {
    const ph = el('div', cls + ' ph', '\u25A6');
    ph.title = 'no image yet \u2014 the Watcher fills this in on its first read';
    return ph;
  }
  const img = el('img', cls);
  img.src = url;
  img.alt = alt || '';
  img.loading = 'lazy';
  // A dead CDN URL should degrade to the placeholder, not a broken-image icon.
  img.addEventListener('error', () => img.replaceWith(thumb('', alt, big)));
  return img;
}

function panel(key, summaryText, build) {
  const d = el('details');
  d.open = OPEN.has(key);
  d.addEventListener('toggle', () => { d.open ? OPEN.add(key) : OPEN.delete(key); });
  d.appendChild(el('summary', null, summaryText));
  d.appendChild(build());
  return d;
}

function emptyBlock(title, detail) {
  const box = el('div', 'empty');
  box.appendChild(el('strong', null, title));
  box.append(detail);
  return box;
}

/* \u2500\u2500 missions \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */

function missionCard(m) {
  const card = el('div', 'card' + (m.enabled ? '' : ' off'));
  const row = el('div', 'row');
  row.appendChild(thumb(m.imageUrl, m.productName));

  const left = el('div', 'grow');
  left.appendChild(el('div', 'name', m.productName));

  const where = el('div', 'meta');
  where.append(m.retailer + ' \xB7 ');
  where.appendChild(el('span', 'mono', m.externalId || '\u2014'));
  where.append(' \xB7 ');
  const a = el('a', null, 'open page');
  a.href = m.url; a.target = '_blank'; a.rel = 'noreferrer';
  where.appendChild(a);
  left.appendChild(where);

  const flags = el('div', 'tags');
  const label = m.state === 'in' ? 'IN STOCK'
    : m.state === 'out' ? 'out of stock'
    : m.state === 'unchecked' ? 'never checked' : m.state;
  flags.appendChild(el('span', 'pill s-' + m.state, label));

  if (!m.enabled) flags.appendChild(el('span', 'pill s-out', 'paused'));
  if (m.armed) {
    flags.appendChild(el('span', 'pill flag',
      'ARMED \xB7 ' + m.quantity + ' @ ' + money(m.ceiling)));
  } else if (m.enabled) {
    flags.appendChild(el('span', 'pill info', 'watching only'));
  }
  // The Walmart trap, made visible rather than buried in a note nobody reads.
  if (m.sellerKind === 'marketplace') {
    flags.appendChild(el('span', 'pill flag', 'marketplace: ' + (m.sellerName || 'third party')));
  }
  if (m.confidence !== 'exact' && m.state !== 'unchecked') {
    flags.appendChild(el('span', 'pill s-unknown', m.confidence + ' read'));
  }
  if (m.isPreOrder) {
    flags.appendChild(el('span', 'pill s-queue',
      'preorder' + (m.releaseDate ? ' \xB7 ' + m.releaseDate : '')));
  }
  if (m.note) {
    const note = el('div', 'meta', m.note);
    note.style.marginTop = '6px';
    left.appendChild(note);
  }

  const right = el('div', 'right');
  // Against MSRP, a price is either a restock or a scalper. Say which.
  let priceClass = 'price';
  if (m.price !== null && m.msrp !== null) {
    priceClass += m.price > m.msrp * 1.05 ? ' over' : ' under';
  }
  right.appendChild(el('div', priceClass, money(m.price)));
  if (m.msrp !== null) {
    const vs = m.price === null ? 'MSRP ' + money(m.msrp)
      : m.price > m.msrp * 1.05
        ? money(m.price - m.msrp) + ' over MSRP'
        : 'at or under MSRP';
    right.appendChild(el('div', 'meta', vs));
  }
  const stale = m.lastCheckedAt && (Date.now() - new Date(m.lastCheckedAt).getTime()) > STALE_MS;
  right.appendChild(el('div', (stale || !m.lastCheckedAt) ? 'meta stale' : 'meta',
    'checked ' + ago(m.lastCheckedAt)));
  if (m.state === 'in' && m.lastChangedAt) {
    right.appendChild(el('div', 'meta', 'in stock since ' + ago(m.lastChangedAt)));
  }
  if (m.availableQuantity !== null && m.availableQuantity !== undefined) {
    right.appendChild(el('div', 'meta', m.availableQuantity + ' available'));
  }

  row.append(left, right);
  card.appendChild(row);
  // Tags go below the whole row, full width. Nested inside the title column
  // they were competing with the price for space and wrapping at odd points.
  card.appendChild(flags);
  card.appendChild(panel('m' + m.id, 'Settings and run history', () => missionPanel(m)));
  return card;
}

function missionPanel(m) {
  const wrap = el('div');
  wrap.style.marginTop = '10px';

  const form = el('form', 'stack');
  form.dataset.mission = String(m.id);
  form.innerHTML = \`
    <div class="grid2">
      <label class="f">Price ceiling <span class="hint">per unit</span>
        <input type="number" name="ceiling" step="0.01" min="0.01" placeholder="none set">
      </label>
      <label class="f">Quantity
        <input type="number" name="quantity" min="1" max="20">
      </label>
      <label class="f">Check every
        <select name="checkEverySeconds">
          <option value="30">30 seconds</option>
          <option value="60">1 minute</option>
          <option value="300">5 minutes</option>
          <option value="1800">30 minutes</option>
          <option value="3600">1 hour</option>
        </select>
      </label>
      <label class="f">Sellers
        <select name="sellerPolicy">
          <option value="retailer_only">The retailer only</option>
          <option value="any">Any seller, under the ceiling</option>
        </select>
      </label>
    </div>
    <label class="check"><input type="checkbox" name="enabled"> Watching \u2014 check this listing on schedule</label>
    <label class="check"><input type="checkbox" name="armed"> Armed \u2014 may buy without asking me</label>
    <div class="actions">
      <button type="submit" class="primary">Save changes</button>
      <button type="button" data-act="check-now">Test run</button>
      <button type="button" class="danger" data-act="delete">Delete mission</button>
      <span class="msg"></span>
    </div>\`;

  const q = (n) => form.querySelector('[name=' + n + ']');
  q('ceiling').value = m.ceiling ?? '';
  q('quantity').value = m.quantity;
  q('checkEverySeconds').value = String(m.checkEverySeconds);
  q('sellerPolicy').value = m.sellerPolicy;
  q('enabled').checked = m.enabled;
  q('armed').checked = m.armed;
  const msg = form.querySelector('.msg');

  // Say what arming means before it is saved, not after.
  const armed = q('armed');
  const warn = el('div', 'msg');
  armed.addEventListener('change', () => {
    warn.textContent = armed.checked
      ? 'This mission will buy on its own. It needs a price ceiling.'
      : '';
    warn.className = 'msg bad';
  });
  form.insertBefore(warn, form.querySelector('.actions'));

  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    const f = fields(form);
    await withButton(e.submitter || form.querySelector('button[type=submit]'), 'Saving\u2026', msg,
      async () => {
        await api('POST', '/api/missions', {
          listingId: m.listingId,
          label: m.label,
          enabled: f.enabled,
          armed: f.armed,
          ceiling: num(f.ceiling),
          quantity: Number(f.quantity),
          sellerPolicy: f.sellerPolicy,
          checkEverySeconds: Number(f.checkEverySeconds),
        });
        load();
        return 'saved';
      });
  });

  // "Test run" \u2014 ask for this one to be checked next pass.
  //
  // The wording on the button and in the reply both say *queued*, deliberately.
  // The Hub has no browser, and the Watcher will not jump the retailer's
  // pacing for a button click, so anything promising "checking now" would be
  // making a claim neither of them can keep.
  const checkNow = form.querySelector('[data-act=check-now]');
  if (m.checkNow) checkNow.textContent = 'Test run queued';
  checkNow.addEventListener('click', async (e) => {
    const ok = await withButton(e.target, 'Queueing\u2026', msg, async () => {
      await api('POST', '/api/missions/' + m.id + '/check-now');
      return 'queued \u2014 the Watcher will check this on its next pass';
    });
    // withButton restores the label it started with, which is right for every
    // other button on this page and wrong for this one: the request outlives
    // the click, and the button is the only thing showing that.
    if (ok) e.target.textContent = 'Test run queued';
  });

  form.querySelector('[data-act=delete]').addEventListener('click', async (e) => {
    if (!confirm('Delete this mission?\\n\\nThe product and its listing stay. Run history goes.')) return;
    await withButton(e.target, 'Deleting\u2026', msg, async () => {
      await api('DELETE', '/api/missions/' + m.id);
      load();
      return 'deleted';
    });
  });

  wrap.appendChild(form);

  const runs = el('div');
  runs.style.marginTop = '12px';
  const btn = el('button', 'small', 'Load this mission\u2019s runs');
  btn.addEventListener('click', async () => {
    await withButton(btn, 'Loading\u2026', null, async () => {
      const data = await api('GET', '/api/missions/' + m.id + '/runs');
      btn.remove();
      runs.appendChild(runTable(data.runs, 'This mission has not run yet.'));
    });
  });
  runs.appendChild(btn);
  wrap.appendChild(runs);
  return wrap;
}

function runTable(runs, emptyText) {
  if (!runs.length) return el('div', 'meta', emptyText);
  const table = el('table');
  const head = el('tr');
  for (const h of ['When', 'Product', 'Outcome', 'Reason', '']) head.appendChild(el('th', null, h));
  const body = el('tbody');
  body.appendChild(head);
  for (const r of runs) {
    const tr = el('tr');
    tr.appendChild(el('td', 'meta nowrap', ago(r.startedAt)));
    tr.appendChild(el('td', null, r.productName));
    tr.appendChild(el('td', 'o-' + r.outcome + ' nowrap', r.outcome.replace('_', ' ')));
    // Every non-success carries a reason. Showing it is the point of recording it.
    tr.appendChild(el('td', 'meta', r.reason || ''));
    const right = el('td', 'meta nowrap mono',
      [r.price !== null ? money(r.price) : '', r.ms !== null ? r.ms + 'ms' : '']
        .filter(Boolean).join(' \xB7 '));
    right.style.textAlign = 'right';
    tr.appendChild(right);
    body.appendChild(tr);
  }
  table.appendChild(body);
  return table;
}

/* \u2500\u2500 products \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */

function productCard(p) {
  const card = el('div', 'card');
  const row = el('div', 'row');
  row.appendChild(thumb(p.imageUrl, p.name, true));

  const left = el('div', 'grow');
  left.appendChild(el('div', 'name', p.name));

  const facts = [];
  if (p.msrp !== null) facts.push('MSRP ' + money(p.msrp));
  facts.push(p.releaseDate ? 'releases ' + p.releaseDate : 'no release date');
  const mine = DATA.listings.filter((l) => l.productKey === p.key);
  facts.push(mine.length === 1 ? '1 listing' : mine.length + ' listings');
  left.appendChild(el('div', 'meta', facts.join(' \xB7 ')));

  if (p.notes) left.appendChild(el('div', 'meta', p.notes));

  const missions = DATA.missions.filter((m) => m.productKey === p.key);
  if (missions.length) {
    const states = el('div', 'tags');
    for (const m of missions) {
      states.appendChild(el('span', 'pill s-' + m.state, m.retailer + ': ' + m.state));
    }
    left.appendChild(states);
  }

  row.append(left);
  card.appendChild(row);
  card.appendChild(panel('p' + p.key, 'Listings and details', () => productPanel(p, mine)));
  return card;
}

function productPanel(p, listings) {
  const wrap = el('div');
  wrap.style.marginTop = '10px';

  // \u2500\u2500 where to buy it
  wrap.appendChild(el('h3', null, 'Where to buy it'));
  if (!listings.length) {
    wrap.appendChild(el('div', 'meta', 'No listings yet. Paste a product URL below.'));
  } else {
    const table = el('table');
    const body = el('tbody');
    for (const l of listings) {
      const tr = el('tr');
      tr.appendChild(el('td', 'nowrap', l.retailer));
      tr.appendChild(el('td', 'meta mono', l.externalId));
      const linkCell = el('td');
      const a = el('a', null, 'open');
      a.href = l.url; a.target = '_blank'; a.rel = 'noreferrer';
      linkCell.appendChild(a);
      tr.appendChild(linkCell);
      const seller = el('td', 'meta',
        l.sellerKind === 'marketplace' ? 'marketplace \xB7 ' + (l.sellerName || 'third party')
        : l.sellerKind === 'retailer' ? 'sold by the retailer' : 'seller unknown');
      tr.appendChild(seller);
      const actions = el('td');
      actions.style.textAlign = 'right';
      const del = el('button', 'small danger', 'remove');
      del.addEventListener('click', async () => {
        if (!confirm('Remove the ' + l.retailer + ' listing?\\n\\nIts mission and run history go with it.')) return;
        await withButton(del, 'removing\u2026', msg, async () => {
          await api('DELETE', '/api/listings/' + l.id);
          load();
          return 'removed';
        });
      });
      actions.appendChild(del);
      tr.appendChild(actions);
      body.appendChild(tr);
    }
    table.appendChild(body);
    wrap.appendChild(table);
  }

  // \u2500\u2500 add a listing
  const addForm = el('form', 'stack');
  addForm.style.marginTop = '10px';
  addForm.dataset.product = p.key;
  addForm.innerHTML = \`
    <label class="f">Add a listing
      <input type="url" name="url" placeholder="Paste a Target, Pok\xE9mon Center or Walmart product URL">
    </label>
    <div class="actions">
      <button type="submit">Add listing and watch it</button>
      <span class="sub">the retailer and SKU are read from the URL</span>
    </div>\`;
  const msg = el('span', 'msg');
  addForm.querySelector('.actions').appendChild(msg);
  addForm.addEventListener('submit', async (e) => {
    e.preventDefault();
    const f = fields(addForm);
    await withButton(addForm.querySelector('button[type=submit]'), 'Adding\u2026', msg, async () => {
      const { listing } = await api('POST', '/api/listings', { productKey: p.key, url: f.url });
      // A listing with no mission is a thing you meant to watch and didn't.
      await api('POST', '/api/missions', { listingId: listing.id, label: p.name, enabled: true });
      addForm.reset();
      load();
      return 'added ' + listing.retailer + ' ' + listing.externalId + ', now watching';
    });
  });
  wrap.appendChild(addForm);

  // \u2500\u2500 edit the product
  const edit = el('form', 'stack');
  edit.style.marginTop = '14px';
  edit.dataset.editProduct = p.key;
  edit.innerHTML = \`
    <h3 style="margin-top:6px">Details</h3>
    <label class="f">Name<input type="text" name="name"></label>
    <div class="grid2">
      <label class="f">Release date<input type="date" name="releaseDate"></label>
      <label class="f">MSRP<input type="number" name="msrp" step="0.01" min="0.01"></label>
    </div>
    <label class="f">Image URL<input type="url" name="imageUrl"></label>
    <label class="f">Notes<textarea name="notes"></textarea></label>
    <div class="actions">
      <button type="submit" class="primary">Save details</button>
      <button type="button" class="danger" data-act="delete-product">Delete product</button>
      <span class="msg"></span>
    </div>\`;
  const eq = (n) => edit.querySelector('[name=' + n + ']');
  eq('name').value = p.name;
  eq('releaseDate').value = p.releaseDate ?? '';
  eq('msrp').value = p.msrp ?? '';
  eq('imageUrl').value = p.imageUrl ?? '';
  eq('notes').value = p.notes ?? '';
  const editMsg = edit.querySelector('.msg');

  edit.addEventListener('submit', async (e) => {
    e.preventDefault();
    const f = fields(edit);
    await withButton(edit.querySelector('button[type=submit]'), 'Saving\u2026', editMsg, async () => {
      await api('POST', '/api/products', {
        key: p.key,
        name: f.name,
        releaseDate: f.releaseDate || null,
        msrp: num(f.msrp),
        imageUrl: f.imageUrl,
        notes: f.notes,
      });
      load();
      return 'saved';
    });
  });

  edit.querySelector('[data-act=delete-product]').addEventListener('click', async (e) => {
    if (!confirm('Delete "' + p.name + '"?\\n\\nEvery listing, mission and run for it goes too.')) return;
    await withButton(e.target, 'Deleting\u2026', editMsg, async () => {
      await api('DELETE', '/api/products/' + encodeURIComponent(p.key));
      load();
      return 'deleted';
    });
  });
  wrap.appendChild(edit);
  return wrap;
}

/* \u2500\u2500 rendering \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */

function render() {
  const missions = document.getElementById('missions');
  missions.textContent = '';
  if (!DATA.missions.length) {
    missions.appendChild(emptyBlock('Nothing is being watched yet.',
      'Add a product on the Products tab, paste a listing URL, and a mission is created for you.'));
  }
  for (const m of DATA.missions) missions.appendChild(missionCard(m));

  const products = document.getElementById('products');
  products.textContent = '';
  if (!DATA.products.length) {
    products.appendChild(emptyBlock('No products yet.', 'Add one with the form above.'));
  }
  for (const p of DATA.products) products.appendChild(productCard(p));

  const runsCard = document.getElementById('runs-card');
  runsCard.textContent = '';
  runsCard.appendChild(runTable(DATA.runs, 'Nothing has run yet.'));

  const changesCard = document.getElementById('changes-card');
  changesCard.textContent = '';
  if (!DATA.changes.length) {
    changesCard.appendChild(el('div', 'meta', 'Nothing has changed yet.'));
  } else {
    const table = el('table');
    const body = el('tbody');
    const head = el('tr');
    for (const h of ['When', 'Product', 'Retailer', 'Now']) head.appendChild(el('th', null, h));
    body.appendChild(head);
    for (const o of DATA.changes) {
      const tr = el('tr');
      tr.appendChild(el('td', 'meta nowrap', ago(o.at)));
      tr.appendChild(el('td', null, o.productName));
      tr.appendChild(el('td', 'meta', o.retailer));
      const td = el('td', 'nowrap');
      td.style.textAlign = 'right';
      td.append(o.state + ' \xB7 ' + money(o.price));
      tr.appendChild(td);
      body.appendChild(tr);
    }
    table.appendChild(body);
    changesCard.appendChild(table);
  }

  const inStock = DATA.missions.filter((m) => m.state === 'in').length;
  const armed = DATA.missions.filter((m) => m.armed).length;
  const never = DATA.missions.filter((m) => m.state === 'unchecked').length;
  const parts = [];
  if (inStock) parts.push(inStock + ' in stock');
  if (armed) parts.push(armed + ' armed');
  if (never) parts.push(never + ' never checked');
  document.getElementById('summary').textContent =
    parts.length ? parts.join(' \xB7 ') : 'nothing in stock';

  document.getElementById('c-missions').textContent = DATA.missions.length || '';
  document.getElementById('c-products').textContent = DATA.products.length || '';
  document.getElementById('c-activity').textContent = DATA.runs.length || '';
}

async function load() {
  try {
    DATA = await api('GET', '/api/dashboard');
  } catch (err) {
    document.getElementById('summary').textContent = err.message;
    return;
  }
  render();
}

document.getElementById('product-form').addEventListener('submit', async (e) => {
  e.preventDefault();
  const form = e.target;
  const f = fields(form);
  const msg = document.getElementById('product-msg');
  await withButton(form.querySelector('button[type=submit]'), 'Adding\u2026', msg, async () => {
    const { product } = await api('POST', '/api/products', {
      name: f.name,
      releaseDate: f.releaseDate || null,
      msrp: num(f.msrp),
      imageUrl: f.imageUrl,
      notes: f.notes,
    });
    form.reset();
    OPEN.add('p' + product.key);   // open it, so the next step is in front of you
    load();
    return 'added \u2014 now give it a listing URL below';
  });
});

for (const tab of document.querySelectorAll('.tab')) {
  tab.addEventListener('click', () => {
    for (const t of document.querySelectorAll('.tab')) t.classList.toggle('on', t === tab);
    for (const name of ['missions', 'products', 'activity']) {
      document.getElementById('tab-' + name).hidden = name !== tab.dataset.tab;
    }
  });
}

document.getElementById('refresh').addEventListener('click', (e) =>
  withButton(e.target, 'Refreshing\u2026', null, load));

let timer = setInterval(load, 30000);
document.getElementById('auto').addEventListener('change', (e) => {
  clearInterval(timer);
  if (e.target.checked) timer = setInterval(load, 30000);
});
load();
</script>
</body></html>`;
}

// src/app.ts
function json(body, status = 200) {
  return new Response(JSON.stringify(body, null, 2), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8" }
  });
}
async function publish(db2, env2, results, now) {
  for (const result of results) {
    if (!result.ok || result.fresh.length === 0) continue;
    const source = await getSource(db2, result.sourceId);
    await announce(
      env2.DISCORD_WEBHOOK_URL,
      result.label,
      source?.retailer ?? "",
      result.fresh,
      now
    );
    await markAnnounced(
      db2,
      result.sourceId,
      result.fresh.map((f) => f.externalId)
    );
  }
  const opsUrl = env2.DISCORD_OPS_WEBHOOK_URL || env2.DISCORD_WEBHOOK_URL;
  await reportOps(opsUrl, results, now);
}
function html(body, status = 200, headers = {}) {
  return new Response(body, {
    status,
    headers: { "Content-Type": "text/html; charset=utf-8", ...headers }
  });
}
function redirect(to, headers = {}) {
  return new Response(null, { status: 303, headers: { Location: to, ...headers } });
}
function createHandler(db2, env2) {
  return async function handle(request) {
    const url = new URL(request.url);
    const path = url.pathname.replace(/\/+$/, "") || "/";
    const now = (/* @__PURE__ */ new Date()).toISOString();
    if (request.method === "GET" && path === "/health") {
      const sources = await listSources(db2);
      return json({
        ok: true,
        sources: sources.map((s) => ({
          id: s.id,
          label: s.label,
          via: s.via,
          seeded: s.seeded,
          lastSweptAt: s.lastSweptAt,
          lastStatus: s.lastStatus,
          lastCount: s.lastCount
        }))
      });
    }
    const secure = url.protocol === "https:";
    if (path === "/login") {
      if (request.method === "GET") return html(loginPage());
      const form = await request.formData().catch(() => null);
      const given = String(form?.get("password") ?? "");
      if (!env2.APP_PASSWORD) {
        return html(loginPage("No password is set on this deployment."), 500);
      }
      if (!safeEqual(given, env2.APP_PASSWORD)) {
        await new Promise((r) => setTimeout(r, 400));
        return html(loginPage("That is not the password."), 401);
      }
      return redirect("/", {
        "Set-Cookie": sessionCookie(await mintSession(env2.APP_PASSWORD), secure)
      });
    }
    if (path === "/logout") {
      return redirect("/login", { "Set-Cookie": clearCookie(secure) });
    }
    const caller = await identify(request, env2);
    if (caller === "none") {
      const wantsHtml = (request.headers.get("accept") ?? "").includes("text/html");
      if (wantsHtml) return redirect("/login");
      return json({ error: "unauthorised" }, 401);
    }
    if (request.method === "GET" && (path === "/" || path === "/dashboard")) {
      return html(dashboardPage());
    }
    if (request.method === "GET" && path === "/api/dashboard") {
      const [missions, runs, changes, products, listings] = await Promise.all([
        listMissions(db2),
        recentRuns(db2, 40),
        recentObservations(db2, 40),
        listProducts(db2),
        listListings(db2)
      ]);
      return json({ missions, runs, changes, products, listings, now });
    }
    if (request.method === "GET" && path.startsWith("/api/missions/") && path.endsWith("/runs")) {
      const id = Number(path.split("/")[3]);
      if (!Number.isInteger(id)) return json({ error: "bad mission id" }, 400);
      const mission = await getMission(db2, id);
      if (!mission) return json({ error: "no such mission" }, 404);
      return json({ mission, runs: await missionRuns(db2, id, 200) });
    }
    const body = async () => await request.json().catch(() => null);
    if (request.method === "POST" && path === "/api/products") {
      const b = await body();
      if (!b) return json({ error: "body must be JSON" }, 400);
      try {
        return json({ product: await upsertProduct(db2, b) });
      } catch (err) {
        return json({ error: err.message }, 400);
      }
    }
    if (request.method === "DELETE" && path.startsWith("/api/products/")) {
      const key = decodeURIComponent(path.slice("/api/products/".length));
      if (!key) return json({ error: "no product key" }, 400);
      await deleteProduct(db2, key);
      return json({ deleted: key });
    }
    if (request.method === "POST" && path === "/api/listings") {
      const b = await body();
      if (!b?.productKey || !b?.url) return json({ error: "need a product and a URL" }, 400);
      const parsed = identifyListing(b.url);
      if (!parsed) {
        return json(
          {
            error: "could not read a retailer and product id out of that URL. Expected a target.com/p/\u2026/A-123, pokemoncenter.com/product/100-123/\u2026 or walmart.com/ip/\u2026/123 link."
          },
          400
        );
      }
      const listing = await addListing(db2, {
        productKey: b.productKey,
        retailer: parsed.retailer,
        externalId: parsed.externalId,
        url: b.url.trim()
      });
      return json({ listing });
    }
    if (request.method === "DELETE" && path.startsWith("/api/listings/")) {
      const id = Number(path.slice("/api/listings/".length));
      if (!Number.isInteger(id)) return json({ error: "bad listing id" }, 400);
      await deleteListing(db2, id);
      return json({ deleted: id });
    }
    if (request.method === "POST" && path === "/api/missions") {
      const b = await body();
      if (!b) return json({ error: "body must be JSON" }, 400);
      try {
        return json({ mission: await upsertMission(db2, b) });
      } catch (err) {
        return json({ error: err.message }, 400);
      }
    }
    if (request.method === "POST" && path.endsWith("/check-now") && path.startsWith("/api/missions/")) {
      const id = Number(path.split("/")[3]);
      if (!Number.isInteger(id)) return json({ error: "bad mission id" }, 400);
      if (!await requestCheckNow(db2, id)) return json({ error: "no such mission" }, 404);
      return json({ queued: id, note: "the Watcher will check this on its next pass" }, 202);
    }
    if (request.method === "DELETE" && path.startsWith("/api/missions/")) {
      const id = Number(path.slice("/api/missions/".length));
      if (!Number.isInteger(id)) return json({ error: "bad mission id" }, 400);
      await deleteMission(db2, id);
      return json({ deleted: id });
    }
    if (request.method === "GET" && path === "/api/missions/active") {
      return json({ missions: await activeMissions(db2) });
    }
    if (request.method === "POST" && path === "/api/runs") {
      const b = await body();
      if (!b?.missionId || !b?.outcome || b.outcome === "running") {
        return json({ error: "need missionId and a settled outcome" }, 400);
      }
      const id = await recordRun(db2, b.missionId, {
        outcome: b.outcome,
        reason: b.reason,
        state: b.state,
        price: b.price,
        sellerKind: b.sellerKind,
        sellerName: b.sellerName,
        quantity: b.quantity,
        total: b.total
      });
      return json({ run: id });
    }
    if (request.method === "POST" && path === "/observations") {
      let body2;
      try {
        body2 = await request.json();
      } catch {
        return json({ error: "body must be JSON" }, 400);
      }
      if (!Array.isArray(body2.observations)) {
        return json({ error: "need observations[]" }, 400);
      }
      const results = [];
      const changes = [];
      for (const obs of body2.observations) {
        if (!obs?.listingId || !obs?.state) {
          results.push({
            listingId: obs?.listingId ?? 0,
            changed: false,
            error: "need listingId and state"
          });
          continue;
        }
        try {
          const outcome = await recordObservation(db2, obs);
          results.push({ listingId: obs.listingId, changed: outcome.changed });
          if (outcome.changed) changes.push({ obs, was: outcome.previousState });
        } catch (err) {
          results.push({ listingId: obs.listingId, changed: false, error: err.message });
        }
      }
      const cameIntoStock = changes.filter((c) => c.obs.state === "in" && c.was !== "in");
      if (cameIntoStock.length > 0 && env2.DISCORD_WEBHOOK_URL) {
        await announce(
          env2.DISCORD_WEBHOOK_URL,
          "In stock",
          "",
          cameIntoStock.map((c) => ({
            externalId: String(c.obs.listingId),
            name: c.obs.note || `listing ${c.obs.listingId}`,
            url: "",
            price: c.obs.price ?? null
          })),
          now
        );
      }
      return json({
        recorded: results.length,
        changed: results.filter((r) => r.changed).length,
        failed: results.filter((r) => r.error).length,
        results
      });
    }
    if (request.method === "POST" && path === "/sweep") {
      const only = url.searchParams.get("source");
      let results;
      if (only) {
        const source = await getSource(db2, only);
        if (!source) return json({ error: `no source "${only}"` }, 404);
        results = [await sweepSource(db2, source)];
      } else {
        results = await sweepAll(db2);
      }
      await publish(db2, env2, results, now);
      return json({
        swept: results.map((r) => ({
          source: r.sourceId,
          ok: r.ok,
          seen: r.seen,
          new: r.fresh.length,
          error: r.error
        }))
      });
    }
    if (request.method === "POST" && path === "/ingest") {
      let body2;
      try {
        body2 = await request.json();
      } catch {
        return json({ error: "body must be JSON" }, 400);
      }
      const sourceId = (body2.sourceId ?? "").trim();
      if (!sourceId || !Array.isArray(body2.items)) {
        return json({ error: "need sourceId and items[]" }, 400);
      }
      const source = await getSource(db2, sourceId);
      if (!source) return json({ error: `no source "${sourceId}"` }, 404);
      const config = source.config;
      const clean = dedupe(
        applyFilters(
          body2.items.filter((i) => i && typeof i.externalId === "string" && i.externalId),
          config.filters
        )
      );
      const known = await knownIds(db2, sourceId);
      const fresh = clean.filter((i) => !known.has(i.externalId));
      const isFirstSweep = !source.seeded;
      const toAnnounce = await recordDiscoveries(db2, sourceId, fresh, !isFirstSweep);
      for (const item of toAnnounce) {
        await attachIdentity(db2, sourceId, source.retailer, item);
      }
      await finishSweep(
        db2,
        sourceId,
        isFirstSweep ? `seeded ${fresh.length} via watcher` : `watcher: ${fresh.length} new`,
        clean.length,
        true
      );
      if (toAnnounce.length > 0) {
        await announce(env2.DISCORD_WEBHOOK_URL, source.label, source.retailer, toAnnounce, now);
        await markAnnounced(
          db2,
          sourceId,
          toAnnounce.map((f) => f.externalId)
        );
      }
      return json({
        received: clean.length,
        new: fresh.length,
        announced: toAnnounce.length,
        seeded: isFirstSweep
      });
    }
    if ((request.method === "POST" || request.method === "GET") && path === "/probe") {
      const sources = await listAllSources(db2);
      const checks = [];
      for (const source of sources) {
        if (source.via === "watcher" || !source.url) {
          checks.push({
            id: source.id,
            retailer: source.retailer,
            via: source.via,
            enabled: source.enabled,
            verdict: "watcher \u2014 never fetched from here"
          });
          continue;
        }
        const config = source.config;
        const result = await probeUrl(source.url, config.headers ?? {});
        checks.push({
          id: source.id,
          retailer: source.retailer,
          via: source.via,
          enabled: source.enabled,
          status: result.status,
          ms: result.ms,
          verdict: result.ok ? `reachable \u2014 ${result.note}` : result.blocked ? `BLOCKED (${result.status}) \u2014 move this source to via='watcher'` : `failed (${result.status}) \u2014 ${result.note}`
        });
      }
      const blocked = checks.filter((c) => String(c.verdict).startsWith("BLOCKED")).length;
      return json({
        summary: blocked === 0 ? "every hub source is reachable from here" : `${blocked} source(s) blocked \u2014 those belong to the Watcher`,
        checks
      });
    }
    if (request.method === "GET" && path === "/watchlist") {
      const [products, sources] = await Promise.all([
        watchlist(db2),
        listSources(db2, "watcher")
      ]);
      return json({
        products,
        sources: sources.map((s) => ({
          id: s.id,
          label: s.label,
          retailer: s.retailer,
          url: s.url,
          config: s.config
        }))
      });
    }
    return json({ error: "not found" }, 404);
  };
}

// src/db.ts
function fromPostgres(client) {
  return {
    async query(text, params = []) {
      const rows = await client.unsafe(text, params);
      return rows;
    },
    async batch(statements) {
      if (statements.length === 0) return;
      await client.begin(async (tx) => {
        for (const s of statements) await tx.unsafe(s.text, s.params ?? []);
      });
    },
    async exec(script) {
      await client.unsafe(script);
    }
  };
}
function connectionStringFrom(env2) {
  const url = env2.DATABASE_URL ?? env2.POSTGRES_URL ?? "";
  if (!url) {
    throw new Error(
      'DATABASE_URL is not set.\n  Supabase dashboard \u2192 the "Connect" button at the top \u2192 Shared pooler,\n  transaction mode. Put it in .env.local for local work, and in the Vercel\n  project settings for deploys.'
    );
  }
  if (!/^postgres(ql)?:\/\//.test(url)) {
    throw new Error("DATABASE_URL does not look like a Postgres connection string.");
  }
  const host = /@([^/:?]+)/.exec(url)?.[1] ?? "";
  if (/^db\.[a-z0-9-]+\.supabase\.co$/i.test(host)) {
    const port = /:(\d+)\//.exec(url)?.[1] ?? "";
    const which = port === "6543" ? "the dedicated pooler" : "the direct connection";
    throw new Error(
      `That is ${which} (${host}), which is IPv6-only unless you pay for the
  IPv4 add-on \u2014 and Vercel is IPv4, so it would fail on every deploy.
  Use the SHARED pooler instead: its host contains "pooler.supabase.com"
  and the username has the project ref on it (postgres.<ref>).
  Supabase dashboard \u2192 "Connect" \u2192 Shared pooler \u2192 Transaction mode.`
    );
  }
  return url;
}

// src/deadline.ts
async function withDeadline(work, opts) {
  const setTimer = opts.setTimer ?? setTimeout;
  const clearTimer = opts.clearTimer ?? clearTimeout;
  let timer;
  let firedLate = false;
  const late = new Promise((resolve) => {
    timer = setTimer(() => {
      firedLate = true;
      opts.onTimeout?.();
      resolve(opts.late());
    }, opts.ms);
  });
  try {
    return await Promise.race([work, late]);
  } finally {
    if (!firedLate) clearTimer(timer);
    void work.catch(() => {
    });
  }
}

// src/server.ts
var cached = null;
var cachedClient = null;
function db() {
  if (cached) return cached;
  const client = postgres(connectionStringFrom(process.env), {
    // The pooler does not support prepared statements.
    prepare: false,
    max: 1,
    idle_timeout: 20,
    connect_timeout: 10,
    // A query that cannot finish in eight seconds is not going to finish. Let
    // Postgres kill it rather than letting it sit on the one connection this
    // instance has.
    connection: { statement_timeout: 8e3 }
  });
  cachedClient = client;
  cached = fromPostgres(client);
  return cached;
}
function dropConnection() {
  const client = cachedClient;
  cached = null;
  cachedClient = null;
  void client?.end({ timeout: 0 }).catch(() => {
  });
}
var ANSWER_WITHIN_MS = 12e3;
function tooSlow() {
  return new Response(
    JSON.stringify(
      {
        error: `the Hub could not answer within ${ANSWER_WITHIN_MS / 1e3}s \u2014 the database connection was reset, try again`
      },
      null,
      2
    ),
    { status: 503, headers: { "Content-Type": "application/json; charset=utf-8" } }
  );
}
function env() {
  return {
    DATABASE_URL: process.env.DATABASE_URL ?? "",
    DISCORD_WEBHOOK_URL: process.env.DISCORD_WEBHOOK_URL ?? "",
    DISCORD_OPS_WEBHOOK_URL: process.env.DISCORD_OPS_WEBHOOK_URL,
    INGEST_TOKEN: process.env.INGEST_TOKEN,
    APP_PASSWORD: process.env.APP_PASSWORD
  };
}
async function readBody(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}
async function handler(req, res) {
  const host = req.headers.host ?? "localhost";
  const proto = req.headers["x-forwarded-proto"] ?? "https";
  const url = new URL(req.url ?? "/", `${proto}://${host}`);
  const method = req.method ?? "GET";
  const hasBody = method !== "GET" && method !== "HEAD";
  const request = new Request(url, {
    method,
    headers: Object.entries(req.headers).flatMap(
      ([k, v]) => typeof v === "string" ? [[k, v]] : []
    ),
    ...hasBody ? { body: await readBody(req) } : {}
  });
  let response;
  try {
    response = await withDeadline(createHandler(db(), env())(request), {
      ms: ANSWER_WITHIN_MS,
      onTimeout: dropConnection,
      late: tooSlow
    });
  } catch (err) {
    dropConnection();
    response = new Response(
      JSON.stringify({ error: err.message }, null, 2),
      { status: 500, headers: { "Content-Type": "application/json; charset=utf-8" } }
    );
  }
  res.statusCode = response.status;
  response.headers.forEach((value, key) => res.setHeader(key, value));
  res.end(Buffer.from(await response.arrayBuffer()));
}
export {
  handler as default
};
