// Generated by `npm run bundle` from src/server.ts. Do not edit.

// src/server.ts
import postgres from "postgres";

// src/fetcher.ts
var UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
var FetchError = class extends Error {
  status;
  blocked;
  constructor(message, status, blocked) {
    super(message);
    this.name = "FetchError";
    this.status = status;
    this.blocked = blocked;
  }
};
function looksGzipped(url, contentType) {
  if (/\.gz(\?|$)/i.test(url)) return true;
  return /application\/(x-)?gzip/i.test(contentType ?? "");
}
async function gunzip(res) {
  if (!res.body) return "";
  const stream = res.body.pipeThrough(new DecompressionStream("gzip"));
  return new Response(stream).text();
}
async function fetchText(url, headers = {}, timeoutMs = 2e4) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": UA, Accept: "*/*", ...headers },
      signal: controller.signal,
      redirect: "follow"
    });
    if (!res.ok) {
      const blocked = res.status === 403 || res.status === 429 || res.status === 503;
      throw new FetchError(
        `${res.status} ${res.statusText || ""}`.trim() + (blocked ? " \u2014 looks like a block; this source needs the Watcher" : ""),
        res.status,
        blocked
      );
    }
    return looksGzipped(url, res.headers.get("content-type")) ? await gunzip(res) : await res.text();
  } catch (err) {
    if (err instanceof FetchError) throw err;
    const msg = err instanceof Error ? err.message : String(err);
    throw new FetchError(msg, 0, false);
  } finally {
    clearTimeout(timer);
  }
}
async function probeUrl(url, headers = {}) {
  const started = Date.now();
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": UA, Accept: "*/*", ...headers },
      redirect: "follow"
    });
    const blocked = res.status === 403 || res.status === 429 || res.status === 503;
    let note = "";
    if (res.ok && res.body) {
      const reader = res.body.getReader();
      const { value } = await reader.read();
      await reader.cancel().catch(() => {
      });
      const bytes = value?.length ?? 0;
      const head = new TextDecoder().decode((value ?? new Uint8Array()).slice(0, 200));
      note = /^\x1f\x8b/.test(head) || /gzip/i.test(res.headers.get("content-type") ?? "") ? `gzipped, ${bytes}B read` : /<sitemapindex/i.test(head) ? "sitemap index" : /<urlset/i.test(head) ? "sitemap" : `${bytes}B read`;
    } else if (blocked) {
      note = "blocked \u2014 this source needs the Watcher";
    } else if (!res.ok) {
      note = res.statusText || "not ok";
    }
    return { url, ok: res.ok, status: res.status, blocked, ms: Date.now() - started, note };
  } catch (err) {
    return {
      url,
      ok: false,
      status: 0,
      blocked: false,
      ms: Date.now() - started,
      note: err instanceof Error ? err.message : String(err)
    };
  }
}

// src/parsers/sitemap.ts
var LOC_RE = /<loc>([\s\S]*?)<\/loc>/gi;
var CDATA_RE = /^\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*$/;
var ENTITIES = {
  "&amp;": "&",
  "&lt;": "<",
  "&gt;": ">",
  "&quot;": '"',
  "&apos;": "'",
  "&#39;": "'"
};
function decodeEntities(s) {
  return s.replace(/&(?:amp|lt|gt|quot|apos|#39);/g, (m) => ENTITIES[m] ?? m);
}
function sitemapKind(xml) {
  const head = xml.slice(0, 4e3);
  if (/<sitemapindex[\s>]/i.test(head)) return "index";
  if (/<urlset[\s>]/i.test(head)) return "urlset";
  return "unknown";
}
function extractLocs(xml) {
  const out = [];
  LOC_RE.lastIndex = 0;
  let m;
  while ((m = LOC_RE.exec(xml)) !== null) {
    let raw = m[1] ?? "";
    const cdata = CDATA_RE.exec(raw);
    if (cdata) raw = cdata[1] ?? "";
    const value = decodeEntities(raw.trim());
    if (value) out.push(value);
  }
  return out;
}

// src/parsers/jsonList.ts
function pluck(obj, path) {
  if (!path) return obj;
  let cur = obj;
  for (const rawPart of path.split(".")) {
    const part = rawPart.trim();
    if (!part) continue;
    const idx = /^\[(\d+)\]$/.exec(part);
    if (idx) {
      if (!Array.isArray(cur)) return void 0;
      cur = cur[Number(idx[1])];
      continue;
    }
    if (cur === null || typeof cur !== "object") return void 0;
    cur = cur[part];
  }
  return cur;
}
function str(v) {
  if (v === null || v === void 0) return "";
  if (typeof v === "string") return v;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return "";
}
function num(v) {
  if (typeof v === "number" && Number.isFinite(v)) return v;
  if (typeof v === "string") {
    const n = Number(v.replace(/[^0-9.]/g, ""));
    return Number.isFinite(n) ? n : null;
  }
  return null;
}
function parseJsonList(payload, config) {
  const raw = pluck(payload, config.itemsPath ?? "");
  if (!Array.isArray(raw)) return [];
  const idField = config.idField ?? "id";
  const nameField = config.nameField ?? "title";
  const urlField = config.urlField ?? "url";
  const out = [];
  for (const item of raw) {
    if (item === null || typeof item !== "object") continue;
    const externalId = str(pluck(item, idField)).trim();
    if (!externalId) continue;
    out.push({
      externalId,
      name: str(pluck(item, nameField)).trim() || externalId,
      url: str(pluck(item, urlField)).trim(),
      price: config.priceField ? num(pluck(item, config.priceField)) : null
    });
  }
  return out;
}

// src/parsers/identify.ts
var TARGET_TCIN = /\/-\/A-(\w+)/i;
var PC_PRODUCT = /\/product\/([^/?#]+)/i;
var WALMART_IP = /\/ip\/(?:([^/?#]+)\/)?(\d{5,})/i;
function titleise(slug) {
  const cleaned = slug.replace(/[-_+]+/g, " ").replace(/\.(html?|aspx)$/i, "").replace(/\s+/g, " ").trim();
  if (!cleaned) return "";
  return cleaned.split(" ").map((w) => w.length > 2 ? w[0].toUpperCase() + w.slice(1) : w).join(" ");
}
function lastSegment(pathname) {
  const parts = pathname.split("/").filter(Boolean);
  return parts.length ? parts[parts.length - 1] : "";
}
function fromUrl(rawUrl, retailer) {
  let u;
  try {
    u = new URL(rawUrl);
  } catch {
    return null;
  }
  const path = u.pathname;
  const tcin = TARGET_TCIN.exec(path);
  if (tcin) {
    const slug = path.split("/-/")[0]?.replace(/^\/p\//, "") ?? "";
    return {
      externalId: tcin[1],
      name: titleise(slug) || tcin[1],
      url: `${u.origin}${path}`
    };
  }
  const wm = WALMART_IP.exec(path);
  if (wm) {
    const slug = wm[1] ?? "";
    const itemId = wm[2];
    return {
      externalId: itemId,
      name: titleise(slug) || itemId,
      url: `${u.origin}${path}`
    };
  }
  const pc = PC_PRODUCT.exec(path);
  if (pc) {
    const id = pc[1];
    const rest = path.slice(pc.index + pc[0].length).replace(/^\//, "");
    return {
      externalId: id,
      name: titleise(rest) || titleise(id),
      url: `${u.origin}${path}`
    };
  }
  const seg = lastSegment(path);
  if (!seg || seg.length < 3) return null;
  return {
    externalId: `${retailer}:${seg}`.toLowerCase(),
    name: titleise(seg),
    url: `${u.origin}${path}`
  };
}
function productKey(name, fallback) {
  const base = (name || fallback).toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 48);
  return `prd_${base || "unknown"}`;
}
var HOSTS = [
  { match: /(^|\.)target\.com$/i, product: /\/p\/(?:[^?#]*\/)?-\/A-\w+/i, retailer: "Target" },
  {
    match: /(^|\.)pokemoncenter\.com$/i,
    product: /\/product\/[^/?#]+/i,
    retailer: "Pokemon Center"
  },
  { match: /(^|\.)walmart\.com$/i, product: /\/ip\/(?:[^/?#]+\/)?\d{5,}/i, retailer: "Walmart" }
];
function identifyListing(rawUrl) {
  let u;
  try {
    u = new URL(rawUrl.trim());
  } catch {
    return null;
  }
  if (u.protocol !== "https:" && u.protocol !== "http:") return null;
  const host = HOSTS.find((h) => h.match.test(u.hostname));
  if (!host) return null;
  if (!host.product.test(u.pathname)) return null;
  const found = fromUrl(u.toString(), host.retailer);
  if (!found?.externalId) return null;
  return {
    retailer: host.retailer,
    externalId: found.externalId,
    name: found.name,
    url: found.url || u.toString()
  };
}

// src/filter.ts
function fold(s) {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
}
function matches(item, filters) {
  if (!filters || filters.length === 0) return true;
  const hay = fold(`${item.name} ${item.url}`);
  return filters.some((f) => {
    const needle = fold(f).trim();
    return needle.length > 0 && hay.includes(needle);
  });
}
function applyFilters(items, filters) {
  if (!filters || filters.length === 0) return items;
  return items.filter((i) => matches(i, filters));
}
function dedupe(items) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const item of items) {
    if (!item.externalId || seen.has(item.externalId)) continue;
    seen.add(item.externalId);
    out.push(item);
  }
  return out;
}

// src/store.ts
function toPrice(v) {
  if (v === null || v === void 0 || v === "") return null;
  const n = typeof v === "number" ? v : Number(v);
  return Number.isFinite(n) && n > 0 ? n : null;
}
function toConfig(v) {
  if (v && typeof v === "object") return v;
  try {
    return JSON.parse(String(v || "{}"));
  } catch {
    return {};
  }
}
function toSource(row) {
  return {
    id: String(row.id),
    label: String(row.label ?? ""),
    retailer: String(row.retailer ?? ""),
    kind: row.kind,
    url: String(row.url ?? ""),
    via: row.via,
    config: toConfig(row.config),
    enabled: row.enabled === true,
    seeded: row.seeded === true,
    cursor: Number(row.cursor ?? 0),
    lastSweptAt: row.last_swept_at ? String(row.last_swept_at) : null,
    lastStatus: String(row.last_status ?? ""),
    lastCount: Number(row.last_count ?? 0)
  };
}
async function listSources(db2, via) {
  const rows = via ? await db2.query("SELECT * FROM sources WHERE enabled = true AND via = $1 ORDER BY id", [via]) : await db2.query("SELECT * FROM sources WHERE enabled = true ORDER BY id");
  return rows.map(toSource);
}
async function listAllSources(db2) {
  const rows = await db2.query("SELECT * FROM sources ORDER BY retailer, id");
  return rows.map(toSource);
}
async function getSource(db2, id) {
  const rows = await db2.query("SELECT * FROM sources WHERE id = $1", [id]);
  return rows[0] ? toSource(rows[0]) : null;
}
async function knownIds(db2, sourceId) {
  const rows = await db2.query(
    "SELECT external_id FROM discoveries WHERE source_id = $1",
    [sourceId]
  );
  return new Set(rows.map((r) => r.external_id));
}
async function recordDiscoveries(db2, sourceId, items, announce2) {
  if (items.length === 0) return [];
  const statements = items.map((item) => ({
    text: `INSERT INTO discoveries (source_id, external_id, url, name, price, announced)
           VALUES ($1, $2, $3, $4, $5, $6)
           ON CONFLICT (source_id, external_id) DO NOTHING`,
    params: [sourceId, item.externalId, item.url, item.name, item.price ?? null, !announce2]
  }));
  await db2.batch(statements);
  return announce2 ? items : [];
}
async function markAnnounced(db2, sourceId, externalIds) {
  if (externalIds.length === 0) return;
  await db2.query(
    "UPDATE discoveries SET announced = true WHERE source_id = $1 AND external_id = ANY($2)",
    [sourceId, externalIds]
  );
}
async function attachIdentity(db2, sourceId, retailer, item) {
  const existing = await db2.query(
    "SELECT product_key FROM aliases WHERE kind = $1 AND retailer = $2 AND value = $3",
    ["retailer_sku", retailer, item.externalId]
  );
  if (existing[0]?.product_key) return existing[0].product_key;
  const key = productKey(item.name, item.externalId);
  await db2.batch([
    {
      text: "INSERT INTO products (key, name) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING",
      params: [key, item.name]
    },
    {
      text: `INSERT INTO aliases (product_key, kind, retailer, value) VALUES ($1, $2, $3, $4)
             ON CONFLICT (kind, retailer, value) DO NOTHING`,
      params: [key, "retailer_sku", retailer, item.externalId]
    },
    {
      text: "UPDATE discoveries SET product_key = $1 WHERE source_id = $2 AND external_id = $3",
      params: [key, sourceId, item.externalId]
    }
  ]);
  return key;
}
async function finishSweep(db2, sourceId, status, count, seeded, cursor = 0) {
  await db2.query(
    `UPDATE sources
        SET last_swept_at = now(), last_status = $1, last_count = $2,
            seeded = $3, cursor = $4
      WHERE id = $5`,
    [status.slice(0, 300), count, seeded, cursor, sourceId]
  );
}
async function logEvent(db2, kind, message, data = null) {
  await db2.query("INSERT INTO events (kind, message, data) VALUES ($1, $2, $3)", [
    kind,
    message.slice(0, 1e3),
    data === null || data === void 0 ? null : JSON.stringify(data).slice(0, 4e3)
  ]);
}
async function watchlist(db2) {
  const rows = await db2.query(
    `SELECT l.id, l.product_key, p.name, p.release_date, l.retailer, l.external_id, l.url
       FROM listings l
       JOIN products p ON p.key = l.product_key
      ORDER BY p.name, l.retailer`
  );
  return rows.map((r) => ({
    listingId: Number(r.id),
    productKey: String(r.product_key),
    name: String(r.name ?? ""),
    retailer: String(r.retailer ?? ""),
    externalId: String(r.external_id ?? ""),
    url: String(r.url ?? ""),
    releaseDate: r.release_date ? String(r.release_date).slice(0, 10) : null
  }));
}
function toProduct(r) {
  return {
    key: String(r.key),
    name: String(r.name ?? ""),
    releaseDate: r.release_date ? String(r.release_date).slice(0, 10) : null,
    imageUrl: String(r.image_url ?? ""),
    notes: String(r.notes ?? "")
  };
}
function keyForName(name) {
  const slug = name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 60);
  return `prd_${slug || "unnamed"}`;
}
async function listProducts(db2) {
  const rows = await db2.query("SELECT * FROM products ORDER BY name");
  return rows.map(toProduct);
}
async function upsertProduct(db2, p) {
  const key = p.key?.trim() || keyForName(p.name);
  const rows = await db2.query(
    `INSERT INTO products (key, name, release_date, image_url, notes)
     VALUES ($1, $2, $3, $4, $5)
     ON CONFLICT (key) DO UPDATE SET
       name = EXCLUDED.name,
       -- COALESCE, not EXCLUDED: an edit that omits a field must not blank a
       -- value someone already took the trouble to set.
       release_date = COALESCE(EXCLUDED.release_date, products.release_date),
       image_url = CASE WHEN EXCLUDED.image_url = '' THEN products.image_url ELSE EXCLUDED.image_url END,
       notes = CASE WHEN EXCLUDED.notes = '' THEN products.notes ELSE EXCLUDED.notes END
     RETURNING *`,
    [key, p.name.trim(), p.releaseDate || null, p.imageUrl ?? "", p.notes ?? ""]
  );
  return toProduct(rows[0]);
}
async function deleteProduct(db2, key) {
  await db2.query("DELETE FROM products WHERE key = $1", [key]);
}
function toListing(r) {
  return {
    id: Number(r.id),
    productKey: String(r.product_key),
    productName: String(r.product_name ?? ""),
    retailer: String(r.retailer ?? ""),
    externalId: String(r.external_id ?? ""),
    url: String(r.url ?? ""),
    sellerKind: String(r.seller_kind ?? "unknown"),
    sellerName: String(r.seller_name ?? ""),
    isPrimary: r.is_primary === true
  };
}
async function listListings(db2, productKey2) {
  const sql = `SELECT l.*, p.name AS product_name FROM listings l
                 JOIN products p ON p.key = l.product_key
                ${productKey2 ? "WHERE l.product_key = $1" : ""}
                ORDER BY p.name, l.retailer`;
  const rows = productKey2 ? await db2.query(sql, [productKey2]) : await db2.query(sql);
  return rows.map(toListing);
}
async function addListing(db2, l) {
  const rows = await db2.query(
    `INSERT INTO listings (product_key, retailer, external_id, url)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (retailer, external_id) DO UPDATE SET
       url = EXCLUDED.url,
       product_key = EXCLUDED.product_key
     RETURNING *`,
    [l.productKey, l.retailer.trim(), l.externalId.trim(), l.url.trim()]
  );
  const [full] = await db2.query(
    "SELECT l.*, p.name AS product_name FROM listings l JOIN products p ON p.key = l.product_key WHERE l.id = $1",
    [rows[0].id]
  );
  return toListing(full);
}
async function deleteListing(db2, id) {
  await db2.query("DELETE FROM listings WHERE id = $1", [id]);
}
function toMission(r) {
  const iso = (v) => v ? new Date(String(v)).toISOString() : "";
  return {
    id: Number(r.id),
    listingId: Number(r.listing_id),
    productKey: String(r.product_key ?? ""),
    productName: String(r.product_name ?? ""),
    imageUrl: String(r.image_url ?? ""),
    retailer: String(r.retailer ?? ""),
    externalId: String(r.external_id ?? ""),
    url: String(r.url ?? ""),
    label: String(r.label ?? ""),
    enabled: r.enabled === true,
    armed: r.armed === true,
    ceiling: toPrice(r.ceiling),
    quantity: Number(r.quantity ?? 1),
    sellerPolicy: String(r.seller_policy ?? "retailer_only"),
    checkEverySeconds: Number(r.check_every_s ?? 60),
    notes: String(r.notes ?? ""),
    state: String(r.state ?? "unchecked"),
    confidence: String(r.confidence ?? "unknown"),
    price: toPrice(r.price),
    sellerKind: String(r.ws_seller_kind ?? r.seller_kind ?? "unknown"),
    sellerName: String(r.ws_seller_name ?? r.seller_name ?? ""),
    availableQuantity: r.available_quantity === null || r.available_quantity === void 0 ? null : Number(r.available_quantity),
    orderLimit: r.order_limit === null || r.order_limit === void 0 ? null : Number(r.order_limit),
    isPreOrder: r.is_preorder === true,
    releaseDate: r.release_date ? String(r.release_date).slice(0, 10) : null,
    note: String(r.note ?? ""),
    lastCheckedAt: iso(r.last_checked_at),
    lastChangedAt: iso(r.last_changed_at)
  };
}
var MISSION_SELECT = `
  SELECT m.*, l.product_key, l.retailer, l.external_id, l.url,
         p.name AS product_name, p.image_url,
         COALESCE(w.state, 'unchecked') AS state,
         COALESCE(w.confidence, 'unknown') AS confidence,
         w.price,
         COALESCE(w.seller_kind, l.seller_kind) AS ws_seller_kind,
         COALESCE(NULLIF(w.seller_name, ''), l.seller_name) AS ws_seller_name,
         w.available_quantity, w.order_limit,
         COALESCE(w.is_preorder, false) AS is_preorder,
         COALESCE(w.release_date, p.release_date) AS release_date,
         COALESCE(w.note, '') AS note,
         w.last_checked_at, w.last_changed_at
    FROM missions m
    JOIN listings l ON l.id = m.listing_id
    JOIN products p ON p.key = l.product_key
    LEFT JOIN watch_state w ON w.listing_id = l.id`;
async function listMissions(db2) {
  const rows = await db2.query(`${MISSION_SELECT}
    ORDER BY
      CASE COALESCE(w.state, 'unchecked')
        WHEN 'in' THEN 0 WHEN 'queue' THEN 1 WHEN 'unknown' THEN 2
        WHEN 'unchecked' THEN 3 ELSE 4 END,
      m.armed DESC, p.name, l.retailer`);
  return rows.map(toMission);
}
async function getMission(db2, id) {
  const rows = await db2.query(`${MISSION_SELECT} WHERE m.id = $1`, [id]);
  return rows[0] ? toMission(rows[0]) : null;
}
async function activeMissions(db2) {
  const rows = await db2.query(`${MISSION_SELECT} WHERE m.enabled = true ORDER BY m.id`);
  return rows.map(toMission);
}
function validateMission(m) {
  if (!Number.isFinite(m.listingId) || m.listingId <= 0) return "a mission needs a listing";
  const quantity = m.quantity ?? 1;
  if (!Number.isInteger(quantity) || quantity < 1 || quantity > 20) {
    return "quantity must be a whole number between 1 and 20";
  }
  if (m.ceiling !== void 0 && m.ceiling !== null && !(m.ceiling > 0)) {
    return "a price ceiling must be greater than zero";
  }
  if (m.armed && (m.ceiling === void 0 || m.ceiling === null)) {
    return "set a price ceiling before arming \u2014 armed with no ceiling is an open cheque";
  }
  if (m.sellerPolicy && !["retailer_only", "any"].includes(m.sellerPolicy)) {
    return "seller policy must be retailer_only or any";
  }
  const every = m.checkEverySeconds ?? 60;
  if (!Number.isInteger(every) || every < 30 || every > 86400) {
    return "check interval must be between 30 seconds and a day";
  }
  return null;
}
async function upsertMission(db2, m) {
  const problem = validateMission(m);
  if (problem) throw new Error(problem);
  const rows = await db2.query(
    `INSERT INTO missions (listing_id, label, enabled, armed, ceiling, quantity,
                           seller_policy, check_every_s, notes)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
     ON CONFLICT (listing_id) DO UPDATE SET
       label = EXCLUDED.label,
       enabled = EXCLUDED.enabled,
       armed = EXCLUDED.armed,
       ceiling = EXCLUDED.ceiling,
       quantity = EXCLUDED.quantity,
       seller_policy = EXCLUDED.seller_policy,
       check_every_s = EXCLUDED.check_every_s,
       notes = EXCLUDED.notes
     RETURNING id`,
    [
      m.listingId,
      m.label ?? "",
      m.enabled ?? true,
      m.armed ?? false,
      m.ceiling ?? null,
      m.quantity ?? 1,
      m.sellerPolicy ?? "retailer_only",
      m.checkEverySeconds ?? 60,
      m.notes ?? ""
    ]
  );
  const mission = await getMission(db2, Number(rows[0].id));
  if (!mission) throw new Error("mission vanished immediately after being written");
  return mission;
}
async function deleteMission(db2, id) {
  await db2.query("DELETE FROM missions WHERE id = $1", [id]);
}
async function startRun(db2, missionId) {
  const rows = await db2.query("INSERT INTO mission_runs (mission_id) VALUES ($1) RETURNING id", [
    missionId
  ]);
  return Number(rows[0].id);
}
async function finishRun(db2, runId, r) {
  const needsReason = r.outcome !== "bought" && r.outcome !== "in_stock";
  const reason = (r.reason ?? "").trim() || (needsReason ? `${r.outcome}, no reason recorded` : "");
  await db2.query(
    `UPDATE mission_runs
        SET finished_at = now(),
            outcome = $1, reason = $2, state = $3, price = $4,
            seller_kind = $5, seller_name = $6, quantity = $7, total = $8,
            ms = GREATEST(0, EXTRACT(EPOCH FROM (now() - started_at)) * 1000)::int
      WHERE id = $9`,
    [
      r.outcome,
      reason.slice(0, 500),
      r.state ?? "",
      r.price ?? null,
      r.sellerKind ?? "",
      r.sellerName ?? "",
      r.quantity ?? null,
      r.total ?? null,
      runId
    ]
  );
}
async function recordRun(db2, missionId, r) {
  const id = await startRun(db2, missionId);
  await finishRun(db2, id, r);
  return id;
}
function toRun(r) {
  const iso = (v) => v ? new Date(String(v)).toISOString() : "";
  return {
    id: Number(r.id),
    missionId: Number(r.mission_id),
    productName: String(r.product_name ?? ""),
    retailer: String(r.retailer ?? ""),
    startedAt: iso(r.started_at),
    finishedAt: iso(r.finished_at),
    outcome: String(r.outcome ?? "running"),
    reason: String(r.reason ?? ""),
    state: String(r.state ?? ""),
    price: toPrice(r.price),
    sellerKind: String(r.seller_kind ?? ""),
    sellerName: String(r.seller_name ?? ""),
    quantity: r.quantity === null || r.quantity === void 0 ? null : Number(r.quantity),
    total: toPrice(r.total),
    ms: r.ms === null || r.ms === void 0 ? null : Number(r.ms)
  };
}
var RUN_SELECT = `
  SELECT r.*, p.name AS product_name, l.retailer
    FROM mission_runs r
    JOIN missions m ON m.id = r.mission_id
    JOIN listings l ON l.id = m.listing_id
    JOIN products p ON p.key = l.product_key`;
async function missionRuns(db2, missionId, limit = 100) {
  const rows = await db2.query(
    `${RUN_SELECT} WHERE r.mission_id = $1 ORDER BY r.started_at DESC, r.id DESC LIMIT $2`,
    [missionId, Math.min(Math.max(limit, 1), 500)]
  );
  return rows.map(toRun);
}
async function recentRuns(db2, limit = 50) {
  const rows = await db2.query(
    `${RUN_SELECT} ORDER BY r.started_at DESC, r.id DESC LIMIT $1`,
    [Math.min(Math.max(limit, 1), 200)]
  );
  return rows.map(toRun);
}
async function recordObservation(db2, obs) {
  const prior = await db2.query(
    "SELECT state, price, seller_kind FROM watch_state WHERE listing_id = $1",
    [obs.listingId]
  );
  const before = prior[0] ?? null;
  const isFirst = before === null;
  const previousPrice = before ? toPrice(before.price) : null;
  const price = obs.price ?? null;
  const sellerKind = obs.sellerKind ?? "unknown";
  const changed = !isFirst && (before.state !== obs.state || previousPrice !== price || before.seller_kind !== sellerKind);
  await db2.query(
    `INSERT INTO watch_state (
       listing_id, state, confidence, price, seller_kind, seller_name,
       available_quantity, order_limit, is_preorder, release_date, note,
       last_checked_at, last_changed_at
     ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11, now(), now())
     ON CONFLICT (listing_id) DO UPDATE SET
       state = EXCLUDED.state,
       confidence = EXCLUDED.confidence,
       price = EXCLUDED.price,
       seller_kind = EXCLUDED.seller_kind,
       seller_name = EXCLUDED.seller_name,
       available_quantity = EXCLUDED.available_quantity,
       order_limit = EXCLUDED.order_limit,
       is_preorder = EXCLUDED.is_preorder,
       release_date = EXCLUDED.release_date,
       note = EXCLUDED.note,
       last_checked_at = now(),
       -- Only move this when something actually moved, so "in stock since"
       -- means what it says instead of resetting on every poll.
       last_changed_at = CASE WHEN $12 THEN now() ELSE watch_state.last_changed_at END`,
    [
      obs.listingId,
      obs.state,
      obs.confidence ?? "unknown",
      price,
      sellerKind,
      obs.sellerName ?? "",
      obs.availableQuantity ?? null,
      obs.orderLimit ?? null,
      obs.isPreOrder ?? false,
      obs.releaseDate ?? null,
      (obs.note ?? "").slice(0, 500),
      changed
    ]
  );
  if (sellerKind !== "unknown") {
    await db2.query("UPDATE listings SET seller_kind = $1, seller_name = $2 WHERE id = $3", [
      sellerKind,
      obs.sellerName ?? "",
      obs.listingId
    ]);
  }
  if (obs.imageUrl) {
    await db2.query(
      `UPDATE products SET image_url = $1
        WHERE image_url = ''
          AND key = (SELECT product_key FROM listings WHERE id = $2)`,
      [obs.imageUrl, obs.listingId]
    );
  }
  if (changed || isFirst) {
    await db2.query(
      `INSERT INTO observations
         (listing_id, state, confidence, price, seller_kind, seller_name,
          available_quantity, note)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
      [
        obs.listingId,
        obs.state,
        obs.confidence ?? "unknown",
        price,
        sellerKind,
        obs.sellerName ?? "",
        obs.availableQuantity ?? null,
        (obs.note ?? "").slice(0, 500)
      ]
    );
  }
  return { changed, isFirst, previousState: before?.state ?? null, previousPrice };
}
async function recentObservations(db2, limit = 50) {
  const rows = await db2.query(
    `SELECT o.listing_id, p.name AS product_name, l.retailer, o.state, o.price,
            o.seller_kind, o.seller_name, o.note, o.at
       FROM observations o
       JOIN listings l ON l.id = o.listing_id
       JOIN products p ON p.key = l.product_key
      ORDER BY o.at DESC, o.id DESC
      LIMIT $1`,
    [Math.min(Math.max(limit, 1), 200)]
  );
  return rows.map((r) => ({
    listingId: Number(r.listing_id),
    productName: String(r.product_name ?? ""),
    retailer: String(r.retailer ?? ""),
    state: String(r.state ?? ""),
    price: toPrice(r.price),
    sellerKind: String(r.seller_kind ?? "unknown"),
    sellerName: String(r.seller_name ?? ""),
    note: String(r.note ?? ""),
    at: r.at ? new Date(String(r.at)).toISOString() : ""
  }));
}

// src/discover.ts
var DEFAULT_CHILD_LIMIT = 3;
var MAX_ITEMS_PER_SWEEP = 5e3;
function rotate(items, cursor, limit) {
  if (items.length === 0 || limit <= 0) return [];
  if (limit >= items.length) return items.slice();
  const start = (cursor % items.length + items.length) % items.length;
  const out = [];
  for (let i = 0; i < limit; i++) out.push(items[(start + i) % items.length]);
  return out;
}
function nextCursor(cursor, limit, total) {
  if (total <= 0 || limit <= 0) return 0;
  return (cursor + limit) % total;
}
function productsFromSitemap(xml, retailer) {
  const locs = extractLocs(xml);
  const out = [];
  for (const loc of locs) {
    const item = fromUrl(loc, retailer);
    if (item) out.push(item);
  }
  return out;
}
async function collect(source, fetchText2) {
  const config = source.config;
  const headers = config.headers ?? {};
  if (source.kind === "json_list") {
    const text = await fetchText2(source.url, headers);
    let payload;
    try {
      payload = JSON.parse(text);
    } catch {
      throw new FetchError("response was not valid JSON", 0, false);
    }
    return { items: parseJsonList(payload, config), childTotal: 0 };
  }
  if (source.kind === "sitemap" || source.kind === "sitemap_index") {
    const text = await fetchText2(source.url, headers);
    const kind = sitemapKind(text);
    if (kind === "index" || source.kind === "sitemap_index") {
      const children = extractLocs(text);
      const limit = config.childLimit ?? DEFAULT_CHILD_LIMIT;
      const window = rotate(children, source.cursor ?? 0, limit);
      const all = [];
      for (const child of window) {
        try {
          const childXml = await fetchText2(child, headers);
          all.push(...productsFromSitemap(childXml, source.retailer));
        } catch (err) {
          console.warn("child sitemap failed", child, String(err));
        }
        if (all.length >= MAX_ITEMS_PER_SWEEP) break;
      }
      return { items: all, childTotal: children.length };
    }
    return { items: productsFromSitemap(text, source.retailer), childTotal: 0 };
  }
  return { items: [], childTotal: 0 };
}
async function sweepSource(db2, source, fetchText2 = fetchText) {
  const config = source.config;
  const base = {
    sourceId: source.id,
    label: source.label,
    ok: true,
    seen: 0,
    fresh: [],
    seeded: source.seeded
  };
  let collected;
  try {
    collected = await collect(source, fetchText2);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await finishSweep(db2, source.id, `error: ${message}`, 0, source.seeded, source.cursor ?? 0);
    await logEvent(db2, "sweep_error", `${source.label}: ${message}`);
    return { ...base, ok: false, error: message };
  }
  const items = dedupe(applyFilters(collected.items, config.filters)).slice(0, MAX_ITEMS_PER_SWEEP);
  const known = await knownIds(db2, source.id);
  const fresh = items.filter((i) => !known.has(i.externalId));
  const alreadySeeded = source.seeded;
  const announced = await recordDiscoveries(db2, source.id, fresh, alreadySeeded);
  for (const item of announced) {
    await attachIdentity(db2, source.id, source.retailer, item);
  }
  const limit = config.childLimit ?? DEFAULT_CHILD_LIMIT;
  const advanced = nextCursor(source.cursor ?? 0, limit, collected.childTotal);
  const lapComplete = collected.childTotal === 0 || advanced === 0;
  const nowSeeded = alreadySeeded || lapComplete;
  const status = alreadySeeded ? `ok, ${fresh.length} new of ${items.length}` : lapComplete ? `seeded ${fresh.length} on final pass` : `seeding, pass ends at child ${advanced} of ${collected.childTotal}`;
  await finishSweep(db2, source.id, status, items.length, nowSeeded, advanced);
  if (!alreadySeeded) {
    await logEvent(
      db2,
      "seed",
      `${source.label}: recorded ${fresh.length} silently (${status})`
    );
  }
  return { ...base, seen: items.length, fresh: announced, seeded: nowSeeded };
}
async function sweepAll(db2, fetchText2 = fetchText) {
  const sources = await listSources(db2, "hub");
  const results = [];
  for (const source of sources) {
    results.push(await sweepSource(db2, source, fetchText2));
  }
  return results;
}

// src/notify.ts
var COLOR_NEW = 2059087;
var COLOR_OPS = 9069584;
var MAX_FIELDS = 20;
function clip(s, n) {
  return s.length <= n ? s : `${s.slice(0, n - 1)}\u2026`;
}
function buildDiscoveryEmbed(label, retailer, items, now) {
  const shown = items.slice(0, MAX_FIELDS);
  const fields = shown.map((i) => ({
    name: clip(i.name || i.externalId, 240),
    value: clip(i.url ? `[${i.externalId}](${i.url})` : i.externalId, 1e3)
  }));
  const extra = items.length - shown.length;
  return {
    title: `\u{1F195} ${items.length} new ${items.length === 1 ? "product" : "products"} \u2014 ${retailer}`,
    description: `Seen for the first time in **${label}**.` + (extra > 0 ? `
_${extra} more not listed._` : ""),
    color: COLOR_NEW,
    fields,
    footer: { text: "catalog discovery \xB7 not a stock signal" },
    timestamp: now
  };
}
function buildOpsEmbed(results, now) {
  const failed = results.filter((r) => !r.ok);
  if (failed.length === 0) return null;
  return {
    title: `\u26A0\uFE0F ${failed.length} source${failed.length === 1 ? "" : "s"} failed`,
    color: COLOR_OPS,
    fields: failed.slice(0, MAX_FIELDS).map((r) => ({
      name: clip(r.label, 240),
      value: clip(r.error ?? "unknown error", 1e3)
    })),
    timestamp: now
  };
}
async function post(url, embeds) {
  if (!url || embeds.length === 0) return;
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ embeds: embeds.slice(0, 10) })
    });
    if (!res.ok && res.status !== 204) {
      const detail = await res.text().catch(() => "");
      console.warn("discord rejected the post", res.status, detail.slice(0, 300));
    }
  } catch (err) {
    console.warn("discord unreachable", err instanceof Error ? err.message : String(err));
  }
}
async function announce(webhookUrl, label, retailer, items, now) {
  if (items.length === 0) return;
  await post(webhookUrl, [buildDiscoveryEmbed(label, retailer, items, now)]);
}
async function reportOps(webhookUrl, results, now) {
  const embed = buildOpsEmbed(results, now);
  if (embed) await post(webhookUrl, [embed]);
}

// src/auth.ts
var SESSION_COOKIE = "hub_session";
var SESSION_HOURS = 24 * 14;
function b64url(bytes) {
  return Buffer.from(bytes).toString("base64url");
}
async function hmac(secret, message) {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return b64url(new Uint8Array(sig));
}
function safeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}
async function mintSession(secret, now = Date.now()) {
  const expires = now + SESSION_HOURS * 3600 * 1e3;
  const payload = String(expires);
  return `${payload}.${await hmac(secret, payload)}`;
}
async function sessionValid(secret, token, now = Date.now()) {
  if (!token) return false;
  const dot = token.lastIndexOf(".");
  if (dot < 1) return false;
  const payload = token.slice(0, dot);
  const signature = token.slice(dot + 1);
  const expected = await hmac(secret, payload);
  if (!safeEqual(signature, expected)) return false;
  const expires = Number(payload);
  return Number.isFinite(expires) && expires > now;
}
function readCookie(request, name) {
  const header = request.headers.get("cookie") ?? "";
  for (const part of header.split(";")) {
    const [k, ...rest] = part.trim().split("=");
    if (k === name) return decodeURIComponent(rest.join("="));
  }
  return null;
}
function sessionCookie(value, secure) {
  const bits = [
    `${SESSION_COOKIE}=${encodeURIComponent(value)}`,
    "Path=/",
    // HttpOnly: script on the page can never read it, so an injected script
    // cannot post the session anywhere.
    "HttpOnly",
    // Lax: the cookie is not sent on cross-site POSTs, which is the CSRF that
    // would otherwise let another tab trigger a buy.
    "SameSite=Lax",
    `Max-Age=${SESSION_HOURS * 3600}`
  ];
  if (secure) bits.push("Secure");
  return bits.join("; ");
}
function clearCookie(secure) {
  const bits = [`${SESSION_COOKIE}=`, "Path=/", "HttpOnly", "SameSite=Lax", "Max-Age=0"];
  if (secure) bits.push("Secure");
  return bits.join("; ");
}
async function identify(request, env2) {
  const header = request.headers.get("Authorization") ?? "";
  if (env2.INGEST_TOKEN && header.startsWith("Bearer ")) {
    if (safeEqual(header.slice(7), env2.INGEST_TOKEN)) return "watcher";
  }
  if (env2.APP_PASSWORD) {
    const cookie = readCookie(request, SESSION_COOKIE);
    if (await sessionValid(env2.APP_PASSWORD, cookie)) return "browser";
  }
  return "none";
}

// src/page.ts
function esc(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
var STYLE = `
:root {
  color-scheme: light dark;
  --bg: #fbfaf8; --panel: #ffffff; --line: #e6e2dc;
  --ink: #1c1a17; --muted: #6d675e;
  --in: #1c6b45; --in-bg: #e6f4ec;
  --out: #7a736a; --out-bg: #f1efec;
  --warn: #8a5a10; --warn-bg: #fdf1dd;
  --alert: #a3341f; --alert-bg: #fbeae6;
  --accent: #2a5db0;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #16150f; --panel: #1e1d17; --line: #33312a;
    --ink: #edeae4; --muted: #a09a90;
    --in: #6fd39d; --in-bg: #14301f;
    --out: #8f887e; --out-bg: #242219;
    --warn: #e0b060; --warn-bg: #33270f;
    --alert: #f0907a; --alert-bg: #3a1d16;
    --accent: #8fb4f5;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--ink);
  font: 15px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
}
main { max-width: 1000px; margin: 0 auto; padding: 28px 20px 80px; }
header { display: flex; align-items: baseline; gap: 14px; flex-wrap: wrap; margin-bottom: 4px; }
h1 { font-size: 21px; margin: 0; letter-spacing: -0.01em; }
.sub { color: var(--muted); font-size: 13px; }
.bar { display: flex; gap: 10px; align-items: center; margin: 18px 0 20px; flex-wrap: wrap; }
button, .btn {
  font: inherit; padding: 7px 13px; border-radius: 8px; cursor: pointer;
  border: 1px solid var(--line); background: var(--panel); color: var(--ink);
}
button:hover { border-color: var(--muted); }
.card {
  background: var(--panel); border: 1px solid var(--line);
  border-radius: 12px; padding: 14px 16px; margin-bottom: 10px;
}
.row { display: flex; gap: 14px; align-items: flex-start; flex-wrap: wrap; }
.grow { flex: 1 1 260px; min-width: 0; }
.name { font-weight: 600; margin-bottom: 2px; }
.meta { color: var(--muted); font-size: 13px; }
.price { font-variant-numeric: tabular-nums; font-size: 19px; font-weight: 600; white-space: nowrap; }
.pill {
  display: inline-block; padding: 2px 9px; border-radius: 999px;
  font-size: 12px; font-weight: 600; letter-spacing: 0.02em; white-space: nowrap;
}
.s-in { background: var(--in-bg); color: var(--in); }
.s-out { background: var(--out-bg); color: var(--out); }
.s-unknown, .s-unchecked, .s-queue { background: var(--warn-bg); color: var(--warn); }
.flag { background: var(--alert-bg); color: var(--alert); }
a { color: var(--accent); }
.empty { color: var(--muted); padding: 30px 0; text-align: center; }
.stale { color: var(--alert); font-weight: 600; }
table { width: 100%; border-collapse: collapse; font-size: 13px; }
td { padding: 6px 8px; border-top: 1px solid var(--line); vertical-align: top; }
h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 0.06em;
     color: var(--muted); margin: 34px 0 10px; }

/* \u2500\u2500 mission management \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */
.tabs { display: flex; gap: 4px; margin: 18px 0 16px; border-bottom: 1px solid var(--line); }
.tab {
  padding: 8px 14px; cursor: pointer; border: none; background: none;
  color: var(--muted); border-bottom: 2px solid transparent; border-radius: 0;
  font: inherit;
}
.tab:hover { color: var(--ink); border-color: var(--line); }
.tab.on { color: var(--ink); border-bottom-color: var(--accent); font-weight: 600; }
.thumb {
  width: 56px; height: 56px; border-radius: 8px; object-fit: contain;
  background: var(--out-bg); flex: 0 0 auto;
}
.thumb.ph { display: flex; align-items: center; justify-content: center;
            color: var(--muted); font-size: 20px; }
form.stack { display: grid; gap: 8px; max-width: 560px; }
label.f { display: grid; gap: 4px; font-size: 13px; color: var(--muted); }
input[type=text], input[type=url], input[type=number], input[type=date], select, textarea {
  font: inherit; padding: 8px 10px; border-radius: 8px;
  border: 1px solid var(--line); background: var(--bg); color: var(--ink); width: 100%;
}
.inline { display: flex; gap: 8px; flex-wrap: wrap; align-items: end; }
.inline > * { flex: 1 1 160px; }
.inline > button { flex: 0 0 auto; }
.danger { color: var(--alert); border-color: var(--alert); }
.armed { background: var(--alert-bg); color: var(--alert); }
.off { opacity: 0.55; }
.msg { font-size: 13px; min-height: 18px; }
.msg.bad { color: var(--alert); }
.msg.good { color: var(--in); }
details > summary { cursor: pointer; color: var(--muted); font-size: 13px; }
.runs td:first-child { white-space: nowrap; }
.o-bought { color: var(--in); font-weight: 600; }
.o-failed, .o-blocked { color: var(--alert); font-weight: 600; }
.o-declined { color: var(--warn); }
.login { max-width: 340px; margin: 16vh auto; }
input[type=password] {
  font: inherit; width: 100%; padding: 9px 11px; border-radius: 8px;
  border: 1px solid var(--line); background: var(--panel); color: var(--ink);
}
.err { color: var(--alert); font-size: 13px; min-height: 20px; }
`;
function loginPage(message = "") {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Hub</title><style>${STYLE}</style></head>
<body><main class="login">
  <h1>Hub</h1>
  <p class="sub">Sign in to see what's being watched.</p>
  <form method="POST" action="/login" style="margin-top:18px">
    <input type="password" name="password" placeholder="Password" autofocus required
           autocomplete="current-password">
    <div class="err" style="margin:8px 0">${esc(message)}</div>
    <button type="submit" style="width:100%">Sign in</button>
  </form>
</main></body></html>`;
}
function dashboardPage() {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Hub</title><style>${STYLE}</style></head>
<body><main>
  <header>
    <h1>Hub</h1>
    <span class="sub" id="summary">loading\u2026</span>
  </header>

  <div class="tabs">
    <button class="tab on" data-tab="missions">Missions</button>
    <button class="tab" data-tab="products">Products</button>
    <button class="tab" data-tab="activity">Activity</button>
  </div>

  <div class="bar">
    <button id="refresh">Refresh</button>
    <label class="sub"><input type="checkbox" id="auto" checked> auto every 30s</label>
    <span class="grow"></span>
    <a class="btn" href="/logout">Sign out</a>
  </div>

  <section id="tab-missions"><div id="missions"></div></section>

  <section id="tab-products" hidden>
    <div class="card">
      <div class="name">Add a product</div>
      <p class="meta">The thing itself. Where to buy it comes next.</p>
      <form class="stack" id="product-form" style="margin-top:10px">
        <label class="f">Name
          <input type="text" name="name" required placeholder="Pok\xE9mon TCG: Pitch Black Elite Trainer Box">
        </label>
        <label class="f">Release date <span style="opacity:.7">(optional)</span>
          <input type="date" name="releaseDate">
        </label>
        <div class="inline">
          <button type="submit">Add product</button>
          <span class="msg" id="product-msg"></span>
        </div>
      </form>
    </div>
    <div id="products"></div>
  </section>

  <section id="tab-activity" hidden>
    <h2 style="margin-top:0">Mission runs</h2>
    <p class="meta" style="margin:-6px 0 10px">
      Only written when a mission did something, or could not. Routine checks
      that found nothing are not runs.
    </p>
    <div class="card"><table class="runs" id="runs"><tbody></tbody></table></div>

    <h2>Stock and price changes</h2>
    <div class="card"><table id="feed"><tbody></tbody></table></div>
  </section>
</main>
<script>
const money = (n) => n === null || n === undefined ? '\u2014' : '$' + Number(n).toFixed(2);

function ago(iso) {
  if (!iso) return 'never';
  const s = Math.max(0, (Date.now() - new Date(iso).getTime()) / 1000);
  if (s < 60) return Math.round(s) + 's ago';
  if (s < 3600) return Math.round(s / 60) + 'm ago';
  if (s < 86400) return Math.round(s / 3600) + 'h ago';
  return Math.round(s / 86400) + 'd ago';
}

// Anything older than five minutes is not a live reading. Say so loudly
// rather than showing a stale price as though it were current.
const STALE_MS = 5 * 60 * 1000;

let DATA = { missions: [], runs: [], changes: [], products: [], listings: [] };

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
}

async function api(method, path, body) {
  const res = await fetch(path, {
    method,
    headers: body ? { 'Content-Type': 'application/json' } : {},
    body: body ? JSON.stringify(body) : undefined,
  });
  if (res.status === 401) { location.href = '/login'; throw new Error('signed out'); }
  const data = await res.json().catch(() => ({}));
  // The API answers failures in sentences. Show the sentence, not the status.
  if (!res.ok) throw new Error(data.error || (method + ' ' + path + ' failed'));
  return data;
}

function say(id, text, ok) {
  const n = document.getElementById(id);
  n.textContent = text;
  n.className = 'msg ' + (ok ? 'good' : 'bad');
  if (ok) setTimeout(() => { n.textContent = ''; }, 4000);
}

function thumb(url, alt) {
  if (!url) {
    const ph = el('div', 'thumb ph', '\u25A6');
    ph.title = 'no image yet \u2014 the Watcher fills this in on its first read';
    return ph;
  }
  const img = el('img', 'thumb');
  img.src = url;
  img.alt = alt || '';
  img.loading = 'lazy';
  // A dead CDN URL should degrade to the placeholder, not a broken-image icon.
  img.addEventListener('error', () => img.replaceWith(thumb('', alt)));
  return img;
}

/* \u2500\u2500 missions \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */

function missionCard(m) {
  const card = el('div', 'card' + (m.enabled ? '' : ' off'));
  const row = el('div', 'row');
  row.appendChild(thumb(m.imageUrl, m.productName));

  const left = el('div', 'grow');
  left.appendChild(el('div', 'name', m.productName));

  const meta = el('div', 'meta');
  meta.append(m.retailer + ' \xB7 ' + (m.externalId || '\u2014') + ' \xB7 ');
  const a = el('a', null, 'open');
  a.href = m.url; a.target = '_blank'; a.rel = 'noreferrer';
  meta.appendChild(a);
  left.appendChild(meta);

  const flags = el('div', 'meta');
  flags.style.marginTop = '6px';
  const label = m.state === 'in' ? 'IN STOCK'
    : m.state === 'out' ? 'out of stock'
    : m.state === 'unchecked' ? 'never checked' : m.state;
  flags.appendChild(el('span', 'pill s-' + m.state, label));

  if (!m.enabled) { flags.append(' '); flags.appendChild(el('span', 'pill s-out', 'paused')); }
  if (m.armed) {
    flags.append(' ');
    flags.appendChild(el('span', 'pill armed', 'ARMED \xB7 ' + m.quantity + ' @ ' + money(m.ceiling)));
  }
  // The Walmart trap, made visible rather than buried in a note nobody reads.
  if (m.sellerKind === 'marketplace') {
    flags.append(' ');
    flags.appendChild(el('span', 'pill flag', 'marketplace: ' + (m.sellerName || 'third party')));
  }
  if (m.confidence !== 'exact' && m.state !== 'unchecked') {
    flags.append(' ');
    flags.appendChild(el('span', 'pill s-unknown', m.confidence + ' read'));
  }
  if (m.isPreOrder) {
    flags.append(' ');
    flags.appendChild(el('span', 'pill s-queue',
      'preorder' + (m.releaseDate ? ' \xB7 ' + m.releaseDate : '')));
  }
  left.appendChild(flags);
  if (m.note) {
    const note = el('div', 'meta', m.note);
    note.style.marginTop = '6px';
    left.appendChild(note);
  }

  const right = el('div');
  right.style.textAlign = 'right';
  right.appendChild(el('div', 'price', money(m.price)));
  const stale = m.lastCheckedAt && (Date.now() - new Date(m.lastCheckedAt).getTime()) > STALE_MS;
  const checked = el('div', (stale || !m.lastCheckedAt) ? 'meta stale' : 'meta',
    'checked ' + ago(m.lastCheckedAt));
  right.appendChild(checked);
  if (m.state === 'in' && m.lastChangedAt) {
    right.appendChild(el('div', 'meta', 'since ' + ago(m.lastChangedAt)));
  }
  if (m.availableQuantity !== null && m.availableQuantity !== undefined) {
    right.appendChild(el('div', 'meta', m.availableQuantity + ' available'));
  }

  row.append(left, right);
  card.appendChild(row);
  card.appendChild(missionControls(m));
  return card;
}

function missionControls(m) {
  const wrap = el('details');
  wrap.style.marginTop = '10px';
  wrap.appendChild(el('summary', null, 'Settings and history'));

  const form = el('form', 'stack');
  form.style.marginTop = '10px';
  form.innerHTML = \`
    <div class="inline">
      <label class="f">Price ceiling
        <input type="number" name="ceiling" step="0.01" min="0.01" placeholder="none">
      </label>
      <label class="f">Quantity
        <input type="number" name="quantity" min="1" max="20" value="1">
      </label>
      <label class="f">Check every
        <select name="checkEverySeconds">
          <option value="30">30 seconds</option>
          <option value="60">1 minute</option>
          <option value="300">5 minutes</option>
          <option value="1800">30 minutes</option>
          <option value="3600">1 hour</option>
        </select>
      </label>
      <label class="f">Sellers
        <select name="sellerPolicy">
          <option value="retailer_only">The retailer only</option>
          <option value="any">Any seller, under the ceiling</option>
        </select>
      </label>
    </div>
    <div class="inline">
      <label class="f" style="flex:0 0 auto">
        <span><input type="checkbox" name="enabled"> Watching</span>
      </label>
      <label class="f" style="flex:0 0 auto">
        <span><input type="checkbox" name="armed"> Armed \u2014 may buy</span>
      </label>
      <span class="grow"></span>
      <button type="submit">Save</button>
      <button type="button" class="danger" data-del="\${m.id}">Delete</button>
    </div>
    <span class="msg" id="m-msg-\${m.id}"></span>\`;

  form.ceiling.value = m.ceiling ?? '';
  form.quantity.value = m.quantity;
  form.checkEverySeconds.value = String(m.checkEverySeconds);
  form.sellerPolicy.value = m.sellerPolicy;
  form.enabled.checked = m.enabled;
  form.armed.checked = m.armed;

  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    try {
      await api('POST', '/api/missions', {
        listingId: m.listingId,
        label: m.label,
        enabled: form.enabled.checked,
        armed: form.armed.checked,
        ceiling: form.ceiling.value === '' ? null : Number(form.ceiling.value),
        quantity: Number(form.quantity.value),
        sellerPolicy: form.sellerPolicy.value,
        checkEverySeconds: Number(form.checkEverySeconds.value),
      });
      say('m-msg-' + m.id, 'saved', true);
      load();
    } catch (err) {
      say('m-msg-' + m.id, err.message, false);
    }
  });

  form.querySelector('[data-del]').addEventListener('click', async () => {
    if (!confirm('Delete this mission? The product and its listing stay.')) return;
    try {
      await api('DELETE', '/api/missions/' + m.id);
      load();
    } catch (err) { say('m-msg-' + m.id, err.message, false); }
  });

  wrap.appendChild(form);

  const runs = el('div');
  runs.style.marginTop = '10px';
  const btn = el('button', null, 'Show this mission\u2019s runs');
  btn.addEventListener('click', async () => {
    btn.remove();
    try {
      const data = await api('GET', '/api/missions/' + m.id + '/runs');
      runs.appendChild(runTable(data.runs, 'This mission has not run yet.'));
    } catch (err) {
      runs.appendChild(el('div', 'msg bad', err.message));
    }
  });
  runs.appendChild(btn);
  wrap.appendChild(runs);
  return wrap;
}

function runTable(runs, emptyText) {
  const table = el('table', 'runs');
  const body = el('tbody');
  if (!runs.length) {
    const tr = el('tr');
    const td = el('td', 'meta', emptyText);
    td.colSpan = 5; tr.appendChild(td); body.appendChild(tr);
  }
  for (const r of runs) {
    const tr = el('tr');
    tr.appendChild(el('td', 'meta', ago(r.startedAt)));
    tr.appendChild(el('td', null, r.productName));
    tr.appendChild(el('td', 'o-' + r.outcome, r.outcome));
    // Every non-success carries a reason. Showing it here is the whole point
    // of recording it.
    tr.appendChild(el('td', 'meta', r.reason || ''));
    const right = el('td', 'meta',
      [r.price !== null ? money(r.price) : '', r.ms !== null ? r.ms + 'ms' : '']
        .filter(Boolean).join(' \xB7 '));
    right.style.textAlign = 'right';
    tr.appendChild(right);
    body.appendChild(tr);
  }
  table.appendChild(body);
  return table;
}

/* \u2500\u2500 products \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */

function productCard(p) {
  const card = el('div', 'card');
  const row = el('div', 'row');
  row.appendChild(thumb(p.imageUrl, p.name));

  const left = el('div', 'grow');
  left.appendChild(el('div', 'name', p.name));
  const meta = el('div', 'meta',
    p.releaseDate ? 'releases ' + p.releaseDate : 'no release date set');
  left.appendChild(meta);

  const mine = DATA.listings.filter((l) => l.productKey === p.key);
  const list = el('div', 'meta');
  list.style.marginTop = '6px';
  if (!mine.length) {
    list.textContent = 'No listings yet \u2014 paste a product URL below.';
  } else {
    for (const l of mine) {
      const line = el('div');
      line.append(l.retailer + ' \xB7 ' + l.externalId + ' ');
      const del = el('button', 'danger');
      del.textContent = 'remove';
      del.style.padding = '0 6px';
      del.style.fontSize = '12px';
      del.addEventListener('click', async () => {
        if (!confirm('Remove this listing? Its mission and history go with it.')) return;
        try { await api('DELETE', '/api/listings/' + l.id); load(); }
        catch (err) { say('p-msg-' + p.key, err.message, false); }
      });
      line.appendChild(del);
      list.appendChild(line);
    }
  }
  left.appendChild(list);

  const form = el('form', 'inline');
  form.style.marginTop = '8px';
  form.innerHTML = \`
    <input type="url" name="url" required placeholder="Paste a Target / Pok\xE9mon Center / Walmart product URL">
    <button type="submit">Add listing</button>\`;
  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    try {
      const { listing } = await api('POST', '/api/listings',
        { productKey: p.key, url: form.url.value });
      // A listing with no mission is a thing you meant to watch and didn't.
      await api('POST', '/api/missions', { listingId: listing.id, label: p.name, enabled: true });
      form.reset();
      say('p-msg-' + p.key, 'added ' + listing.retailer + ' ' + listing.externalId, true);
      load();
    } catch (err) { say('p-msg-' + p.key, err.message, false); }
  });
  left.appendChild(form);
  left.appendChild(Object.assign(el('span', 'msg'), { id: 'p-msg-' + p.key }));

  const right = el('div');
  right.style.textAlign = 'right';
  const del = el('button', 'danger', 'Delete product');
  del.addEventListener('click', async () => {
    if (!confirm('Delete "' + p.name + '"? Every listing, mission and run for it goes too.')) return;
    try { await api('DELETE', '/api/products/' + encodeURIComponent(p.key)); load(); }
    catch (err) { say('p-msg-' + p.key, err.message, false); }
  });
  right.appendChild(del);

  row.append(left, right);
  card.appendChild(row);
  return card;
}

/* \u2500\u2500 wiring \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */

function render() {
  const missions = document.getElementById('missions');
  missions.textContent = '';
  if (!DATA.missions.length) {
    missions.appendChild(el('div', 'empty',
      'No missions yet. Add a product, paste a listing URL, and one is created for you.'));
  }
  for (const m of DATA.missions) missions.appendChild(missionCard(m));

  const products = document.getElementById('products');
  products.textContent = '';
  for (const p of DATA.products) products.appendChild(productCard(p));

  const inStock = DATA.missions.filter((m) => m.state === 'in').length;
  const armed = DATA.missions.filter((m) => m.armed).length;
  const never = DATA.missions.filter((m) => m.state === 'unchecked').length;
  const parts = [DATA.missions.length + ' missions'];
  if (inStock) parts.push(inStock + ' in stock');
  if (armed) parts.push(armed + ' armed');
  if (never) parts.push(never + ' never checked');
  document.getElementById('summary').textContent = parts.join(' \xB7 ');

  const runs = document.getElementById('runs');
  runs.replaceWith(Object.assign(runTable(DATA.runs, 'Nothing has run yet.'), { id: 'runs' }));

  const feed = document.querySelector('#feed tbody');
  feed.textContent = '';
  if (!DATA.changes.length) {
    const tr = el('tr');
    const td = el('td', 'meta', 'Nothing has changed yet.');
    td.colSpan = 4; tr.appendChild(td); feed.appendChild(tr);
  }
  for (const o of DATA.changes) {
    const tr = el('tr');
    tr.appendChild(el('td', 'meta', ago(o.at)));
    tr.appendChild(el('td', null, o.productName));
    tr.appendChild(el('td', 'meta', o.retailer));
    const td = el('td');
    td.style.textAlign = 'right';
    td.append(o.state + ' \xB7 ' + money(o.price));
    tr.appendChild(td);
    feed.appendChild(tr);
  }
}

async function load() {
  try {
    DATA = await api('GET', '/api/dashboard');
  } catch (err) {
    document.getElementById('summary').textContent = err.message;
    return;
  }
  render();
}

document.getElementById('product-form').addEventListener('submit', async (e) => {
  e.preventDefault();
  const f = e.target;
  try {
    await api('POST', '/api/products',
      { name: f.name.value, releaseDate: f.releaseDate.value || null });
    f.reset();
    say('product-msg', 'added \u2014 now give it a listing URL below', true);
    load();
  } catch (err) { say('product-msg', err.message, false); }
});

for (const tab of document.querySelectorAll('.tab')) {
  tab.addEventListener('click', () => {
    for (const t of document.querySelectorAll('.tab')) t.classList.toggle('on', t === tab);
    for (const name of ['missions', 'products', 'activity']) {
      document.getElementById('tab-' + name).hidden = name !== tab.dataset.tab;
    }
  });
}

document.getElementById('refresh').addEventListener('click', load);
let timer = setInterval(load, 30000);
document.getElementById('auto').addEventListener('change', (e) => {
  clearInterval(timer);
  if (e.target.checked) timer = setInterval(load, 30000);
});
load();
</script>
</body></html>`;
}

// src/app.ts
function json(body, status = 200) {
  return new Response(JSON.stringify(body, null, 2), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8" }
  });
}
async function publish(db2, env2, results, now) {
  for (const result of results) {
    if (!result.ok || result.fresh.length === 0) continue;
    const source = await getSource(db2, result.sourceId);
    await announce(
      env2.DISCORD_WEBHOOK_URL,
      result.label,
      source?.retailer ?? "",
      result.fresh,
      now
    );
    await markAnnounced(
      db2,
      result.sourceId,
      result.fresh.map((f) => f.externalId)
    );
  }
  const opsUrl = env2.DISCORD_OPS_WEBHOOK_URL || env2.DISCORD_WEBHOOK_URL;
  await reportOps(opsUrl, results, now);
}
function html(body, status = 200, headers = {}) {
  return new Response(body, {
    status,
    headers: { "Content-Type": "text/html; charset=utf-8", ...headers }
  });
}
function redirect(to, headers = {}) {
  return new Response(null, { status: 303, headers: { Location: to, ...headers } });
}
function createHandler(db2, env2) {
  return async function handle(request) {
    const url = new URL(request.url);
    const path = url.pathname.replace(/\/+$/, "") || "/";
    const now = (/* @__PURE__ */ new Date()).toISOString();
    if (request.method === "GET" && path === "/health") {
      const sources = await listSources(db2);
      return json({
        ok: true,
        sources: sources.map((s) => ({
          id: s.id,
          label: s.label,
          via: s.via,
          seeded: s.seeded,
          lastSweptAt: s.lastSweptAt,
          lastStatus: s.lastStatus,
          lastCount: s.lastCount
        }))
      });
    }
    const secure = url.protocol === "https:";
    if (path === "/login") {
      if (request.method === "GET") return html(loginPage());
      const form = await request.formData().catch(() => null);
      const given = String(form?.get("password") ?? "");
      if (!env2.APP_PASSWORD) {
        return html(loginPage("No password is set on this deployment."), 500);
      }
      if (!safeEqual(given, env2.APP_PASSWORD)) {
        await new Promise((r) => setTimeout(r, 400));
        return html(loginPage("That is not the password."), 401);
      }
      return redirect("/", {
        "Set-Cookie": sessionCookie(await mintSession(env2.APP_PASSWORD), secure)
      });
    }
    if (path === "/logout") {
      return redirect("/login", { "Set-Cookie": clearCookie(secure) });
    }
    const caller = await identify(request, env2);
    if (caller === "none") {
      const wantsHtml = (request.headers.get("accept") ?? "").includes("text/html");
      if (wantsHtml) return redirect("/login");
      return json({ error: "unauthorised" }, 401);
    }
    if (request.method === "GET" && (path === "/" || path === "/dashboard")) {
      return html(dashboardPage());
    }
    if (request.method === "GET" && path === "/api/dashboard") {
      const [missions, runs, changes, products, listings] = await Promise.all([
        listMissions(db2),
        recentRuns(db2, 40),
        recentObservations(db2, 40),
        listProducts(db2),
        listListings(db2)
      ]);
      return json({ missions, runs, changes, products, listings, now });
    }
    if (request.method === "GET" && path.startsWith("/api/missions/") && path.endsWith("/runs")) {
      const id = Number(path.split("/")[3]);
      if (!Number.isInteger(id)) return json({ error: "bad mission id" }, 400);
      const mission = await getMission(db2, id);
      if (!mission) return json({ error: "no such mission" }, 404);
      return json({ mission, runs: await missionRuns(db2, id, 200) });
    }
    const body = async () => await request.json().catch(() => null);
    if (request.method === "POST" && path === "/api/products") {
      const b = await body();
      if (!b?.name?.trim()) return json({ error: "a product needs a name" }, 400);
      return json({ product: await upsertProduct(db2, { name: b.name, releaseDate: b.releaseDate || null, notes: b.notes }) });
    }
    if (request.method === "DELETE" && path.startsWith("/api/products/")) {
      const key = decodeURIComponent(path.slice("/api/products/".length));
      if (!key) return json({ error: "no product key" }, 400);
      await deleteProduct(db2, key);
      return json({ deleted: key });
    }
    if (request.method === "POST" && path === "/api/listings") {
      const b = await body();
      if (!b?.productKey || !b?.url) return json({ error: "need a product and a URL" }, 400);
      const parsed = identifyListing(b.url);
      if (!parsed) {
        return json(
          {
            error: "could not read a retailer and product id out of that URL. Expected a target.com/p/\u2026/A-123, pokemoncenter.com/product/100-123/\u2026 or walmart.com/ip/\u2026/123 link."
          },
          400
        );
      }
      const listing = await addListing(db2, {
        productKey: b.productKey,
        retailer: parsed.retailer,
        externalId: parsed.externalId,
        url: b.url.trim()
      });
      return json({ listing });
    }
    if (request.method === "DELETE" && path.startsWith("/api/listings/")) {
      const id = Number(path.slice("/api/listings/".length));
      if (!Number.isInteger(id)) return json({ error: "bad listing id" }, 400);
      await deleteListing(db2, id);
      return json({ deleted: id });
    }
    if (request.method === "POST" && path === "/api/missions") {
      const b = await body();
      if (!b) return json({ error: "body must be JSON" }, 400);
      try {
        return json({ mission: await upsertMission(db2, b) });
      } catch (err) {
        return json({ error: err.message }, 400);
      }
    }
    if (request.method === "DELETE" && path.startsWith("/api/missions/")) {
      const id = Number(path.slice("/api/missions/".length));
      if (!Number.isInteger(id)) return json({ error: "bad mission id" }, 400);
      await deleteMission(db2, id);
      return json({ deleted: id });
    }
    if (request.method === "GET" && path === "/api/missions/active") {
      return json({ missions: await activeMissions(db2) });
    }
    if (request.method === "POST" && path === "/api/runs") {
      const b = await body();
      if (!b?.missionId || !b?.outcome || b.outcome === "running") {
        return json({ error: "need missionId and a settled outcome" }, 400);
      }
      const id = await recordRun(db2, b.missionId, {
        outcome: b.outcome,
        reason: b.reason,
        state: b.state,
        price: b.price,
        sellerKind: b.sellerKind,
        sellerName: b.sellerName,
        quantity: b.quantity,
        total: b.total
      });
      return json({ run: id });
    }
    if (request.method === "POST" && path === "/observations") {
      let body2;
      try {
        body2 = await request.json();
      } catch {
        return json({ error: "body must be JSON" }, 400);
      }
      if (!Array.isArray(body2.observations)) {
        return json({ error: "need observations[]" }, 400);
      }
      const results = [];
      const changes = [];
      for (const obs of body2.observations) {
        if (!obs?.listingId || !obs?.state) {
          results.push({
            listingId: obs?.listingId ?? 0,
            changed: false,
            error: "need listingId and state"
          });
          continue;
        }
        try {
          const outcome = await recordObservation(db2, obs);
          results.push({ listingId: obs.listingId, changed: outcome.changed });
          if (outcome.changed) changes.push({ obs, was: outcome.previousState });
        } catch (err) {
          results.push({ listingId: obs.listingId, changed: false, error: err.message });
        }
      }
      const cameIntoStock = changes.filter((c) => c.obs.state === "in" && c.was !== "in");
      if (cameIntoStock.length > 0 && env2.DISCORD_WEBHOOK_URL) {
        await announce(
          env2.DISCORD_WEBHOOK_URL,
          "In stock",
          "",
          cameIntoStock.map((c) => ({
            externalId: String(c.obs.listingId),
            name: c.obs.note || `listing ${c.obs.listingId}`,
            url: "",
            price: c.obs.price ?? null
          })),
          now
        );
      }
      return json({
        recorded: results.length,
        changed: results.filter((r) => r.changed).length,
        failed: results.filter((r) => r.error).length,
        results
      });
    }
    if (request.method === "POST" && path === "/sweep") {
      const only = url.searchParams.get("source");
      let results;
      if (only) {
        const source = await getSource(db2, only);
        if (!source) return json({ error: `no source "${only}"` }, 404);
        results = [await sweepSource(db2, source)];
      } else {
        results = await sweepAll(db2);
      }
      await publish(db2, env2, results, now);
      return json({
        swept: results.map((r) => ({
          source: r.sourceId,
          ok: r.ok,
          seen: r.seen,
          new: r.fresh.length,
          error: r.error
        }))
      });
    }
    if (request.method === "POST" && path === "/ingest") {
      let body2;
      try {
        body2 = await request.json();
      } catch {
        return json({ error: "body must be JSON" }, 400);
      }
      const sourceId = (body2.sourceId ?? "").trim();
      if (!sourceId || !Array.isArray(body2.items)) {
        return json({ error: "need sourceId and items[]" }, 400);
      }
      const source = await getSource(db2, sourceId);
      if (!source) return json({ error: `no source "${sourceId}"` }, 404);
      const config = source.config;
      const clean = dedupe(
        applyFilters(
          body2.items.filter((i) => i && typeof i.externalId === "string" && i.externalId),
          config.filters
        )
      );
      const known = await knownIds(db2, sourceId);
      const fresh = clean.filter((i) => !known.has(i.externalId));
      const isFirstSweep = !source.seeded;
      const toAnnounce = await recordDiscoveries(db2, sourceId, fresh, !isFirstSweep);
      for (const item of toAnnounce) {
        await attachIdentity(db2, sourceId, source.retailer, item);
      }
      await finishSweep(
        db2,
        sourceId,
        isFirstSweep ? `seeded ${fresh.length} via watcher` : `watcher: ${fresh.length} new`,
        clean.length,
        true
      );
      if (toAnnounce.length > 0) {
        await announce(env2.DISCORD_WEBHOOK_URL, source.label, source.retailer, toAnnounce, now);
        await markAnnounced(
          db2,
          sourceId,
          toAnnounce.map((f) => f.externalId)
        );
      }
      return json({
        received: clean.length,
        new: fresh.length,
        announced: toAnnounce.length,
        seeded: isFirstSweep
      });
    }
    if ((request.method === "POST" || request.method === "GET") && path === "/probe") {
      const sources = await listAllSources(db2);
      const checks = [];
      for (const source of sources) {
        if (source.via === "watcher" || !source.url) {
          checks.push({
            id: source.id,
            retailer: source.retailer,
            via: source.via,
            enabled: source.enabled,
            verdict: "watcher \u2014 never fetched from here"
          });
          continue;
        }
        const config = source.config;
        const result = await probeUrl(source.url, config.headers ?? {});
        checks.push({
          id: source.id,
          retailer: source.retailer,
          via: source.via,
          enabled: source.enabled,
          status: result.status,
          ms: result.ms,
          verdict: result.ok ? `reachable \u2014 ${result.note}` : result.blocked ? `BLOCKED (${result.status}) \u2014 move this source to via='watcher'` : `failed (${result.status}) \u2014 ${result.note}`
        });
      }
      const blocked = checks.filter((c) => String(c.verdict).startsWith("BLOCKED")).length;
      return json({
        summary: blocked === 0 ? "every hub source is reachable from here" : `${blocked} source(s) blocked \u2014 those belong to the Watcher`,
        checks
      });
    }
    if (request.method === "GET" && path === "/watchlist") {
      const [products, sources] = await Promise.all([
        watchlist(db2),
        listSources(db2, "watcher")
      ]);
      return json({
        products,
        sources: sources.map((s) => ({
          id: s.id,
          label: s.label,
          retailer: s.retailer,
          url: s.url,
          config: s.config
        }))
      });
    }
    return json({ error: "not found" }, 404);
  };
}

// src/db.ts
function fromPostgres(client) {
  return {
    async query(text, params = []) {
      const rows = await client.unsafe(text, params);
      return rows;
    },
    async batch(statements) {
      if (statements.length === 0) return;
      await client.begin(async (tx) => {
        for (const s of statements) await tx.unsafe(s.text, s.params ?? []);
      });
    },
    async exec(script) {
      await client.unsafe(script);
    }
  };
}
function connectionStringFrom(env2) {
  const url = env2.DATABASE_URL ?? env2.POSTGRES_URL ?? "";
  if (!url) {
    throw new Error(
      'DATABASE_URL is not set.\n  Supabase dashboard \u2192 the "Connect" button at the top \u2192 Shared pooler,\n  transaction mode. Put it in .env.local for local work, and in the Vercel\n  project settings for deploys.'
    );
  }
  if (!/^postgres(ql)?:\/\//.test(url)) {
    throw new Error("DATABASE_URL does not look like a Postgres connection string.");
  }
  const host = /@([^/:?]+)/.exec(url)?.[1] ?? "";
  if (/^db\.[a-z0-9-]+\.supabase\.co$/i.test(host)) {
    const port = /:(\d+)\//.exec(url)?.[1] ?? "";
    const which = port === "6543" ? "the dedicated pooler" : "the direct connection";
    throw new Error(
      `That is ${which} (${host}), which is IPv6-only unless you pay for the
  IPv4 add-on \u2014 and Vercel is IPv4, so it would fail on every deploy.
  Use the SHARED pooler instead: its host contains "pooler.supabase.com"
  and the username has the project ref on it (postgres.<ref>).
  Supabase dashboard \u2192 "Connect" \u2192 Shared pooler \u2192 Transaction mode.`
    );
  }
  return url;
}

// src/server.ts
var cached = null;
function db() {
  if (cached) return cached;
  const client = postgres(connectionStringFrom(process.env), {
    // The pooler does not support prepared statements.
    prepare: false,
    max: 1,
    idle_timeout: 20,
    connect_timeout: 10
  });
  cached = fromPostgres(client);
  return cached;
}
function env() {
  return {
    DATABASE_URL: process.env.DATABASE_URL ?? "",
    DISCORD_WEBHOOK_URL: process.env.DISCORD_WEBHOOK_URL ?? "",
    DISCORD_OPS_WEBHOOK_URL: process.env.DISCORD_OPS_WEBHOOK_URL,
    INGEST_TOKEN: process.env.INGEST_TOKEN,
    APP_PASSWORD: process.env.APP_PASSWORD
  };
}
async function readBody(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}
async function handler(req, res) {
  const host = req.headers.host ?? "localhost";
  const proto = req.headers["x-forwarded-proto"] ?? "https";
  const url = new URL(req.url ?? "/", `${proto}://${host}`);
  const method = req.method ?? "GET";
  const hasBody = method !== "GET" && method !== "HEAD";
  const request = new Request(url, {
    method,
    headers: Object.entries(req.headers).flatMap(
      ([k, v]) => typeof v === "string" ? [[k, v]] : []
    ),
    ...hasBody ? { body: await readBody(req) } : {}
  });
  let response;
  try {
    response = await createHandler(db(), env())(request);
  } catch (err) {
    response = new Response(
      JSON.stringify({ error: err.message }, null, 2),
      { status: 500, headers: { "Content-Type": "application/json; charset=utf-8" } }
    );
  }
  res.statusCode = response.status;
  response.headers.forEach((value, key) => res.setHeader(key, value));
  res.end(Buffer.from(await response.arrayBuffer()));
}
export {
  handler as default
};
