// Generated by npm run build from src/server.ts. Do not edit.

// src/server.ts
import postgres from "postgres";

// src/fetcher.ts
var UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
var FetchError = class extends Error {
  status;
  blocked;
  constructor(message, status, blocked) {
    super(message);
    this.name = "FetchError";
    this.status = status;
    this.blocked = blocked;
  }
};
function looksGzipped(url, contentType) {
  if (/\.gz(\?|$)/i.test(url)) return true;
  return /application\/(x-)?gzip/i.test(contentType ?? "");
}
async function gunzip(res) {
  if (!res.body) return "";
  const stream = res.body.pipeThrough(new DecompressionStream("gzip"));
  return new Response(stream).text();
}
async function fetchText(url, headers = {}, timeoutMs = 2e4) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": UA, Accept: "*/*", ...headers },
      signal: controller.signal,
      redirect: "follow"
    });
    if (!res.ok) {
      const blocked = res.status === 403 || res.status === 429 || res.status === 503;
      throw new FetchError(
        `${res.status} ${res.statusText || ""}`.trim() + (blocked ? " \u2014 looks like a block; this source needs the Watcher" : ""),
        res.status,
        blocked
      );
    }
    return looksGzipped(url, res.headers.get("content-type")) ? await gunzip(res) : await res.text();
  } catch (err) {
    if (err instanceof FetchError) throw err;
    const msg = err instanceof Error ? err.message : String(err);
    throw new FetchError(msg, 0, false);
  } finally {
    clearTimeout(timer);
  }
}
async function probeUrl(url, headers = {}) {
  const started = Date.now();
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": UA, Accept: "*/*", ...headers },
      redirect: "follow"
    });
    const blocked = res.status === 403 || res.status === 429 || res.status === 503;
    let note = "";
    if (res.ok && res.body) {
      const reader = res.body.getReader();
      const { value } = await reader.read();
      await reader.cancel().catch(() => {
      });
      const bytes = value?.length ?? 0;
      const head = new TextDecoder().decode((value ?? new Uint8Array()).slice(0, 200));
      note = /^\x1f\x8b/.test(head) || /gzip/i.test(res.headers.get("content-type") ?? "") ? `gzipped, ${bytes}B read` : /<sitemapindex/i.test(head) ? "sitemap index" : /<urlset/i.test(head) ? "sitemap" : `${bytes}B read`;
    } else if (blocked) {
      note = "blocked \u2014 this source needs the Watcher";
    } else if (!res.ok) {
      note = res.statusText || "not ok";
    }
    return { url, ok: res.ok, status: res.status, blocked, ms: Date.now() - started, note };
  } catch (err) {
    return {
      url,
      ok: false,
      status: 0,
      blocked: false,
      ms: Date.now() - started,
      note: err instanceof Error ? err.message : String(err)
    };
  }
}

// src/parsers/sitemap.ts
var LOC_RE = /<loc>([\s\S]*?)<\/loc>/gi;
var CDATA_RE = /^\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*$/;
var ENTITIES = {
  "&amp;": "&",
  "&lt;": "<",
  "&gt;": ">",
  "&quot;": '"',
  "&apos;": "'",
  "&#39;": "'"
};
function decodeEntities(s) {
  return s.replace(/&(?:amp|lt|gt|quot|apos|#39);/g, (m) => ENTITIES[m] ?? m);
}
function sitemapKind(xml) {
  const head = xml.slice(0, 4e3);
  if (/<sitemapindex[\s>]/i.test(head)) return "index";
  if (/<urlset[\s>]/i.test(head)) return "urlset";
  return "unknown";
}
function extractLocs(xml) {
  const out = [];
  LOC_RE.lastIndex = 0;
  let m;
  while ((m = LOC_RE.exec(xml)) !== null) {
    let raw = m[1] ?? "";
    const cdata = CDATA_RE.exec(raw);
    if (cdata) raw = cdata[1] ?? "";
    const value = decodeEntities(raw.trim());
    if (value) out.push(value);
  }
  return out;
}

// src/parsers/jsonList.ts
function pluck(obj, path) {
  if (!path) return obj;
  let cur = obj;
  for (const rawPart of path.split(".")) {
    const part = rawPart.trim();
    if (!part) continue;
    const idx = /^\[(\d+)\]$/.exec(part);
    if (idx) {
      if (!Array.isArray(cur)) return void 0;
      cur = cur[Number(idx[1])];
      continue;
    }
    if (cur === null || typeof cur !== "object") return void 0;
    cur = cur[part];
  }
  return cur;
}
function str(v) {
  if (v === null || v === void 0) return "";
  if (typeof v === "string") return v;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return "";
}
function num(v) {
  if (typeof v === "number" && Number.isFinite(v)) return v;
  if (typeof v === "string") {
    const n = Number(v.replace(/[^0-9.]/g, ""));
    return Number.isFinite(n) ? n : null;
  }
  return null;
}
function parseJsonList(payload, config) {
  const raw = pluck(payload, config.itemsPath ?? "");
  if (!Array.isArray(raw)) return [];
  const idField = config.idField ?? "id";
  const nameField = config.nameField ?? "title";
  const urlField = config.urlField ?? "url";
  const out = [];
  for (const item of raw) {
    if (item === null || typeof item !== "object") continue;
    const externalId = str(pluck(item, idField)).trim();
    if (!externalId) continue;
    out.push({
      externalId,
      name: str(pluck(item, nameField)).trim() || externalId,
      url: str(pluck(item, urlField)).trim(),
      price: config.priceField ? num(pluck(item, config.priceField)) : null
    });
  }
  return out;
}

// src/parsers/identify.ts
var TARGET_TCIN = /\/-\/A-(\w+)/i;
var PC_PRODUCT = /\/product\/([^/?#]+)/i;
var WALMART_IP = /\/ip\/(?:([^/?#]+)\/)?(\d{5,})/i;
function titleise(slug) {
  const cleaned = slug.replace(/[-_+]+/g, " ").replace(/\.(html?|aspx)$/i, "").replace(/\s+/g, " ").trim();
  if (!cleaned) return "";
  return cleaned.split(" ").map((w) => w.length > 2 ? w[0].toUpperCase() + w.slice(1) : w).join(" ");
}
function lastSegment(pathname) {
  const parts = pathname.split("/").filter(Boolean);
  return parts.length ? parts[parts.length - 1] : "";
}
function fromUrl(rawUrl, retailer) {
  let u;
  try {
    u = new URL(rawUrl);
  } catch {
    return null;
  }
  const path = u.pathname;
  const tcin = TARGET_TCIN.exec(path);
  if (tcin) {
    const slug = path.split("/-/")[0]?.replace(/^\/p\//, "") ?? "";
    return {
      externalId: tcin[1],
      name: titleise(slug) || tcin[1],
      url: `${u.origin}${path}`
    };
  }
  const wm = WALMART_IP.exec(path);
  if (wm) {
    const slug = wm[1] ?? "";
    const itemId = wm[2];
    return {
      externalId: itemId,
      name: titleise(slug) || itemId,
      url: `${u.origin}${path}`
    };
  }
  const pc = PC_PRODUCT.exec(path);
  if (pc) {
    const id = pc[1];
    const rest = path.slice(pc.index + pc[0].length).replace(/^\//, "");
    return {
      externalId: id,
      name: titleise(rest) || titleise(id),
      url: `${u.origin}${path}`
    };
  }
  const seg = lastSegment(path);
  if (!seg || seg.length < 3) return null;
  return {
    externalId: `${retailer}:${seg}`.toLowerCase(),
    name: titleise(seg),
    url: `${u.origin}${path}`
  };
}
function productKey(name, fallback) {
  const base = (name || fallback).toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 48);
  return `prd_${base || "unknown"}`;
}

// src/filter.ts
function fold(s) {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
}
function matches(item, filters) {
  if (!filters || filters.length === 0) return true;
  const hay = fold(`${item.name} ${item.url}`);
  return filters.some((f) => {
    const needle = fold(f).trim();
    return needle.length > 0 && hay.includes(needle);
  });
}
function applyFilters(items, filters) {
  if (!filters || filters.length === 0) return items;
  return items.filter((i) => matches(i, filters));
}
function dedupe(items) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const item of items) {
    if (!item.externalId || seen.has(item.externalId)) continue;
    seen.add(item.externalId);
    out.push(item);
  }
  return out;
}

// src/store.ts
function toPrice(v) {
  if (v === null || v === void 0 || v === "") return null;
  const n = typeof v === "number" ? v : Number(v);
  return Number.isFinite(n) && n > 0 ? n : null;
}
function toConfig(v) {
  if (v && typeof v === "object") return v;
  try {
    return JSON.parse(String(v || "{}"));
  } catch {
    return {};
  }
}
function toSource(row) {
  return {
    id: String(row.id),
    label: String(row.label ?? ""),
    retailer: String(row.retailer ?? ""),
    kind: row.kind,
    url: String(row.url ?? ""),
    via: row.via,
    config: toConfig(row.config),
    enabled: row.enabled === true,
    seeded: row.seeded === true,
    cursor: Number(row.cursor ?? 0),
    lastSweptAt: row.last_swept_at ? String(row.last_swept_at) : null,
    lastStatus: String(row.last_status ?? ""),
    lastCount: Number(row.last_count ?? 0)
  };
}
async function listSources(db2, via) {
  const rows = via ? await db2.query("SELECT * FROM sources WHERE enabled = true AND via = $1 ORDER BY id", [via]) : await db2.query("SELECT * FROM sources WHERE enabled = true ORDER BY id");
  return rows.map(toSource);
}
async function listAllSources(db2) {
  const rows = await db2.query("SELECT * FROM sources ORDER BY retailer, id");
  return rows.map(toSource);
}
async function getSource(db2, id) {
  const rows = await db2.query("SELECT * FROM sources WHERE id = $1", [id]);
  return rows[0] ? toSource(rows[0]) : null;
}
async function knownIds(db2, sourceId) {
  const rows = await db2.query(
    "SELECT external_id FROM discoveries WHERE source_id = $1",
    [sourceId]
  );
  return new Set(rows.map((r) => r.external_id));
}
async function recordDiscoveries(db2, sourceId, items, announce2) {
  if (items.length === 0) return [];
  const statements = items.map((item) => ({
    text: `INSERT INTO discoveries (source_id, external_id, url, name, price, announced)
           VALUES ($1, $2, $3, $4, $5, $6)
           ON CONFLICT (source_id, external_id) DO NOTHING`,
    params: [sourceId, item.externalId, item.url, item.name, item.price ?? null, !announce2]
  }));
  await db2.batch(statements);
  return announce2 ? items : [];
}
async function markAnnounced(db2, sourceId, externalIds) {
  if (externalIds.length === 0) return;
  await db2.query(
    "UPDATE discoveries SET announced = true WHERE source_id = $1 AND external_id = ANY($2)",
    [sourceId, externalIds]
  );
}
async function attachIdentity(db2, sourceId, retailer, item) {
  const existing = await db2.query(
    "SELECT product_key FROM aliases WHERE kind = $1 AND retailer = $2 AND value = $3",
    ["retailer_sku", retailer, item.externalId]
  );
  if (existing[0]?.product_key) return existing[0].product_key;
  const key = productKey(item.name, item.externalId);
  await db2.batch([
    {
      text: "INSERT INTO products (key, name) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING",
      params: [key, item.name]
    },
    {
      text: `INSERT INTO aliases (product_key, kind, retailer, value) VALUES ($1, $2, $3, $4)
             ON CONFLICT (kind, retailer, value) DO NOTHING`,
      params: [key, "retailer_sku", retailer, item.externalId]
    },
    {
      text: "UPDATE discoveries SET product_key = $1 WHERE source_id = $2 AND external_id = $3",
      params: [key, sourceId, item.externalId]
    }
  ]);
  return key;
}
async function finishSweep(db2, sourceId, status, count, seeded, cursor = 0) {
  await db2.query(
    `UPDATE sources
        SET last_swept_at = now(), last_status = $1, last_count = $2,
            seeded = $3, cursor = $4
      WHERE id = $5`,
    [status.slice(0, 300), count, seeded, cursor, sourceId]
  );
}
async function logEvent(db2, kind, message, data = null) {
  await db2.query("INSERT INTO events (kind, message, data) VALUES ($1, $2, $3)", [
    kind,
    message.slice(0, 1e3),
    data === null || data === void 0 ? null : JSON.stringify(data).slice(0, 4e3)
  ]);
}
async function watchlist(db2) {
  const rows = await db2.query(
    `SELECT p.key, p.name, p.release_date, a.retailer, a.value AS external_id,
            COALESCE(MAX(d.url), '') AS url
       FROM products p
       JOIN aliases a ON a.product_key = p.key AND a.kind = 'retailer_sku'
       LEFT JOIN discoveries d ON d.product_key = p.key
      GROUP BY p.key, p.name, p.release_date, a.retailer, a.value
      ORDER BY p.name, a.retailer`
  );
  return rows.map((r) => ({
    productKey: String(r.key),
    name: String(r.name ?? ""),
    retailer: String(r.retailer ?? ""),
    externalId: String(r.external_id ?? ""),
    url: String(r.url ?? ""),
    releaseDate: r.release_date ? String(r.release_date).slice(0, 10) : null
  }));
}
async function recordObservation(db2, obs) {
  const prior = await db2.query("SELECT state, price, seller_kind FROM watch_state WHERE product_key = $1 AND retailer = $2", [
    obs.productKey,
    obs.retailer
  ]);
  const before = prior[0] ?? null;
  const isFirst = before === null;
  const previousPrice = before ? toPrice(before.price) : null;
  const price = obs.price ?? null;
  const changed = !isFirst && (before.state !== obs.state || previousPrice !== price || before.seller_kind !== (obs.sellerKind ?? "unknown"));
  await db2.query(
    `INSERT INTO watch_state (
       product_key, retailer, external_id, url, state, confidence, price,
       seller_kind, seller_name, available_quantity, order_limit,
       is_preorder, release_date, note, last_checked_at, last_changed_at
     ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14, now(), now())
     ON CONFLICT (product_key, retailer) DO UPDATE SET
       external_id = EXCLUDED.external_id,
       url = EXCLUDED.url,
       state = EXCLUDED.state,
       confidence = EXCLUDED.confidence,
       price = EXCLUDED.price,
       seller_kind = EXCLUDED.seller_kind,
       seller_name = EXCLUDED.seller_name,
       available_quantity = EXCLUDED.available_quantity,
       order_limit = EXCLUDED.order_limit,
       is_preorder = EXCLUDED.is_preorder,
       release_date = EXCLUDED.release_date,
       note = EXCLUDED.note,
       last_checked_at = now(),
       -- Only move this when something actually moved, so "in stock since"
       -- means what it says instead of resetting on every poll.
       last_changed_at = CASE WHEN $15 THEN now() ELSE watch_state.last_changed_at END`,
    [
      obs.productKey,
      obs.retailer,
      obs.externalId ?? "",
      obs.url ?? "",
      obs.state,
      obs.confidence ?? "unknown",
      price,
      obs.sellerKind ?? "unknown",
      obs.sellerName ?? "",
      obs.availableQuantity ?? null,
      obs.orderLimit ?? null,
      obs.isPreOrder ?? false,
      obs.releaseDate ?? null,
      (obs.note ?? "").slice(0, 500),
      changed
    ]
  );
  if (changed || isFirst) {
    await db2.query(
      `INSERT INTO observations
         (product_key, retailer, state, confidence, price, seller_kind,
          seller_name, available_quantity, note)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
      [
        obs.productKey,
        obs.retailer,
        obs.state,
        obs.confidence ?? "unknown",
        price,
        obs.sellerKind ?? "unknown",
        obs.sellerName ?? "",
        obs.availableQuantity ?? null,
        (obs.note ?? "").slice(0, 500)
      ]
    );
  }
  return {
    changed,
    isFirst,
    previousState: before?.state ?? null,
    previousPrice
  };
}
async function dashboard(db2) {
  const rows = await db2.query(
    `SELECT p.key, p.name AS product_name, a.retailer, a.value AS external_id,
            COALESCE(w.url, MAX(d.url), '') AS url,
            COALESCE(w.state, 'unchecked') AS state,
            COALESCE(w.confidence, 'unknown') AS confidence,
            w.price, COALESCE(w.seller_kind, 'unknown') AS seller_kind,
            COALESCE(w.seller_name, '') AS seller_name,
            w.available_quantity, w.order_limit,
            COALESCE(w.is_preorder, false) AS is_preorder,
            COALESCE(w.release_date, p.release_date) AS release_date,
            COALESCE(w.note, '') AS note,
            w.last_checked_at, w.last_changed_at
       FROM products p
       JOIN aliases a ON a.product_key = p.key AND a.kind = 'retailer_sku'
       LEFT JOIN watch_state w ON w.product_key = p.key AND w.retailer = a.retailer
       LEFT JOIN discoveries d ON d.product_key = p.key
      GROUP BY p.key, p.name, p.release_date, a.retailer, a.value, w.url, w.state,
               w.confidence, w.price, w.seller_kind, w.seller_name,
               w.available_quantity, w.order_limit, w.is_preorder, w.release_date,
               w.note, w.last_checked_at, w.last_changed_at
      ORDER BY
        CASE COALESCE(w.state, 'unchecked')
          WHEN 'in' THEN 0 WHEN 'queue' THEN 1 WHEN 'unknown' THEN 2
          WHEN 'unchecked' THEN 3 ELSE 4 END,
        p.name, a.retailer`
  );
  return rows.map((r) => ({
    productKey: String(r.key),
    productName: String(r.product_name ?? ""),
    retailer: String(r.retailer ?? ""),
    externalId: String(r.external_id ?? ""),
    url: String(r.url ?? ""),
    state: String(r.state ?? "unchecked"),
    confidence: String(r.confidence ?? "unknown"),
    price: toPrice(r.price),
    sellerKind: String(r.seller_kind ?? "unknown"),
    sellerName: String(r.seller_name ?? ""),
    availableQuantity: r.available_quantity === null ? null : Number(r.available_quantity),
    orderLimit: r.order_limit === null ? null : Number(r.order_limit),
    isPreOrder: r.is_preorder === true,
    releaseDate: r.release_date ? String(r.release_date).slice(0, 10) : null,
    note: String(r.note ?? ""),
    lastCheckedAt: r.last_checked_at ? new Date(String(r.last_checked_at)).toISOString() : "",
    lastChangedAt: r.last_changed_at ? new Date(String(r.last_changed_at)).toISOString() : ""
  }));
}
async function recentObservations(db2, limit = 50) {
  const rows = await db2.query(
    `SELECT o.product_key, p.name AS product_name, o.retailer, o.state, o.price,
            o.seller_kind, o.seller_name, o.note, o.at
       FROM observations o
       JOIN products p ON p.key = o.product_key
      ORDER BY o.at DESC, o.id DESC
      LIMIT $1`,
    [Math.min(Math.max(limit, 1), 200)]
  );
  return rows.map((r) => ({
    productKey: String(r.product_key),
    productName: String(r.product_name ?? ""),
    retailer: String(r.retailer ?? ""),
    state: String(r.state ?? ""),
    price: toPrice(r.price),
    sellerKind: String(r.seller_kind ?? "unknown"),
    sellerName: String(r.seller_name ?? ""),
    note: String(r.note ?? ""),
    at: r.at ? new Date(String(r.at)).toISOString() : ""
  }));
}

// src/discover.ts
var DEFAULT_CHILD_LIMIT = 3;
var MAX_ITEMS_PER_SWEEP = 5e3;
function rotate(items, cursor, limit) {
  if (items.length === 0 || limit <= 0) return [];
  if (limit >= items.length) return items.slice();
  const start = (cursor % items.length + items.length) % items.length;
  const out = [];
  for (let i = 0; i < limit; i++) out.push(items[(start + i) % items.length]);
  return out;
}
function nextCursor(cursor, limit, total) {
  if (total <= 0 || limit <= 0) return 0;
  return (cursor + limit) % total;
}
function productsFromSitemap(xml, retailer) {
  const locs = extractLocs(xml);
  const out = [];
  for (const loc of locs) {
    const item = fromUrl(loc, retailer);
    if (item) out.push(item);
  }
  return out;
}
async function collect(source, fetchText2) {
  const config = source.config;
  const headers = config.headers ?? {};
  if (source.kind === "json_list") {
    const text = await fetchText2(source.url, headers);
    let payload;
    try {
      payload = JSON.parse(text);
    } catch {
      throw new FetchError("response was not valid JSON", 0, false);
    }
    return { items: parseJsonList(payload, config), childTotal: 0 };
  }
  if (source.kind === "sitemap" || source.kind === "sitemap_index") {
    const text = await fetchText2(source.url, headers);
    const kind = sitemapKind(text);
    if (kind === "index" || source.kind === "sitemap_index") {
      const children = extractLocs(text);
      const limit = config.childLimit ?? DEFAULT_CHILD_LIMIT;
      const window = rotate(children, source.cursor ?? 0, limit);
      const all = [];
      for (const child of window) {
        try {
          const childXml = await fetchText2(child, headers);
          all.push(...productsFromSitemap(childXml, source.retailer));
        } catch (err) {
          console.warn("child sitemap failed", child, String(err));
        }
        if (all.length >= MAX_ITEMS_PER_SWEEP) break;
      }
      return { items: all, childTotal: children.length };
    }
    return { items: productsFromSitemap(text, source.retailer), childTotal: 0 };
  }
  return { items: [], childTotal: 0 };
}
async function sweepSource(db2, source, fetchText2 = fetchText) {
  const config = source.config;
  const base = {
    sourceId: source.id,
    label: source.label,
    ok: true,
    seen: 0,
    fresh: [],
    seeded: source.seeded
  };
  let collected;
  try {
    collected = await collect(source, fetchText2);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await finishSweep(db2, source.id, `error: ${message}`, 0, source.seeded, source.cursor ?? 0);
    await logEvent(db2, "sweep_error", `${source.label}: ${message}`);
    return { ...base, ok: false, error: message };
  }
  const items = dedupe(applyFilters(collected.items, config.filters)).slice(0, MAX_ITEMS_PER_SWEEP);
  const known = await knownIds(db2, source.id);
  const fresh = items.filter((i) => !known.has(i.externalId));
  const alreadySeeded = source.seeded;
  const announced = await recordDiscoveries(db2, source.id, fresh, alreadySeeded);
  for (const item of announced) {
    await attachIdentity(db2, source.id, source.retailer, item);
  }
  const limit = config.childLimit ?? DEFAULT_CHILD_LIMIT;
  const advanced = nextCursor(source.cursor ?? 0, limit, collected.childTotal);
  const lapComplete = collected.childTotal === 0 || advanced === 0;
  const nowSeeded = alreadySeeded || lapComplete;
  const status = alreadySeeded ? `ok, ${fresh.length} new of ${items.length}` : lapComplete ? `seeded ${fresh.length} on final pass` : `seeding, pass ends at child ${advanced} of ${collected.childTotal}`;
  await finishSweep(db2, source.id, status, items.length, nowSeeded, advanced);
  if (!alreadySeeded) {
    await logEvent(
      db2,
      "seed",
      `${source.label}: recorded ${fresh.length} silently (${status})`
    );
  }
  return { ...base, seen: items.length, fresh: announced, seeded: nowSeeded };
}
async function sweepAll(db2, fetchText2 = fetchText) {
  const sources = await listSources(db2, "hub");
  const results = [];
  for (const source of sources) {
    results.push(await sweepSource(db2, source, fetchText2));
  }
  return results;
}

// src/notify.ts
var COLOR_NEW = 2059087;
var COLOR_OPS = 9069584;
var MAX_FIELDS = 20;
function clip(s, n) {
  return s.length <= n ? s : `${s.slice(0, n - 1)}\u2026`;
}
function buildDiscoveryEmbed(label, retailer, items, now) {
  const shown = items.slice(0, MAX_FIELDS);
  const fields = shown.map((i) => ({
    name: clip(i.name || i.externalId, 240),
    value: clip(i.url ? `[${i.externalId}](${i.url})` : i.externalId, 1e3)
  }));
  const extra = items.length - shown.length;
  return {
    title: `\u{1F195} ${items.length} new ${items.length === 1 ? "product" : "products"} \u2014 ${retailer}`,
    description: `Seen for the first time in **${label}**.` + (extra > 0 ? `
_${extra} more not listed._` : ""),
    color: COLOR_NEW,
    fields,
    footer: { text: "catalog discovery \xB7 not a stock signal" },
    timestamp: now
  };
}
function buildOpsEmbed(results, now) {
  const failed = results.filter((r) => !r.ok);
  if (failed.length === 0) return null;
  return {
    title: `\u26A0\uFE0F ${failed.length} source${failed.length === 1 ? "" : "s"} failed`,
    color: COLOR_OPS,
    fields: failed.slice(0, MAX_FIELDS).map((r) => ({
      name: clip(r.label, 240),
      value: clip(r.error ?? "unknown error", 1e3)
    })),
    timestamp: now
  };
}
async function post(url, embeds) {
  if (!url || embeds.length === 0) return;
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ embeds: embeds.slice(0, 10) })
    });
    if (!res.ok && res.status !== 204) {
      const detail = await res.text().catch(() => "");
      console.warn("discord rejected the post", res.status, detail.slice(0, 300));
    }
  } catch (err) {
    console.warn("discord unreachable", err instanceof Error ? err.message : String(err));
  }
}
async function announce(webhookUrl, label, retailer, items, now) {
  if (items.length === 0) return;
  await post(webhookUrl, [buildDiscoveryEmbed(label, retailer, items, now)]);
}
async function reportOps(webhookUrl, results, now) {
  const embed = buildOpsEmbed(results, now);
  if (embed) await post(webhookUrl, [embed]);
}

// src/auth.ts
var SESSION_COOKIE = "hub_session";
var SESSION_HOURS = 24 * 14;
function b64url(bytes) {
  return Buffer.from(bytes).toString("base64url");
}
async function hmac(secret, message) {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return b64url(new Uint8Array(sig));
}
function safeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}
async function mintSession(secret, now = Date.now()) {
  const expires = now + SESSION_HOURS * 3600 * 1e3;
  const payload = String(expires);
  return `${payload}.${await hmac(secret, payload)}`;
}
async function sessionValid(secret, token, now = Date.now()) {
  if (!token) return false;
  const dot = token.lastIndexOf(".");
  if (dot < 1) return false;
  const payload = token.slice(0, dot);
  const signature = token.slice(dot + 1);
  const expected = await hmac(secret, payload);
  if (!safeEqual(signature, expected)) return false;
  const expires = Number(payload);
  return Number.isFinite(expires) && expires > now;
}
function readCookie(request, name) {
  const header = request.headers.get("cookie") ?? "";
  for (const part of header.split(";")) {
    const [k, ...rest] = part.trim().split("=");
    if (k === name) return decodeURIComponent(rest.join("="));
  }
  return null;
}
function sessionCookie(value, secure) {
  const bits = [
    `${SESSION_COOKIE}=${encodeURIComponent(value)}`,
    "Path=/",
    // HttpOnly: script on the page can never read it, so an injected script
    // cannot post the session anywhere.
    "HttpOnly",
    // Lax: the cookie is not sent on cross-site POSTs, which is the CSRF that
    // would otherwise let another tab trigger a buy.
    "SameSite=Lax",
    `Max-Age=${SESSION_HOURS * 3600}`
  ];
  if (secure) bits.push("Secure");
  return bits.join("; ");
}
function clearCookie(secure) {
  const bits = [`${SESSION_COOKIE}=`, "Path=/", "HttpOnly", "SameSite=Lax", "Max-Age=0"];
  if (secure) bits.push("Secure");
  return bits.join("; ");
}
async function identify(request, env2) {
  const header = request.headers.get("Authorization") ?? "";
  if (env2.INGEST_TOKEN && header.startsWith("Bearer ")) {
    if (safeEqual(header.slice(7), env2.INGEST_TOKEN)) return "watcher";
  }
  if (env2.APP_PASSWORD) {
    const cookie = readCookie(request, SESSION_COOKIE);
    if (await sessionValid(env2.APP_PASSWORD, cookie)) return "browser";
  }
  return "none";
}

// src/page.ts
function esc(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
var STYLE = `
:root {
  color-scheme: light dark;
  --bg: #fbfaf8; --panel: #ffffff; --line: #e6e2dc;
  --ink: #1c1a17; --muted: #6d675e;
  --in: #1c6b45; --in-bg: #e6f4ec;
  --out: #7a736a; --out-bg: #f1efec;
  --warn: #8a5a10; --warn-bg: #fdf1dd;
  --alert: #a3341f; --alert-bg: #fbeae6;
  --accent: #2a5db0;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #16150f; --panel: #1e1d17; --line: #33312a;
    --ink: #edeae4; --muted: #a09a90;
    --in: #6fd39d; --in-bg: #14301f;
    --out: #8f887e; --out-bg: #242219;
    --warn: #e0b060; --warn-bg: #33270f;
    --alert: #f0907a; --alert-bg: #3a1d16;
    --accent: #8fb4f5;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--ink);
  font: 15px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
}
main { max-width: 1000px; margin: 0 auto; padding: 28px 20px 80px; }
header { display: flex; align-items: baseline; gap: 14px; flex-wrap: wrap; margin-bottom: 4px; }
h1 { font-size: 21px; margin: 0; letter-spacing: -0.01em; }
.sub { color: var(--muted); font-size: 13px; }
.bar { display: flex; gap: 10px; align-items: center; margin: 18px 0 20px; flex-wrap: wrap; }
button, .btn {
  font: inherit; padding: 7px 13px; border-radius: 8px; cursor: pointer;
  border: 1px solid var(--line); background: var(--panel); color: var(--ink);
}
button:hover { border-color: var(--muted); }
.card {
  background: var(--panel); border: 1px solid var(--line);
  border-radius: 12px; padding: 14px 16px; margin-bottom: 10px;
}
.row { display: flex; gap: 14px; align-items: flex-start; flex-wrap: wrap; }
.grow { flex: 1 1 260px; min-width: 0; }
.name { font-weight: 600; margin-bottom: 2px; }
.meta { color: var(--muted); font-size: 13px; }
.price { font-variant-numeric: tabular-nums; font-size: 19px; font-weight: 600; white-space: nowrap; }
.pill {
  display: inline-block; padding: 2px 9px; border-radius: 999px;
  font-size: 12px; font-weight: 600; letter-spacing: 0.02em; white-space: nowrap;
}
.s-in { background: var(--in-bg); color: var(--in); }
.s-out { background: var(--out-bg); color: var(--out); }
.s-unknown, .s-unchecked, .s-queue { background: var(--warn-bg); color: var(--warn); }
.flag { background: var(--alert-bg); color: var(--alert); }
a { color: var(--accent); }
.empty { color: var(--muted); padding: 30px 0; text-align: center; }
.stale { color: var(--alert); font-weight: 600; }
table { width: 100%; border-collapse: collapse; font-size: 13px; }
td { padding: 6px 8px; border-top: 1px solid var(--line); vertical-align: top; }
h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 0.06em;
     color: var(--muted); margin: 34px 0 10px; }
.login { max-width: 340px; margin: 16vh auto; }
input[type=password] {
  font: inherit; width: 100%; padding: 9px 11px; border-radius: 8px;
  border: 1px solid var(--line); background: var(--panel); color: var(--ink);
}
.err { color: var(--alert); font-size: 13px; min-height: 20px; }
`;
function loginPage(message = "") {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Hub</title><style>${STYLE}</style></head>
<body><main class="login">
  <h1>Hub</h1>
  <p class="sub">Sign in to see what's being watched.</p>
  <form method="POST" action="/login" style="margin-top:18px">
    <input type="password" name="password" placeholder="Password" autofocus required
           autocomplete="current-password">
    <div class="err" style="margin:8px 0">${esc(message)}</div>
    <button type="submit" style="width:100%">Sign in</button>
  </form>
</main></body></html>`;
}
function dashboardPage() {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Hub</title><style>${STYLE}</style></head>
<body><main>
  <header>
    <h1>Watching</h1>
    <span class="sub" id="summary">loading\u2026</span>
  </header>

  <div class="bar">
    <button id="refresh">Refresh</button>
    <label class="sub"><input type="checkbox" id="auto" checked> auto every 30s</label>
    <span class="grow"></span>
    <a class="btn" href="/logout">Sign out</a>
  </div>

  <div id="watches"></div>

  <h2>Recent changes</h2>
  <div class="card"><table id="feed"><tbody></tbody></table></div>
</main>
<script>
const money = (n) => n === null || n === undefined ? '\u2014' : '$' + Number(n).toFixed(2);

function ago(iso) {
  if (!iso) return 'never';
  const s = Math.max(0, (Date.now() - new Date(iso).getTime()) / 1000);
  if (s < 60) return Math.round(s) + 's ago';
  if (s < 3600) return Math.round(s / 60) + 'm ago';
  if (s < 86400) return Math.round(s / 3600) + 'h ago';
  return Math.round(s / 86400) + 'd ago';
}

// Anything older than five minutes is not a live reading. Say so loudly
// rather than showing a stale price as though it were current.
const STALE_MS = 5 * 60 * 1000;

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
}

function watchCard(w) {
  const card = el('div', 'card');
  const row = el('div', 'row');

  const left = el('div', 'grow');
  const name = el('div', 'name', w.productName);
  left.appendChild(name);

  const meta = el('div', 'meta');
  meta.append(w.retailer + ' \xB7 ' + (w.externalId || '\u2014'));
  if (w.url) {
    meta.append(' \xB7 ');
    const a = el('a', null, 'open');
    a.href = w.url; a.target = '_blank'; a.rel = 'noreferrer';
    meta.appendChild(a);
  }
  left.appendChild(meta);

  const flags = el('div', 'meta');
  flags.style.marginTop = '6px';

  const pill = el('span', 'pill s-' + w.state,
    w.state === 'in' ? 'IN STOCK' :
    w.state === 'out' ? 'out of stock' :
    w.state === 'unchecked' ? 'never checked' : w.state);
  flags.appendChild(pill);

  // A marketplace seller at any price is not a restock at retail. This is the
  // Walmart trap made visible rather than left in a note nobody reads.
  if (w.sellerKind === 'marketplace') {
    flags.append(' ');
    const s = el('span', 'pill flag', 'marketplace: ' + (w.sellerName || 'third party'));
    flags.appendChild(s);
  }
  if (w.confidence !== 'exact' && w.state !== 'unchecked') {
    flags.append(' ');
    flags.appendChild(el('span', 'pill s-unknown', w.confidence + ' read'));
  }
  if (w.isPreOrder) {
    flags.append(' ');
    flags.appendChild(el('span', 'pill s-queue',
      'preorder' + (w.releaseDate ? ' \xB7 ' + w.releaseDate : '')));
  }
  left.appendChild(flags);

  if (w.note) {
    const note = el('div', 'meta', w.note);
    note.style.marginTop = '6px';
    left.appendChild(note);
  }

  const right = el('div');
  right.style.textAlign = 'right';
  right.appendChild(el('div', 'price', money(w.price)));

  const checked = el('div', 'meta');
  const stale = w.lastCheckedAt && (Date.now() - new Date(w.lastCheckedAt).getTime()) > STALE_MS;
  checked.textContent = 'checked ' + ago(w.lastCheckedAt);
  if (stale || !w.lastCheckedAt) checked.className = 'meta stale';
  right.appendChild(checked);

  if (w.state === 'in' && w.lastChangedAt) {
    right.appendChild(el('div', 'meta', 'since ' + ago(w.lastChangedAt)));
  }
  if (w.availableQuantity !== null && w.availableQuantity !== undefined) {
    right.appendChild(el('div', 'meta', w.availableQuantity + ' available'));
  }

  row.append(left, right);
  card.appendChild(row);
  return card;
}

async function load() {
  let data;
  try {
    const res = await fetch('/api/dashboard', { headers: { 'Accept': 'application/json' } });
    if (res.status === 401) { location.href = '/login'; return; }
    data = await res.json();
  } catch (err) {
    document.getElementById('summary').textContent = 'could not reach the hub';
    return;
  }

  const list = document.getElementById('watches');
  list.textContent = '';

  if (!data.watches.length) {
    list.appendChild(el('div', 'empty', 'Nothing is being watched yet. Run the seed.'));
  } else {
    for (const w of data.watches) list.appendChild(watchCard(w));
  }

  const inStock = data.watches.filter((w) => w.state === 'in').length;
  const never = data.watches.filter((w) => w.state === 'unchecked').length;
  const parts = [data.watches.length + ' watched'];
  if (inStock) parts.push(inStock + ' in stock');
  if (never) parts.push(never + ' never checked');
  document.getElementById('summary').textContent = parts.join(' \xB7 ');

  const feed = document.querySelector('#feed tbody');
  feed.textContent = '';
  if (!data.recent.length) {
    const tr = document.createElement('tr');
    const td = el('td', 'meta', 'Nothing has changed yet.');
    td.colSpan = 4; tr.appendChild(td); feed.appendChild(tr);
  }
  for (const o of data.recent) {
    const tr = document.createElement('tr');
    tr.appendChild(el('td', 'meta', ago(o.at)));
    tr.appendChild(el('td', null, o.productName));
    tr.appendChild(el('td', 'meta', o.retailer));
    const td = el('td');
    td.style.textAlign = 'right';
    td.append(o.state + ' \xB7 ' + money(o.price));
    tr.appendChild(td);
    feed.appendChild(tr);
  }
}

document.getElementById('refresh').addEventListener('click', load);
let timer = setInterval(load, 30000);
document.getElementById('auto').addEventListener('change', (e) => {
  clearInterval(timer);
  if (e.target.checked) timer = setInterval(load, 30000);
});
load();
</script>
</body></html>`;
}

// src/app.ts
function json(body, status = 200) {
  return new Response(JSON.stringify(body, null, 2), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8" }
  });
}
async function publish(db2, env2, results, now) {
  for (const result of results) {
    if (!result.ok || result.fresh.length === 0) continue;
    const source = await getSource(db2, result.sourceId);
    await announce(
      env2.DISCORD_WEBHOOK_URL,
      result.label,
      source?.retailer ?? "",
      result.fresh,
      now
    );
    await markAnnounced(
      db2,
      result.sourceId,
      result.fresh.map((f) => f.externalId)
    );
  }
  const opsUrl = env2.DISCORD_OPS_WEBHOOK_URL || env2.DISCORD_WEBHOOK_URL;
  await reportOps(opsUrl, results, now);
}
function html(body, status = 200, headers = {}) {
  return new Response(body, {
    status,
    headers: { "Content-Type": "text/html; charset=utf-8", ...headers }
  });
}
function redirect(to, headers = {}) {
  return new Response(null, { status: 303, headers: { Location: to, ...headers } });
}
function createHandler(db2, env2) {
  return async function handle(request) {
    const url = new URL(request.url);
    const path = url.pathname.replace(/\/+$/, "") || "/";
    const now = (/* @__PURE__ */ new Date()).toISOString();
    if (request.method === "GET" && path === "/health") {
      const sources = await listSources(db2);
      return json({
        ok: true,
        sources: sources.map((s) => ({
          id: s.id,
          label: s.label,
          via: s.via,
          seeded: s.seeded,
          lastSweptAt: s.lastSweptAt,
          lastStatus: s.lastStatus,
          lastCount: s.lastCount
        }))
      });
    }
    const secure = url.protocol === "https:";
    if (path === "/login") {
      if (request.method === "GET") return html(loginPage());
      const form = await request.formData().catch(() => null);
      const given = String(form?.get("password") ?? "");
      if (!env2.APP_PASSWORD) {
        return html(loginPage("No password is set on this deployment."), 500);
      }
      if (!safeEqual(given, env2.APP_PASSWORD)) {
        await new Promise((r) => setTimeout(r, 400));
        return html(loginPage("That is not the password."), 401);
      }
      return redirect("/", {
        "Set-Cookie": sessionCookie(await mintSession(env2.APP_PASSWORD), secure)
      });
    }
    if (path === "/logout") {
      return redirect("/login", { "Set-Cookie": clearCookie(secure) });
    }
    const caller = await identify(request, env2);
    if (caller === "none") {
      const wantsHtml = (request.headers.get("accept") ?? "").includes("text/html");
      if (wantsHtml) return redirect("/login");
      return json({ error: "unauthorised" }, 401);
    }
    if (request.method === "GET" && (path === "/" || path === "/dashboard")) {
      return html(dashboardPage());
    }
    if (request.method === "GET" && path === "/api/dashboard") {
      const [watches, recent] = await Promise.all([
        dashboard(db2),
        recentObservations(db2, 40)
      ]);
      return json({ watches, recent, now });
    }
    if (request.method === "POST" && path === "/observations") {
      let body;
      try {
        body = await request.json();
      } catch {
        return json({ error: "body must be JSON" }, 400);
      }
      if (!Array.isArray(body.observations)) {
        return json({ error: "need observations[]" }, 400);
      }
      const results = [];
      const changes = [];
      for (const obs of body.observations) {
        if (!obs?.productKey || !obs?.retailer || !obs?.state) {
          results.push({
            productKey: obs?.productKey ?? "",
            retailer: obs?.retailer ?? "",
            changed: false,
            error: "need productKey, retailer and state"
          });
          continue;
        }
        try {
          const outcome = await recordObservation(db2, obs);
          results.push({ productKey: obs.productKey, retailer: obs.retailer, changed: outcome.changed });
          if (outcome.changed) changes.push({ obs, was: outcome.previousState });
        } catch (err) {
          results.push({
            productKey: obs.productKey,
            retailer: obs.retailer,
            changed: false,
            error: err.message
          });
        }
      }
      const cameIntoStock = changes.filter((c) => c.obs.state === "in" && c.was !== "in");
      if (cameIntoStock.length > 0 && env2.DISCORD_WEBHOOK_URL) {
        await announce(
          env2.DISCORD_WEBHOOK_URL,
          "In stock",
          cameIntoStock[0].obs.retailer,
          cameIntoStock.map((c) => ({
            externalId: c.obs.externalId ?? c.obs.productKey,
            name: c.obs.productKey,
            url: c.obs.url ?? "",
            price: c.obs.price ?? null
          })),
          now
        );
      }
      return json({
        recorded: results.length,
        changed: results.filter((r) => r.changed).length,
        failed: results.filter((r) => r.error).length,
        results
      });
    }
    if (request.method === "POST" && path === "/sweep") {
      const only = url.searchParams.get("source");
      let results;
      if (only) {
        const source = await getSource(db2, only);
        if (!source) return json({ error: `no source "${only}"` }, 404);
        results = [await sweepSource(db2, source)];
      } else {
        results = await sweepAll(db2);
      }
      await publish(db2, env2, results, now);
      return json({
        swept: results.map((r) => ({
          source: r.sourceId,
          ok: r.ok,
          seen: r.seen,
          new: r.fresh.length,
          error: r.error
        }))
      });
    }
    if (request.method === "POST" && path === "/ingest") {
      let body;
      try {
        body = await request.json();
      } catch {
        return json({ error: "body must be JSON" }, 400);
      }
      const sourceId = (body.sourceId ?? "").trim();
      if (!sourceId || !Array.isArray(body.items)) {
        return json({ error: "need sourceId and items[]" }, 400);
      }
      const source = await getSource(db2, sourceId);
      if (!source) return json({ error: `no source "${sourceId}"` }, 404);
      const config = source.config;
      const clean = dedupe(
        applyFilters(
          body.items.filter((i) => i && typeof i.externalId === "string" && i.externalId),
          config.filters
        )
      );
      const known = await knownIds(db2, sourceId);
      const fresh = clean.filter((i) => !known.has(i.externalId));
      const isFirstSweep = !source.seeded;
      const toAnnounce = await recordDiscoveries(db2, sourceId, fresh, !isFirstSweep);
      for (const item of toAnnounce) {
        await attachIdentity(db2, sourceId, source.retailer, item);
      }
      await finishSweep(
        db2,
        sourceId,
        isFirstSweep ? `seeded ${fresh.length} via watcher` : `watcher: ${fresh.length} new`,
        clean.length,
        true
      );
      if (toAnnounce.length > 0) {
        await announce(
          env2.DISCORD_WEBHOOK_URL,
          source.label,
          source.retailer,
          toAnnounce,
          now
        );
        await markAnnounced(
          db2,
          sourceId,
          toAnnounce.map((f) => f.externalId)
        );
      }
      return json({
        received: clean.length,
        new: fresh.length,
        announced: toAnnounce.length,
        seeded: isFirstSweep
      });
    }
    if ((request.method === "POST" || request.method === "GET") && path === "/probe") {
      const sources = await listAllSources(db2);
      const checks = [];
      for (const source of sources) {
        if (source.via === "watcher" || !source.url) {
          checks.push({
            id: source.id,
            retailer: source.retailer,
            via: source.via,
            enabled: source.enabled,
            verdict: "watcher \u2014 never fetched from here"
          });
          continue;
        }
        const config = source.config;
        const result = await probeUrl(source.url, config.headers ?? {});
        checks.push({
          id: source.id,
          retailer: source.retailer,
          via: source.via,
          enabled: source.enabled,
          status: result.status,
          ms: result.ms,
          verdict: result.ok ? `reachable \u2014 ${result.note}` : result.blocked ? `BLOCKED (${result.status}) \u2014 move this source to via='watcher'` : `failed (${result.status}) \u2014 ${result.note}`
        });
      }
      const blocked = checks.filter((c) => String(c.verdict).startsWith("BLOCKED")).length;
      return json({
        summary: blocked === 0 ? "every hub source is reachable from here" : `${blocked} source(s) blocked \u2014 those belong to the Watcher`,
        checks
      });
    }
    if (request.method === "GET" && path === "/watchlist") {
      const [products, sources] = await Promise.all([
        watchlist(db2),
        listSources(db2, "watcher")
      ]);
      return json({
        products,
        sources: sources.map((s) => ({
          id: s.id,
          label: s.label,
          retailer: s.retailer,
          url: s.url,
          config: s.config
        }))
      });
    }
    return json({ error: "not found" }, 404);
  };
}

// src/db.ts
function fromPostgres(client) {
  return {
    async query(text, params = []) {
      const rows = await client.unsafe(text, params);
      return rows;
    },
    async batch(statements) {
      if (statements.length === 0) return;
      await client.begin(async (tx) => {
        for (const s of statements) await tx.unsafe(s.text, s.params ?? []);
      });
    },
    async exec(script) {
      await client.unsafe(script);
    }
  };
}
function connectionStringFrom(env2) {
  const url = env2.DATABASE_URL ?? env2.POSTGRES_URL ?? "";
  if (!url) {
    throw new Error(
      'DATABASE_URL is not set.\n  Supabase dashboard \u2192 the "Connect" button at the top \u2192 Shared pooler,\n  transaction mode. Put it in .env.local for local work, and in the Vercel\n  project settings for deploys.'
    );
  }
  if (!/^postgres(ql)?:\/\//.test(url)) {
    throw new Error("DATABASE_URL does not look like a Postgres connection string.");
  }
  const host = /@([^/:?]+)/.exec(url)?.[1] ?? "";
  if (/^db\.[a-z0-9-]+\.supabase\.co$/i.test(host)) {
    const port = /:(\d+)\//.exec(url)?.[1] ?? "";
    const which = port === "6543" ? "the dedicated pooler" : "the direct connection";
    throw new Error(
      `That is ${which} (${host}), which is IPv6-only unless you pay for the
  IPv4 add-on \u2014 and Vercel is IPv4, so it would fail on every deploy.
  Use the SHARED pooler instead: its host contains "pooler.supabase.com"
  and the username has the project ref on it (postgres.<ref>).
  Supabase dashboard \u2192 "Connect" \u2192 Shared pooler \u2192 Transaction mode.`
    );
  }
  return url;
}

// src/server.ts
var cached = null;
function db() {
  if (cached) return cached;
  const client = postgres(connectionStringFrom(process.env), {
    // The pooler does not support prepared statements.
    prepare: false,
    max: 1,
    idle_timeout: 20,
    connect_timeout: 10
  });
  cached = fromPostgres(client);
  return cached;
}
function env() {
  return {
    DATABASE_URL: process.env.DATABASE_URL ?? "",
    DISCORD_WEBHOOK_URL: process.env.DISCORD_WEBHOOK_URL ?? "",
    DISCORD_OPS_WEBHOOK_URL: process.env.DISCORD_OPS_WEBHOOK_URL,
    INGEST_TOKEN: process.env.INGEST_TOKEN,
    APP_PASSWORD: process.env.APP_PASSWORD
  };
}
async function readBody(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}
async function handler(req, res) {
  const host = req.headers.host ?? "localhost";
  const proto = req.headers["x-forwarded-proto"] ?? "https";
  const url = new URL(req.url ?? "/", `${proto}://${host}`);
  const method = req.method ?? "GET";
  const hasBody = method !== "GET" && method !== "HEAD";
  const request = new Request(url, {
    method,
    headers: Object.entries(req.headers).flatMap(
      ([k, v]) => typeof v === "string" ? [[k, v]] : []
    ),
    ...hasBody ? { body: await readBody(req) } : {}
  });
  let response;
  try {
    response = await createHandler(db(), env())(request);
  } catch (err) {
    response = new Response(
      JSON.stringify({ error: err.message }, null, 2),
      { status: 500, headers: { "Content-Type": "application/json; charset=utf-8" } }
    );
  }
  res.statusCode = response.status;
  response.headers.forEach((value, key) => res.setHeader(key, value));
  res.end(Buffer.from(await response.arrayBuffer()));
}
export {
  handler as default
};
