/**
 * Build the single file Vercel deploys.
 *
 * The options live here rather than in a package.json string so that the build
 * and the test that checks the build cannot drift apart. If they could, the
 * test would be verifying a different artifact than the one that ships, which
 * is the whole failure it exists to prevent.
 *
 * ── Why the npm script is called `bundle` and not `build` ────────────────────
 *
 * Naming it `build` flipped Vercel out of zero-config into static-site mode,
 * and the deploy then failed with:
 *
 *   No Output Directory named "public" found after the Build completed.
 *
 * The bundle had been produced perfectly a line earlier. There is no static
 * output here — everything is one serverless function — so the fix is to have
 * no build step on Vercel at all. `api/index.js` is committed, Vercel deploys
 * it as-is, and nothing clever happens in between.
 *
 * The cost of committing a build artifact is that it can go stale. That is
 * paid for by a test which rebuilds and compares, so `npm test` fails if the
 * committed bundle no longer matches the source.
 */
import { resolve } from 'node:path';
import type { BuildOptions } from 'esbuild';

const root = resolve(import.meta.dirname, '..');

export const OUTFILE = resolve(root, 'api', 'index.js');

export const BUNDLE_OPTIONS: BuildOptions = {
  entryPoints: [resolve(root, 'src', 'server.ts')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  // Real dependencies stay real: Vercel installs them from package.json.
  packages: 'external',
  banner: { js: '// Generated by `npm run bundle` from src/server.ts. Do not edit.' },
};

async function main(): Promise<void> {
  const esbuild = await import('esbuild');
  const result = await esbuild.build({ ...BUNDLE_OPTIONS, outfile: OUTFILE, metafile: true });
  const bytes = Object.values(result.metafile!.outputs)[0]?.bytes ?? 0;
  console.log(`\n  api/index.js  ${(bytes / 1024).toFixed(1)}kb\n`);
}

// Only build when run directly, so importing the options costs nothing.
if (process.argv[1] && resolve(process.argv[1]) === resolve(import.meta.filename)) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
